// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package db

import (
	"context"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens
WHERE user_id = $1
  AND token = $2
`

type DeleteDeviceTokenParams struct {
	UserID int64  `db:"user_id" json:"user_id"`
	Token  string `db:"token" json:"token"`
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.UserID, arg.Token)
	return err
}

const deleteDeviceTokenByValue = `-- name: DeleteDeviceTokenByValue :exec
DELETE FROM device_tokens
WHERE token = $1
`

func (q *Queries) DeleteDeviceTokenByValue(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteDeviceTokenByValue, token)
	return err
}

const listDeviceTokensByUserID = `-- name: ListDeviceTokensByUserID :many
SELECT id, user_id, token, platform, device_id, last_seen_at, created_at, updated_at
FROM device_tokens
WHERE user_id = $1
ORDER BY last_seen_at DESC
`

func (q *Queries) ListDeviceTokensByUserID(ctx context.Context, userID int64) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.DeviceID,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (
    user_id,
    token,
    platform,
    device_id,
    last_seen_at
)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id, token) DO UPDATE SET
    platform = EXCLUDED.platform,
    device_id = EXCLUDED.device_id,
    last_seen_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, token, platform, device_id, last_seen_at, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID   int64          `db:"user_id" json:"user_id"`
	Token    string         `db:"token" json:"token"`
	Platform DevicePlatform `db:"platform" json:"platform"`
	DeviceID *string        `db:"device_id" json:"device_id"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken,
		arg.UserID,
		arg.Token,
		arg.Platform,
		arg.DeviceID,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.DeviceID,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
