// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flat_resident.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFlatResident = `-- name: AddFlatResident :one
INSERT INTO flat_residents (society_id, flat_id, user_id, role, status, is_primary, metadata, created_by)
VALUES ($1, $2, $3, $4, 'active', $5, COALESCE($7, '{}'::jsonb), $6)
RETURNING id, society_id, flat_id, user_id, role, status, is_primary, moved_in_at, moved_out_at, metadata, created_by, created_at, updated_at
`

type AddFlatResidentParams struct {
	SocietyID int64            `db:"society_id" json:"society_id"`
	FlatID    int64            `db:"flat_id" json:"flat_id"`
	UserID    int64            `db:"user_id" json:"user_id"`
	Role      FlatResidentRole `db:"role" json:"role"`
	IsPrimary bool             `db:"is_primary" json:"is_primary"`
	CreatedBy *int64           `db:"created_by" json:"created_by"`
	Metadata  interface{}      `db:"metadata" json:"metadata"`
}

func (q *Queries) AddFlatResident(ctx context.Context, arg AddFlatResidentParams) (FlatResident, error) {
	row := q.db.QueryRow(ctx, addFlatResident,
		arg.SocietyID,
		arg.FlatID,
		arg.UserID,
		arg.Role,
		arg.IsPrimary,
		arg.CreatedBy,
		arg.Metadata,
	)
	var i FlatResident
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.IsPrimary,
		&i.MovedInAt,
		&i.MovedOutAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearPrimaryFlatResident = `-- name: ClearPrimaryFlatResident :exec
UPDATE flat_residents
SET is_primary = FALSE,
    role = 'family',
    updated_at = NOW()
WHERE society_id = $1
  AND flat_id = $2
  AND status = 'active'
  AND is_primary = TRUE
`

type ClearPrimaryFlatResidentParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
}

func (q *Queries) ClearPrimaryFlatResident(ctx context.Context, arg ClearPrimaryFlatResidentParams) error {
	_, err := q.db.Exec(ctx, clearPrimaryFlatResident, arg.SocietyID, arg.FlatID)
	return err
}

const countActiveFlatResidents = `-- name: CountActiveFlatResidents :one
SELECT COUNT(*)
FROM flat_residents
WHERE society_id = $1 AND flat_id = $2 AND status = 'active'
`

type CountActiveFlatResidentsParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
}

func (q *Queries) CountActiveFlatResidents(ctx context.Context, arg CountActiveFlatResidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveFlatResidents, arg.SocietyID, arg.FlatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivePrimaryFlatResidents = `-- name: CountActivePrimaryFlatResidents :one
SELECT COUNT(*)
FROM flat_residents
WHERE society_id = $1 AND flat_id = $2 AND status = 'active' AND is_primary = TRUE
`

type CountActivePrimaryFlatResidentsParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
}

func (q *Queries) CountActivePrimaryFlatResidents(ctx context.Context, arg CountActivePrimaryFlatResidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePrimaryFlatResidents, arg.SocietyID, arg.FlatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFlatResident = `-- name: GetFlatResident :one
SELECT
    fr.id, fr.society_id, fr.flat_id, fr.user_id, fr.role, fr.status, fr.is_primary, fr.moved_in_at, fr.moved_out_at, fr.metadata, fr.created_by, fr.created_at, fr.updated_at,
    u.full_name AS user_name,
    u.email AS user_email,
    u.phone_number AS user_phone,
    f.flat_number AS flat_number,
    f.block AS block,
    f.floor AS floor,
    s.name AS society_name,
    s.society_code AS society_code
FROM flat_residents fr
JOIN users u ON u.id = fr.user_id
JOIN flats f ON f.id = fr.flat_id
JOIN societies s ON s.id = fr.society_id
WHERE ($1::bigint IS NULL OR fr.id = $1::bigint)
  AND ($2::bigint IS NULL OR fr.society_id = $2::bigint)
  AND ($3::bigint IS NULL OR fr.flat_id = $3::bigint)
  AND ($4::bigint IS NULL OR fr.user_id = $4::bigint)
  AND ($5::flat_resident_role IS NULL OR fr.role = $5::flat_resident_role)
  AND ($6::flat_resident_status IS NULL OR fr.status = $6::flat_resident_status)
  AND ($7::bool IS NULL OR fr.is_primary = $7::bool)
ORDER BY fr.id DESC
LIMIT 1
`

type GetFlatResidentParams struct {
	ID        *int64              `db:"id" json:"id"`
	SocietyID *int64              `db:"society_id" json:"society_id"`
	FlatID    *int64              `db:"flat_id" json:"flat_id"`
	UserID    *int64              `db:"user_id" json:"user_id"`
	Role      *FlatResidentRole   `db:"role" json:"role"`
	Status    *FlatResidentStatus `db:"status" json:"status"`
	IsPrimary *bool               `db:"is_primary" json:"is_primary"`
}

type GetFlatResidentRow struct {
	ID          int64              `db:"id" json:"id"`
	SocietyID   int64              `db:"society_id" json:"society_id"`
	FlatID      int64              `db:"flat_id" json:"flat_id"`
	UserID      int64              `db:"user_id" json:"user_id"`
	Role        FlatResidentRole   `db:"role" json:"role"`
	Status      FlatResidentStatus `db:"status" json:"status"`
	IsPrimary   bool               `db:"is_primary" json:"is_primary"`
	MovedInAt   pgtype.Timestamptz `db:"moved_in_at" json:"moved_in_at"`
	MovedOutAt  pgtype.Timestamptz `db:"moved_out_at" json:"moved_out_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedBy   *int64             `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserName    string             `db:"user_name" json:"user_name"`
	UserEmail   *string            `db:"user_email" json:"user_email"`
	UserPhone   *string            `db:"user_phone" json:"user_phone"`
	FlatNumber  string             `db:"flat_number" json:"flat_number"`
	Block       *string            `db:"block" json:"block"`
	Floor       *string            `db:"floor" json:"floor"`
	SocietyName string             `db:"society_name" json:"society_name"`
	SocietyCode string             `db:"society_code" json:"society_code"`
}

func (q *Queries) GetFlatResident(ctx context.Context, arg GetFlatResidentParams) (GetFlatResidentRow, error) {
	row := q.db.QueryRow(ctx, getFlatResident,
		arg.ID,
		arg.SocietyID,
		arg.FlatID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.IsPrimary,
	)
	var i GetFlatResidentRow
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.IsPrimary,
		&i.MovedInAt,
		&i.MovedOutAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserPhone,
		&i.FlatNumber,
		&i.Block,
		&i.Floor,
		&i.SocietyName,
		&i.SocietyCode,
	)
	return i, err
}

const listFlatResidents = `-- name: ListFlatResidents :many
SELECT
    fr.id, fr.society_id, fr.flat_id, fr.user_id, fr.role, fr.status, fr.is_primary, fr.moved_in_at, fr.moved_out_at, fr.metadata, fr.created_by, fr.created_at, fr.updated_at,
    u.full_name AS user_name,
    u.email AS user_email,
    u.phone_number AS user_phone,
    f.flat_number AS flat_number,
    f.block AS block,
    f.floor AS floor,
    s.name AS society_name,
    s.society_code AS society_code
FROM flat_residents fr
JOIN users u ON u.id = fr.user_id
JOIN flats f ON f.id = fr.flat_id
JOIN societies s ON s.id = fr.society_id
WHERE ($1::bigint IS NULL OR fr.id = $1::bigint)
  AND ($2::bigint IS NULL OR fr.society_id = $2::bigint)
  AND ($3::bigint IS NULL OR fr.flat_id = $3::bigint)
  AND ($4::bigint IS NULL OR fr.user_id = $4::bigint)
  AND ($5::flat_resident_role IS NULL OR fr.role = $5::flat_resident_role)
  AND ($6::flat_resident_status IS NULL OR fr.status = $6::flat_resident_status)
  AND ($7::bool IS NULL OR fr.is_primary = $7::bool)
  AND (
      $8::text = ''
      OR u.full_name ILIKE '%' || $8::text || '%'
      OR COALESCE(u.email, '') ILIKE '%' || $8::text || '%'
      OR COALESCE(u.phone_number, '') ILIKE '%' || $8::text || '%'
      OR f.flat_number ILIKE '%' || $8::text || '%'
      OR COALESCE(f.block, '') ILIKE '%' || $8::text || '%'
      OR fr.role::text ILIKE '%' || $8::text || '%'
      OR fr.status::text ILIKE '%' || $8::text || '%'
  )
ORDER BY fr.moved_in_at DESC
LIMIT $10 OFFSET $9
`

type ListFlatResidentsParams struct {
	ID        *int64              `db:"id" json:"id"`
	SocietyID *int64              `db:"society_id" json:"society_id"`
	FlatID    *int64              `db:"flat_id" json:"flat_id"`
	UserID    *int64              `db:"user_id" json:"user_id"`
	Role      *FlatResidentRole   `db:"role" json:"role"`
	Status    *FlatResidentStatus `db:"status" json:"status"`
	IsPrimary *bool               `db:"is_primary" json:"is_primary"`
	Search    string              `db:"search" json:"search"`
	Offset    int32               `db:"offset" json:"offset"`
	Limit     int32               `db:"limit" json:"limit"`
}

type ListFlatResidentsRow struct {
	ID          int64              `db:"id" json:"id"`
	SocietyID   int64              `db:"society_id" json:"society_id"`
	FlatID      int64              `db:"flat_id" json:"flat_id"`
	UserID      int64              `db:"user_id" json:"user_id"`
	Role        FlatResidentRole   `db:"role" json:"role"`
	Status      FlatResidentStatus `db:"status" json:"status"`
	IsPrimary   bool               `db:"is_primary" json:"is_primary"`
	MovedInAt   pgtype.Timestamptz `db:"moved_in_at" json:"moved_in_at"`
	MovedOutAt  pgtype.Timestamptz `db:"moved_out_at" json:"moved_out_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedBy   *int64             `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserName    string             `db:"user_name" json:"user_name"`
	UserEmail   *string            `db:"user_email" json:"user_email"`
	UserPhone   *string            `db:"user_phone" json:"user_phone"`
	FlatNumber  string             `db:"flat_number" json:"flat_number"`
	Block       *string            `db:"block" json:"block"`
	Floor       *string            `db:"floor" json:"floor"`
	SocietyName string             `db:"society_name" json:"society_name"`
	SocietyCode string             `db:"society_code" json:"society_code"`
}

func (q *Queries) ListFlatResidents(ctx context.Context, arg ListFlatResidentsParams) ([]ListFlatResidentsRow, error) {
	rows, err := q.db.Query(ctx, listFlatResidents,
		arg.ID,
		arg.SocietyID,
		arg.FlatID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.IsPrimary,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFlatResidentsRow{}
	for rows.Next() {
		var i ListFlatResidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.FlatID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.IsPrimary,
			&i.MovedInAt,
			&i.MovedOutAt,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserPhone,
			&i.FlatNumber,
			&i.Block,
			&i.Floor,
			&i.SocietyName,
			&i.SocietyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveOutFlatResident = `-- name: MoveOutFlatResident :one
UPDATE flat_residents
SET status = 'moved_out', is_primary = FALSE, moved_out_at = NOW(), updated_at = NOW()
WHERE ($1::bigint IS NULL OR id = $1::bigint)
  AND ($2::bigint IS NULL OR society_id = $2::bigint)
  AND ($3::bigint IS NULL OR flat_id = $3::bigint)
  AND ($4::bigint IS NULL OR user_id = $4::bigint)
  AND status = 'active'
RETURNING id, society_id, flat_id, user_id, role, status, is_primary, moved_in_at, moved_out_at, metadata, created_by, created_at, updated_at
`

type MoveOutFlatResidentParams struct {
	ID        *int64 `db:"id" json:"id"`
	SocietyID *int64 `db:"society_id" json:"society_id"`
	FlatID    *int64 `db:"flat_id" json:"flat_id"`
	UserID    *int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) MoveOutFlatResident(ctx context.Context, arg MoveOutFlatResidentParams) (FlatResident, error) {
	row := q.db.QueryRow(ctx, moveOutFlatResident,
		arg.ID,
		arg.SocietyID,
		arg.FlatID,
		arg.UserID,
	)
	var i FlatResident
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.IsPrimary,
		&i.MovedInAt,
		&i.MovedOutAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeFlatResident = `-- name: RemoveFlatResident :exec
UPDATE flat_residents
SET status = 'inactive', is_primary = FALSE, updated_at = NOW()
WHERE ($1::bigint IS NULL OR id = $1::bigint)
  AND ($2::bigint IS NULL OR society_id = $2::bigint)
  AND ($3::bigint IS NULL OR flat_id = $3::bigint)
  AND ($4::bigint IS NULL OR user_id = $4::bigint)
  AND status = 'active'
`

type RemoveFlatResidentParams struct {
	ID        *int64 `db:"id" json:"id"`
	SocietyID *int64 `db:"society_id" json:"society_id"`
	FlatID    *int64 `db:"flat_id" json:"flat_id"`
	UserID    *int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveFlatResident(ctx context.Context, arg RemoveFlatResidentParams) error {
	_, err := q.db.Exec(ctx, removeFlatResident,
		arg.ID,
		arg.SocietyID,
		arg.FlatID,
		arg.UserID,
	)
	return err
}

const setPrimaryFlatResident = `-- name: SetPrimaryFlatResident :one
UPDATE flat_residents
SET is_primary = TRUE,
    role = 'owner',
    updated_at = NOW()
WHERE society_id = $1
  AND flat_id = $2
  AND id = $3
  AND status = 'active'
RETURNING id, society_id, flat_id, user_id, role, status, is_primary, moved_in_at, moved_out_at, metadata, created_by, created_at, updated_at
`

type SetPrimaryFlatResidentParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) SetPrimaryFlatResident(ctx context.Context, arg SetPrimaryFlatResidentParams) (FlatResident, error) {
	row := q.db.QueryRow(ctx, setPrimaryFlatResident, arg.SocietyID, arg.FlatID, arg.ID)
	var i FlatResident
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.IsPrimary,
		&i.MovedInAt,
		&i.MovedOutAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlatResidentRole = `-- name: UpdateFlatResidentRole :one
UPDATE flat_residents
SET role = $1, updated_at = NOW()
WHERE ($2::bigint IS NULL OR id = $2::bigint)
  AND ($3::bigint IS NULL OR society_id = $3::bigint)
  AND ($4::bigint IS NULL OR flat_id = $4::bigint)
  AND ($5::bigint IS NULL OR user_id = $5::bigint)
  AND status = 'active'
RETURNING id, society_id, flat_id, user_id, role, status, is_primary, moved_in_at, moved_out_at, metadata, created_by, created_at, updated_at
`

type UpdateFlatResidentRoleParams struct {
	Role      FlatResidentRole `db:"role" json:"role"`
	ID        *int64           `db:"id" json:"id"`
	SocietyID *int64           `db:"society_id" json:"society_id"`
	FlatID    *int64           `db:"flat_id" json:"flat_id"`
	UserID    *int64           `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateFlatResidentRole(ctx context.Context, arg UpdateFlatResidentRoleParams) (FlatResident, error) {
	row := q.db.QueryRow(ctx, updateFlatResidentRole,
		arg.Role,
		arg.ID,
		arg.SocietyID,
		arg.FlatID,
		arg.UserID,
	)
	var i FlatResident
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.IsPrimary,
		&i.MovedInAt,
		&i.MovedOutAt,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
