// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flat_member_invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFlatMemberInvite = `-- name: AcceptFlatMemberInvite :one
UPDATE flat_member_invites
SET status = 'accepted',
    updated_at = NOW()
WHERE id = $1
  AND status = 'pending'
  AND expires_at > NOW()
RETURNING id, society_id, flat_id, invited_by, role, phone, email, full_name, token_hash, expires_at, status, created_at, updated_at
`

func (q *Queries) AcceptFlatMemberInvite(ctx context.Context, id int64) (FlatMemberInvite, error) {
	row := q.db.QueryRow(ctx, acceptFlatMemberInvite, id)
	var i FlatMemberInvite
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.InvitedBy,
		&i.Role,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelFlatMemberInvite = `-- name: CancelFlatMemberInvite :one
UPDATE flat_member_invites
SET status = 'cancelled',
    updated_at = NOW()
WHERE id = $1
  AND society_id = $2
  AND flat_id = $3
  AND status = 'pending'
RETURNING id, society_id, flat_id, invited_by, role, phone, email, full_name, token_hash, expires_at, status, created_at, updated_at
`

type CancelFlatMemberInviteParams struct {
	ID        int64 `db:"id" json:"id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
}

func (q *Queries) CancelFlatMemberInvite(ctx context.Context, arg CancelFlatMemberInviteParams) (FlatMemberInvite, error) {
	row := q.db.QueryRow(ctx, cancelFlatMemberInvite, arg.ID, arg.SocietyID, arg.FlatID)
	var i FlatMemberInvite
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.InvitedBy,
		&i.Role,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlatMemberInvite = `-- name: CreateFlatMemberInvite :one
INSERT INTO flat_member_invites (
    society_id,
    flat_id,
    invited_by,
    role,
    phone,
    email,
    full_name,
    token_hash,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, society_id, flat_id, invited_by, role, phone, email, full_name, token_hash, expires_at, status, created_at, updated_at
`

type CreateFlatMemberInviteParams struct {
	SocietyID int64                `db:"society_id" json:"society_id"`
	FlatID    int64                `db:"flat_id" json:"flat_id"`
	InvitedBy int64                `db:"invited_by" json:"invited_by"`
	Role      FlatMemberInviteRole `db:"role" json:"role"`
	Phone     *string              `db:"phone" json:"phone"`
	Email     *string              `db:"email" json:"email"`
	FullName  string               `db:"full_name" json:"full_name"`
	TokenHash string               `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz   `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateFlatMemberInvite(ctx context.Context, arg CreateFlatMemberInviteParams) (FlatMemberInvite, error) {
	row := q.db.QueryRow(ctx, createFlatMemberInvite,
		arg.SocietyID,
		arg.FlatID,
		arg.InvitedBy,
		arg.Role,
		arg.Phone,
		arg.Email,
		arg.FullName,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i FlatMemberInvite
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.InvitedBy,
		&i.Role,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireOldFlatMemberInvites = `-- name: ExpireOldFlatMemberInvites :exec
UPDATE flat_member_invites
SET status = 'expired',
    updated_at = NOW()
WHERE status = 'pending'
  AND expires_at < NOW()
`

func (q *Queries) ExpireOldFlatMemberInvites(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOldFlatMemberInvites)
	return err
}

const getFlatMemberInviteByID = `-- name: GetFlatMemberInviteByID :one
SELECT id, society_id, flat_id, invited_by, role, phone, email, full_name, token_hash, expires_at, status, created_at, updated_at
FROM flat_member_invites
WHERE id = $1
  AND society_id = $2
`

type GetFlatMemberInviteByIDParams struct {
	ID        int64 `db:"id" json:"id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
}

func (q *Queries) GetFlatMemberInviteByID(ctx context.Context, arg GetFlatMemberInviteByIDParams) (FlatMemberInvite, error) {
	row := q.db.QueryRow(ctx, getFlatMemberInviteByID, arg.ID, arg.SocietyID)
	var i FlatMemberInvite
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.InvitedBy,
		&i.Role,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlatMemberInviteByTokenHash = `-- name: GetFlatMemberInviteByTokenHash :one
SELECT id, society_id, flat_id, invited_by, role, phone, email, full_name, token_hash, expires_at, status, created_at, updated_at
FROM flat_member_invites
WHERE token_hash = $1
`

func (q *Queries) GetFlatMemberInviteByTokenHash(ctx context.Context, tokenHash string) (FlatMemberInvite, error) {
	row := q.db.QueryRow(ctx, getFlatMemberInviteByTokenHash, tokenHash)
	var i FlatMemberInvite
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.InvitedBy,
		&i.Role,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingFlatMemberInvites = `-- name: ListPendingFlatMemberInvites :many
SELECT id, society_id, flat_id, invited_by, role, phone, email, full_name, token_hash, expires_at, status, created_at, updated_at
FROM flat_member_invites
WHERE society_id = $1
  AND flat_id = $2
  AND status = 'pending'
ORDER BY created_at DESC
`

type ListPendingFlatMemberInvitesParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
}

func (q *Queries) ListPendingFlatMemberInvites(ctx context.Context, arg ListPendingFlatMemberInvitesParams) ([]FlatMemberInvite, error) {
	rows, err := q.db.Query(ctx, listPendingFlatMemberInvites, arg.SocietyID, arg.FlatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlatMemberInvite{}
	for rows.Next() {
		var i FlatMemberInvite
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.FlatID,
			&i.InvitedBy,
			&i.Role,
			&i.Phone,
			&i.Email,
			&i.FullName,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
