// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flat_claim.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveFlatClaim = `-- name: ApproveFlatClaim :one
UPDATE flat_claim_requests
SET status = 'approved', reviewed_by = $3, reviewed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND society_id = $2 AND status = 'pending'
RETURNING id, society_id, flat_id, user_id, requested_role, requested_primary, status, note, rejection_reason, reviewed_by, reviewed_at, cancelled_at, metadata, created_at, updated_at
`

type ApproveFlatClaimParams struct {
	ID         int64  `db:"id" json:"id"`
	SocietyID  int64  `db:"society_id" json:"society_id"`
	ReviewedBy *int64 `db:"reviewed_by" json:"reviewed_by"`
}

func (q *Queries) ApproveFlatClaim(ctx context.Context, arg ApproveFlatClaimParams) (FlatClaimRequest, error) {
	row := q.db.QueryRow(ctx, approveFlatClaim, arg.ID, arg.SocietyID, arg.ReviewedBy)
	var i FlatClaimRequest
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.UserID,
		&i.RequestedRole,
		&i.RequestedPrimary,
		&i.Status,
		&i.Note,
		&i.RejectionReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CancelledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelMyFlatClaim = `-- name: CancelMyFlatClaim :one
UPDATE flat_claim_requests
SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND status = 'pending'
RETURNING id, society_id, flat_id, user_id, requested_role, requested_primary, status, note, rejection_reason, reviewed_by, reviewed_at, cancelled_at, metadata, created_at, updated_at
`

type CancelMyFlatClaimParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) CancelMyFlatClaim(ctx context.Context, arg CancelMyFlatClaimParams) (FlatClaimRequest, error) {
	row := q.db.QueryRow(ctx, cancelMyFlatClaim, arg.ID, arg.UserID)
	var i FlatClaimRequest
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.UserID,
		&i.RequestedRole,
		&i.RequestedPrimary,
		&i.Status,
		&i.Note,
		&i.RejectionReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CancelledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlatClaim = `-- name: GetFlatClaim :one
SELECT
    fc.id, fc.society_id, fc.flat_id, fc.user_id, fc.requested_role, fc.requested_primary, fc.status, fc.note, fc.rejection_reason, fc.reviewed_by, fc.reviewed_at, fc.cancelled_at, fc.metadata, fc.created_at, fc.updated_at,
    u.full_name AS user_name,
    u.email AS user_email,
    u.phone_number AS user_phone,
    f.flat_number AS flat_number,
    f.block AS block,
    f.floor AS floor,
    f.status AS flat_status,
    s.name AS society_name,
    s.society_code AS society_code,
    reviewer.full_name AS reviewer_name,
    reviewer.email AS reviewer_email,
    reviewer.phone_number AS reviewer_phone
FROM flat_claim_requests fc
JOIN users u ON u.id = fc.user_id
LEFT JOIN users reviewer ON reviewer.id = fc.reviewed_by
JOIN flats f ON f.id = fc.flat_id
JOIN societies s ON s.id = fc.society_id
WHERE ($1::bigint IS NULL OR fc.id = $1::bigint)
  AND ($2::bigint IS NULL OR fc.society_id = $2::bigint)
  AND ($3::bigint IS NULL OR fc.flat_id = $3::bigint)
  AND ($4::bigint IS NULL OR fc.user_id = $4::bigint)
  AND ($5::flat_claim_status IS NULL OR fc.status = $5::flat_claim_status)
ORDER BY fc.id DESC
LIMIT 1
`

type GetFlatClaimParams struct {
	ID        *int64           `db:"id" json:"id"`
	SocietyID *int64           `db:"society_id" json:"society_id"`
	FlatID    *int64           `db:"flat_id" json:"flat_id"`
	UserID    *int64           `db:"user_id" json:"user_id"`
	Status    *FlatClaimStatus `db:"status" json:"status"`
}

type GetFlatClaimRow struct {
	ID               int64              `db:"id" json:"id"`
	SocietyID        int64              `db:"society_id" json:"society_id"`
	FlatID           int64              `db:"flat_id" json:"flat_id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	RequestedRole    FlatResidentRole   `db:"requested_role" json:"requested_role"`
	RequestedPrimary bool               `db:"requested_primary" json:"requested_primary"`
	Status           FlatClaimStatus    `db:"status" json:"status"`
	Note             *string            `db:"note" json:"note"`
	RejectionReason  *string            `db:"rejection_reason" json:"rejection_reason"`
	ReviewedBy       *int64             `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	CancelledAt      pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	Metadata         []byte             `db:"metadata" json:"metadata"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserName         string             `db:"user_name" json:"user_name"`
	UserEmail        *string            `db:"user_email" json:"user_email"`
	UserPhone        *string            `db:"user_phone" json:"user_phone"`
	FlatNumber       string             `db:"flat_number" json:"flat_number"`
	Block            *string            `db:"block" json:"block"`
	Floor            *string            `db:"floor" json:"floor"`
	FlatStatus       FlatStatus         `db:"flat_status" json:"flat_status"`
	SocietyName      string             `db:"society_name" json:"society_name"`
	SocietyCode      string             `db:"society_code" json:"society_code"`
	ReviewerName     *string            `db:"reviewer_name" json:"reviewer_name"`
	ReviewerEmail    *string            `db:"reviewer_email" json:"reviewer_email"`
	ReviewerPhone    *string            `db:"reviewer_phone" json:"reviewer_phone"`
}

func (q *Queries) GetFlatClaim(ctx context.Context, arg GetFlatClaimParams) (GetFlatClaimRow, error) {
	row := q.db.QueryRow(ctx, getFlatClaim,
		arg.ID,
		arg.SocietyID,
		arg.FlatID,
		arg.UserID,
		arg.Status,
	)
	var i GetFlatClaimRow
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.UserID,
		&i.RequestedRole,
		&i.RequestedPrimary,
		&i.Status,
		&i.Note,
		&i.RejectionReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CancelledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserPhone,
		&i.FlatNumber,
		&i.Block,
		&i.Floor,
		&i.FlatStatus,
		&i.SocietyName,
		&i.SocietyCode,
		&i.ReviewerName,
		&i.ReviewerEmail,
		&i.ReviewerPhone,
	)
	return i, err
}

const getFlatClaimStats = `-- name: GetFlatClaimStats :one
SELECT
    COUNT(*) AS total_claims,
    COUNT(*) FILTER (WHERE status = 'pending') AS pending_claims,
    COUNT(*) FILTER (WHERE status = 'approved') AS approved_claims,
    COUNT(*) FILTER (WHERE status = 'rejected') AS rejected_claims,
    COUNT(*) FILTER (WHERE status = 'cancelled') AS cancelled_claims
FROM flat_claim_requests fc
WHERE fc.society_id = $1::bigint
`

type GetFlatClaimStatsRow struct {
	TotalClaims     int64 `db:"total_claims" json:"total_claims"`
	PendingClaims   int64 `db:"pending_claims" json:"pending_claims"`
	ApprovedClaims  int64 `db:"approved_claims" json:"approved_claims"`
	RejectedClaims  int64 `db:"rejected_claims" json:"rejected_claims"`
	CancelledClaims int64 `db:"cancelled_claims" json:"cancelled_claims"`
}

func (q *Queries) GetFlatClaimStats(ctx context.Context, societyID int64) (GetFlatClaimStatsRow, error) {
	row := q.db.QueryRow(ctx, getFlatClaimStats, societyID)
	var i GetFlatClaimStatsRow
	err := row.Scan(
		&i.TotalClaims,
		&i.PendingClaims,
		&i.ApprovedClaims,
		&i.RejectedClaims,
		&i.CancelledClaims,
	)
	return i, err
}

const listFlatClaims = `-- name: ListFlatClaims :many
SELECT
    fc.id, fc.society_id, fc.flat_id, fc.user_id, fc.requested_role, fc.requested_primary, fc.status, fc.note, fc.rejection_reason, fc.reviewed_by, fc.reviewed_at, fc.cancelled_at, fc.metadata, fc.created_at, fc.updated_at,
    u.full_name AS user_name,
    u.email AS user_email,
    u.phone_number AS user_phone,
    f.flat_number AS flat_number,
    f.block AS block,
    f.floor AS floor,
    f.status AS flat_status,
    s.name AS society_name,
    s.society_code AS society_code,
    reviewer.full_name AS reviewer_name,
    reviewer.email AS reviewer_email,
    reviewer.phone_number AS reviewer_phone
FROM flat_claim_requests fc
JOIN users u ON u.id = fc.user_id
LEFT JOIN users reviewer ON reviewer.id = fc.reviewed_by
JOIN flats f ON f.id = fc.flat_id
JOIN societies s ON s.id = fc.society_id
WHERE ($1::bigint IS NULL OR fc.id = $1::bigint)
  AND ($2::bigint IS NULL OR fc.society_id = $2::bigint)
  AND ($3::bigint IS NULL OR fc.flat_id = $3::bigint)
  AND ($4::bigint IS NULL OR fc.user_id = $4::bigint)
  AND ($5::flat_claim_status IS NULL OR fc.status = $5::flat_claim_status)
  AND (
      $6::text = ''
      OR (
          $7::text IN ('', 'all', 'claimant')
          AND (
              u.full_name ILIKE '%' || $6::text || '%'
              OR COALESCE(u.email, '') ILIKE '%' || $6::text || '%'
              OR COALESCE(u.phone_number, '') ILIKE '%' || $6::text || '%'
          )
      )
      OR (
          $7::text IN ('', 'all', 'flat')
          AND (
              f.flat_number ILIKE '%' || $6::text || '%'
              OR COALESCE(f.block, '') ILIKE '%' || $6::text || '%'
              OR COALESCE(f.floor, '') ILIKE '%' || $6::text || '%'
          )
      )
      OR (
          $7::text IN ('', 'all', 'reviewer')
          AND (
              COALESCE(reviewer.full_name, '') ILIKE '%' || $6::text || '%'
              OR COALESCE(reviewer.email, '') ILIKE '%' || $6::text || '%'
              OR COALESCE(reviewer.phone_number, '') ILIKE '%' || $6::text || '%'
          )
      )
      OR (
          $7::text IN ('', 'all')
          AND fc.status::text ILIKE '%' || $6::text || '%'
      )
  )
ORDER BY fc.created_at DESC
LIMIT $9 OFFSET $8
`

type ListFlatClaimsParams struct {
	ID         *int64           `db:"id" json:"id"`
	SocietyID  *int64           `db:"society_id" json:"society_id"`
	FlatID     *int64           `db:"flat_id" json:"flat_id"`
	UserID     *int64           `db:"user_id" json:"user_id"`
	Status     *FlatClaimStatus `db:"status" json:"status"`
	Search     string           `db:"search" json:"search"`
	SearchMode string           `db:"search_mode" json:"search_mode"`
	Offset     int32            `db:"offset" json:"offset"`
	Limit      int32            `db:"limit" json:"limit"`
}

type ListFlatClaimsRow struct {
	ID               int64              `db:"id" json:"id"`
	SocietyID        int64              `db:"society_id" json:"society_id"`
	FlatID           int64              `db:"flat_id" json:"flat_id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	RequestedRole    FlatResidentRole   `db:"requested_role" json:"requested_role"`
	RequestedPrimary bool               `db:"requested_primary" json:"requested_primary"`
	Status           FlatClaimStatus    `db:"status" json:"status"`
	Note             *string            `db:"note" json:"note"`
	RejectionReason  *string            `db:"rejection_reason" json:"rejection_reason"`
	ReviewedBy       *int64             `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	CancelledAt      pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	Metadata         []byte             `db:"metadata" json:"metadata"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserName         string             `db:"user_name" json:"user_name"`
	UserEmail        *string            `db:"user_email" json:"user_email"`
	UserPhone        *string            `db:"user_phone" json:"user_phone"`
	FlatNumber       string             `db:"flat_number" json:"flat_number"`
	Block            *string            `db:"block" json:"block"`
	Floor            *string            `db:"floor" json:"floor"`
	FlatStatus       FlatStatus         `db:"flat_status" json:"flat_status"`
	SocietyName      string             `db:"society_name" json:"society_name"`
	SocietyCode      string             `db:"society_code" json:"society_code"`
	ReviewerName     *string            `db:"reviewer_name" json:"reviewer_name"`
	ReviewerEmail    *string            `db:"reviewer_email" json:"reviewer_email"`
	ReviewerPhone    *string            `db:"reviewer_phone" json:"reviewer_phone"`
}

func (q *Queries) ListFlatClaims(ctx context.Context, arg ListFlatClaimsParams) ([]ListFlatClaimsRow, error) {
	rows, err := q.db.Query(ctx, listFlatClaims,
		arg.ID,
		arg.SocietyID,
		arg.FlatID,
		arg.UserID,
		arg.Status,
		arg.Search,
		arg.SearchMode,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFlatClaimsRow{}
	for rows.Next() {
		var i ListFlatClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.FlatID,
			&i.UserID,
			&i.RequestedRole,
			&i.RequestedPrimary,
			&i.Status,
			&i.Note,
			&i.RejectionReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CancelledAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserPhone,
			&i.FlatNumber,
			&i.Block,
			&i.Floor,
			&i.FlatStatus,
			&i.SocietyName,
			&i.SocietyCode,
			&i.ReviewerName,
			&i.ReviewerEmail,
			&i.ReviewerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectFlatClaim = `-- name: RejectFlatClaim :one
UPDATE flat_claim_requests
SET status = 'rejected', reviewed_by = $3, reviewed_at = NOW(), rejection_reason = $4, updated_at = NOW()
WHERE id = $1 AND society_id = $2 AND status = 'pending'
RETURNING id, society_id, flat_id, user_id, requested_role, requested_primary, status, note, rejection_reason, reviewed_by, reviewed_at, cancelled_at, metadata, created_at, updated_at
`

type RejectFlatClaimParams struct {
	ID              int64   `db:"id" json:"id"`
	SocietyID       int64   `db:"society_id" json:"society_id"`
	ReviewedBy      *int64  `db:"reviewed_by" json:"reviewed_by"`
	RejectionReason *string `db:"rejection_reason" json:"rejection_reason"`
}

func (q *Queries) RejectFlatClaim(ctx context.Context, arg RejectFlatClaimParams) (FlatClaimRequest, error) {
	row := q.db.QueryRow(ctx, rejectFlatClaim,
		arg.ID,
		arg.SocietyID,
		arg.ReviewedBy,
		arg.RejectionReason,
	)
	var i FlatClaimRequest
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.UserID,
		&i.RequestedRole,
		&i.RequestedPrimary,
		&i.Status,
		&i.Note,
		&i.RejectionReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CancelledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitFlatClaim = `-- name: SubmitFlatClaim :one
INSERT INTO flat_claim_requests (
    society_id, flat_id, user_id, requested_role, requested_primary, status, note, metadata
) VALUES (
    $1, $2, $3, $4, $5, 'pending', $6, COALESCE($7, '{}'::jsonb)
)
RETURNING id, society_id, flat_id, user_id, requested_role, requested_primary, status, note, rejection_reason, reviewed_by, reviewed_at, cancelled_at, metadata, created_at, updated_at
`

type SubmitFlatClaimParams struct {
	SocietyID        int64            `db:"society_id" json:"society_id"`
	FlatID           int64            `db:"flat_id" json:"flat_id"`
	UserID           int64            `db:"user_id" json:"user_id"`
	RequestedRole    FlatResidentRole `db:"requested_role" json:"requested_role"`
	RequestedPrimary bool             `db:"requested_primary" json:"requested_primary"`
	Note             *string          `db:"note" json:"note"`
	Metadata         interface{}      `db:"metadata" json:"metadata"`
}

func (q *Queries) SubmitFlatClaim(ctx context.Context, arg SubmitFlatClaimParams) (FlatClaimRequest, error) {
	row := q.db.QueryRow(ctx, submitFlatClaim,
		arg.SocietyID,
		arg.FlatID,
		arg.UserID,
		arg.RequestedRole,
		arg.RequestedPrimary,
		arg.Note,
		arg.Metadata,
	)
	var i FlatClaimRequest
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.UserID,
		&i.RequestedRole,
		&i.RequestedPrimary,
		&i.Status,
		&i.Note,
		&i.RejectionReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CancelledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
