// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockFlat = `-- name: BlockFlat :one
UPDATE flats
SET status = 'blocked', updated_at = NOW()
WHERE ($1::bigint IS NULL OR id = $1::bigint)
  AND ($2::bigint IS NULL OR society_id = $2::bigint)
  AND is_active = TRUE
RETURNING id, society_id, block, floor, flat_number, status, is_active, metadata, created_by, created_at, updated_at
`

type BlockFlatParams struct {
	ID        *int64 `db:"id" json:"id"`
	SocietyID *int64 `db:"society_id" json:"society_id"`
}

func (q *Queries) BlockFlat(ctx context.Context, arg BlockFlatParams) (Flat, error) {
	row := q.db.QueryRow(ctx, blockFlat, arg.ID, arg.SocietyID)
	var i Flat
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.Block,
		&i.Floor,
		&i.FlatNumber,
		&i.Status,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countFlats = `-- name: CountFlats :one
SELECT COUNT(*)
FROM flats f
JOIN societies s ON s.id = f.society_id
LEFT JOIN LATERAL (
    SELECT u.full_name
    FROM flat_residents fr
    JOIN users u ON u.id = fr.user_id
    WHERE fr.society_id = f.society_id
      AND fr.flat_id = f.id
      AND fr.status = 'active'
      AND fr.is_primary = TRUE
    LIMIT 1
) primary_resident ON TRUE
WHERE ($1::bigint IS NULL OR f.id = $1::bigint)
  AND ($2::bigint IS NULL OR f.society_id = $2::bigint)
  AND ($3::text IS NULL OR f.block = $3::text)
  AND ($4::text IS NULL OR f.floor = $4::text)
  AND ($5::text IS NULL OR f.flat_number = $5::text)
  AND ($6::flat_status IS NULL OR f.status = $6::flat_status)
  AND ($7::bool IS NULL OR f.is_active = $7::bool)
  AND (
      $8::text = ''
      OR f.flat_number ILIKE '%' || $8::text || '%'
      OR COALESCE(f.block, '') ILIKE '%' || $8::text || '%'
      OR COALESCE(f.floor, '') ILIKE '%' || $8::text || '%'
      OR f.status::text ILIKE '%' || $8::text || '%'
      OR s.name ILIKE '%' || $8::text || '%'
      OR s.society_code ILIKE '%' || $8::text || '%'
      OR COALESCE(primary_resident.full_name, '') ILIKE '%' || $8::text || '%'
  )
`

type CountFlatsParams struct {
	ID         *int64      `db:"id" json:"id"`
	SocietyID  *int64      `db:"society_id" json:"society_id"`
	Block      *string     `db:"block" json:"block"`
	Floor      *string     `db:"floor" json:"floor"`
	FlatNumber *string     `db:"flat_number" json:"flat_number"`
	Status     *FlatStatus `db:"status" json:"status"`
	IsActive   *bool       `db:"is_active" json:"is_active"`
	Search     string      `db:"search" json:"search"`
}

func (q *Queries) CountFlats(ctx context.Context, arg CountFlatsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFlats,
		arg.ID,
		arg.SocietyID,
		arg.Block,
		arg.Floor,
		arg.FlatNumber,
		arg.Status,
		arg.IsActive,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFlat = `-- name: CreateFlat :one
INSERT INTO flats (society_id, block, floor, flat_number, status, is_active, metadata, created_by)
VALUES ($1, $2, $3, $4, 'vacant', TRUE, COALESCE($6, '{}'::jsonb), $5)
RETURNING id, society_id, block, floor, flat_number, status, is_active, metadata, created_by, created_at, updated_at
`

type CreateFlatParams struct {
	SocietyID  int64       `db:"society_id" json:"society_id"`
	Block      *string     `db:"block" json:"block"`
	Floor      *string     `db:"floor" json:"floor"`
	FlatNumber string      `db:"flat_number" json:"flat_number"`
	CreatedBy  *int64      `db:"created_by" json:"created_by"`
	Metadata   interface{} `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateFlat(ctx context.Context, arg CreateFlatParams) (Flat, error) {
	row := q.db.QueryRow(ctx, createFlat,
		arg.SocietyID,
		arg.Block,
		arg.Floor,
		arg.FlatNumber,
		arg.CreatedBy,
		arg.Metadata,
	)
	var i Flat
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.Block,
		&i.Floor,
		&i.FlatNumber,
		&i.Status,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateFlat = `-- name: DeactivateFlat :exec
UPDATE flats
SET is_active = FALSE, updated_at = NOW()
WHERE ($1::bigint IS NULL OR id = $1::bigint)
  AND ($2::bigint IS NULL OR society_id = $2::bigint)
`

type DeactivateFlatParams struct {
	ID        *int64 `db:"id" json:"id"`
	SocietyID *int64 `db:"society_id" json:"society_id"`
}

func (q *Queries) DeactivateFlat(ctx context.Context, arg DeactivateFlatParams) error {
	_, err := q.db.Exec(ctx, deactivateFlat, arg.ID, arg.SocietyID)
	return err
}

const getFlat = `-- name: GetFlat :one
SELECT
    f.id, f.society_id, f.block, f.floor, f.flat_number, f.status, f.is_active, f.metadata, f.created_by, f.created_at, f.updated_at,
    s.name AS society_name,
    s.society_code AS society_code
FROM flats f
JOIN societies s ON s.id = f.society_id
WHERE ($1::bigint IS NULL OR f.id = $1::bigint)
  AND ($2::bigint IS NULL OR f.society_id = $2::bigint)
  AND ($3::text IS NULL OR f.block = $3::text)
  AND ($4::text IS NULL OR f.floor = $4::text)
  AND ($5::text IS NULL OR f.flat_number = $5::text)
  AND ($6::flat_status IS NULL OR f.status = $6::flat_status)
  AND ($7::bool IS NULL OR f.is_active = $7::bool)
ORDER BY f.id DESC
LIMIT 1
`

type GetFlatParams struct {
	ID         *int64      `db:"id" json:"id"`
	SocietyID  *int64      `db:"society_id" json:"society_id"`
	Block      *string     `db:"block" json:"block"`
	Floor      *string     `db:"floor" json:"floor"`
	FlatNumber *string     `db:"flat_number" json:"flat_number"`
	Status     *FlatStatus `db:"status" json:"status"`
	IsActive   *bool       `db:"is_active" json:"is_active"`
}

type GetFlatRow struct {
	ID          int64              `db:"id" json:"id"`
	SocietyID   int64              `db:"society_id" json:"society_id"`
	Block       *string            `db:"block" json:"block"`
	Floor       *string            `db:"floor" json:"floor"`
	FlatNumber  string             `db:"flat_number" json:"flat_number"`
	Status      FlatStatus         `db:"status" json:"status"`
	IsActive    bool               `db:"is_active" json:"is_active"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedBy   *int64             `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SocietyName string             `db:"society_name" json:"society_name"`
	SocietyCode string             `db:"society_code" json:"society_code"`
}

func (q *Queries) GetFlat(ctx context.Context, arg GetFlatParams) (GetFlatRow, error) {
	row := q.db.QueryRow(ctx, getFlat,
		arg.ID,
		arg.SocietyID,
		arg.Block,
		arg.Floor,
		arg.FlatNumber,
		arg.Status,
		arg.IsActive,
	)
	var i GetFlatRow
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.Block,
		&i.Floor,
		&i.FlatNumber,
		&i.Status,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SocietyName,
		&i.SocietyCode,
	)
	return i, err
}

const getFlatStats = `-- name: GetFlatStats :one
SELECT
    $1::bigint AS society_id,
    COUNT(*) AS total_flats,
    COUNT(*) FILTER (WHERE status = 'vacant') AS vacant_flats,
    COUNT(*) FILTER (WHERE status = 'occupied') AS occupied_flats,
    COUNT(*) FILTER (WHERE status = 'blocked') AS blocked_flats,
    COUNT(*) FILTER (WHERE is_active = TRUE) AS active_flats,
    COUNT(*) FILTER (WHERE is_active = FALSE) AS inactive_flats
FROM flats
WHERE society_id = $1::bigint
`

type GetFlatStatsRow struct {
	SocietyID     int64 `db:"society_id" json:"society_id"`
	TotalFlats    int64 `db:"total_flats" json:"total_flats"`
	VacantFlats   int64 `db:"vacant_flats" json:"vacant_flats"`
	OccupiedFlats int64 `db:"occupied_flats" json:"occupied_flats"`
	BlockedFlats  int64 `db:"blocked_flats" json:"blocked_flats"`
	ActiveFlats   int64 `db:"active_flats" json:"active_flats"`
	InactiveFlats int64 `db:"inactive_flats" json:"inactive_flats"`
}

func (q *Queries) GetFlatStats(ctx context.Context, societyID int64) (GetFlatStatsRow, error) {
	row := q.db.QueryRow(ctx, getFlatStats, societyID)
	var i GetFlatStatsRow
	err := row.Scan(
		&i.SocietyID,
		&i.TotalFlats,
		&i.VacantFlats,
		&i.OccupiedFlats,
		&i.BlockedFlats,
		&i.ActiveFlats,
		&i.InactiveFlats,
	)
	return i, err
}

const listFlats = `-- name: ListFlats :many
SELECT
    f.id, f.society_id, f.block, f.floor, f.flat_number, f.status, f.is_active, f.metadata, f.created_by, f.created_at, f.updated_at,
    s.name AS society_name,
    s.society_code AS society_code,
    primary_resident.full_name AS primary_resident_name
FROM flats f
JOIN societies s ON s.id = f.society_id
LEFT JOIN LATERAL (
    SELECT u.full_name
    FROM flat_residents fr
    JOIN users u ON u.id = fr.user_id
    WHERE fr.society_id = f.society_id
      AND fr.flat_id = f.id
      AND fr.status = 'active'
      AND fr.is_primary = TRUE
    LIMIT 1
) primary_resident ON TRUE
WHERE ($1::bigint IS NULL OR f.id = $1::bigint)
  AND ($2::bigint IS NULL OR f.society_id = $2::bigint)
  AND ($3::text IS NULL OR f.block = $3::text)
  AND ($4::text IS NULL OR f.floor = $4::text)
  AND ($5::text IS NULL OR f.flat_number = $5::text)
  AND ($6::flat_status IS NULL OR f.status = $6::flat_status)
  AND ($7::bool IS NULL OR f.is_active = $7::bool)
  AND (
      $8::text = ''
      OR f.flat_number ILIKE '%' || $8::text || '%'
      OR COALESCE(f.block, '') ILIKE '%' || $8::text || '%'
      OR COALESCE(f.floor, '') ILIKE '%' || $8::text || '%'
      OR f.status::text ILIKE '%' || $8::text || '%'
      OR s.name ILIKE '%' || $8::text || '%'
      OR s.society_code ILIKE '%' || $8::text || '%'
      OR COALESCE(primary_resident.full_name, '') ILIKE '%' || $8::text || '%'
  )
ORDER BY f.created_at DESC
LIMIT $10 OFFSET $9
`

type ListFlatsParams struct {
	ID         *int64      `db:"id" json:"id"`
	SocietyID  *int64      `db:"society_id" json:"society_id"`
	Block      *string     `db:"block" json:"block"`
	Floor      *string     `db:"floor" json:"floor"`
	FlatNumber *string     `db:"flat_number" json:"flat_number"`
	Status     *FlatStatus `db:"status" json:"status"`
	IsActive   *bool       `db:"is_active" json:"is_active"`
	Search     string      `db:"search" json:"search"`
	Offset     int32       `db:"offset" json:"offset"`
	Limit      int32       `db:"limit" json:"limit"`
}

type ListFlatsRow struct {
	ID                  int64              `db:"id" json:"id"`
	SocietyID           int64              `db:"society_id" json:"society_id"`
	Block               *string            `db:"block" json:"block"`
	Floor               *string            `db:"floor" json:"floor"`
	FlatNumber          string             `db:"flat_number" json:"flat_number"`
	Status              FlatStatus         `db:"status" json:"status"`
	IsActive            bool               `db:"is_active" json:"is_active"`
	Metadata            []byte             `db:"metadata" json:"metadata"`
	CreatedBy           *int64             `db:"created_by" json:"created_by"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SocietyName         string             `db:"society_name" json:"society_name"`
	SocietyCode         string             `db:"society_code" json:"society_code"`
	PrimaryResidentName string             `db:"primary_resident_name" json:"primary_resident_name"`
}

func (q *Queries) ListFlats(ctx context.Context, arg ListFlatsParams) ([]ListFlatsRow, error) {
	rows, err := q.db.Query(ctx, listFlats,
		arg.ID,
		arg.SocietyID,
		arg.Block,
		arg.Floor,
		arg.FlatNumber,
		arg.Status,
		arg.IsActive,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFlatsRow{}
	for rows.Next() {
		var i ListFlatsRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.Block,
			&i.Floor,
			&i.FlatNumber,
			&i.Status,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SocietyName,
			&i.SocietyCode,
			&i.PrimaryResidentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFlatOccupied = `-- name: MarkFlatOccupied :one
UPDATE flats
SET status = 'occupied', updated_at = NOW()
WHERE id = $1 AND society_id = $2 AND is_active = TRUE AND status != 'blocked'
RETURNING id, society_id, block, floor, flat_number, status, is_active, metadata, created_by, created_at, updated_at
`

type MarkFlatOccupiedParams struct {
	ID        int64 `db:"id" json:"id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
}

func (q *Queries) MarkFlatOccupied(ctx context.Context, arg MarkFlatOccupiedParams) (Flat, error) {
	row := q.db.QueryRow(ctx, markFlatOccupied, arg.ID, arg.SocietyID)
	var i Flat
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.Block,
		&i.Floor,
		&i.FlatNumber,
		&i.Status,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFlatVacant = `-- name: MarkFlatVacant :one
UPDATE flats
SET status = 'vacant', updated_at = NOW()
WHERE id = $1 AND society_id = $2 AND is_active = TRUE AND status != 'blocked'
RETURNING id, society_id, block, floor, flat_number, status, is_active, metadata, created_by, created_at, updated_at
`

type MarkFlatVacantParams struct {
	ID        int64 `db:"id" json:"id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
}

func (q *Queries) MarkFlatVacant(ctx context.Context, arg MarkFlatVacantParams) (Flat, error) {
	row := q.db.QueryRow(ctx, markFlatVacant, arg.ID, arg.SocietyID)
	var i Flat
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.Block,
		&i.Floor,
		&i.FlatNumber,
		&i.Status,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unblockFlat = `-- name: UnblockFlat :one
UPDATE flats
SET status = 'vacant', updated_at = NOW()
WHERE ($1::bigint IS NULL OR id = $1::bigint)
  AND ($2::bigint IS NULL OR society_id = $2::bigint)
  AND status = 'blocked'
RETURNING id, society_id, block, floor, flat_number, status, is_active, metadata, created_by, created_at, updated_at
`

type UnblockFlatParams struct {
	ID        *int64 `db:"id" json:"id"`
	SocietyID *int64 `db:"society_id" json:"society_id"`
}

func (q *Queries) UnblockFlat(ctx context.Context, arg UnblockFlatParams) (Flat, error) {
	row := q.db.QueryRow(ctx, unblockFlat, arg.ID, arg.SocietyID)
	var i Flat
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.Block,
		&i.Floor,
		&i.FlatNumber,
		&i.Status,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlat = `-- name: UpdateFlat :one
UPDATE flats
SET
    block = COALESCE($1, block),
    floor = COALESCE($2, floor),
    flat_number = COALESCE($3, flat_number),
    status = COALESCE($4, status),
    is_active = COALESCE($5, is_active),
    metadata = COALESCE($6, metadata),
    updated_at = NOW()
WHERE ($7::bigint IS NULL OR id = $7::bigint)
  AND ($8::bigint IS NULL OR society_id = $8::bigint)
RETURNING id, society_id, block, floor, flat_number, status, is_active, metadata, created_by, created_at, updated_at
`

type UpdateFlatParams struct {
	Block      *string     `db:"block" json:"block"`
	Floor      *string     `db:"floor" json:"floor"`
	FlatNumber *string     `db:"flat_number" json:"flat_number"`
	Status     *FlatStatus `db:"status" json:"status"`
	IsActive   *bool       `db:"is_active" json:"is_active"`
	Metadata   []byte      `db:"metadata" json:"metadata"`
	ID         *int64      `db:"id" json:"id"`
	SocietyID  *int64      `db:"society_id" json:"society_id"`
}

func (q *Queries) UpdateFlat(ctx context.Context, arg UpdateFlatParams) (Flat, error) {
	row := q.db.QueryRow(ctx, updateFlat,
		arg.Block,
		arg.Floor,
		arg.FlatNumber,
		arg.Status,
		arg.IsActive,
		arg.Metadata,
		arg.ID,
		arg.SocietyID,
	)
	var i Flat
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.Block,
		&i.Floor,
		&i.FlatNumber,
		&i.Status,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
