// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider string

const (
	AuthProviderEmail  AuthProvider = "email"
	AuthProviderGoogle AuthProvider = "google"
	AuthProviderApple  AuthProvider = "apple"
	AuthProviderPhone  AuthProvider = "phone"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type BillingCycle string

const (
	BillingCycleMonthly BillingCycle = "monthly"
	BillingCycleYearly  BillingCycle = "yearly"
)

func (e *BillingCycle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingCycle(s)
	case string:
		*e = BillingCycle(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingCycle: %T", src)
	}
	return nil
}

type NullBillingCycle struct {
	BillingCycle BillingCycle `json:"billing_cycle"`
	Valid        bool         `json:"valid"` // Valid is true if BillingCycle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingCycle) Scan(value interface{}) error {
	if value == nil {
		ns.BillingCycle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingCycle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingCycle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingCycle), nil
}

type FlatClaimStatus string

const (
	FlatClaimStatusPending   FlatClaimStatus = "pending"
	FlatClaimStatusApproved  FlatClaimStatus = "approved"
	FlatClaimStatusRejected  FlatClaimStatus = "rejected"
	FlatClaimStatusCancelled FlatClaimStatus = "cancelled"
)

func (e *FlatClaimStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlatClaimStatus(s)
	case string:
		*e = FlatClaimStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FlatClaimStatus: %T", src)
	}
	return nil
}

type NullFlatClaimStatus struct {
	FlatClaimStatus FlatClaimStatus `json:"flat_claim_status"`
	Valid           bool            `json:"valid"` // Valid is true if FlatClaimStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlatClaimStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FlatClaimStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlatClaimStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlatClaimStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlatClaimStatus), nil
}

type FlatResidentRole string

const (
	FlatResidentRoleOwner  FlatResidentRole = "owner"
	FlatResidentRoleTenant FlatResidentRole = "tenant"
	FlatResidentRoleFamily FlatResidentRole = "family"
)

func (e *FlatResidentRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlatResidentRole(s)
	case string:
		*e = FlatResidentRole(s)
	default:
		return fmt.Errorf("unsupported scan type for FlatResidentRole: %T", src)
	}
	return nil
}

type NullFlatResidentRole struct {
	FlatResidentRole FlatResidentRole `json:"flat_resident_role"`
	Valid            bool             `json:"valid"` // Valid is true if FlatResidentRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlatResidentRole) Scan(value interface{}) error {
	if value == nil {
		ns.FlatResidentRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlatResidentRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlatResidentRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlatResidentRole), nil
}

type FlatResidentStatus string

const (
	FlatResidentStatusActive   FlatResidentStatus = "active"
	FlatResidentStatusInactive FlatResidentStatus = "inactive"
	FlatResidentStatusMovedOut FlatResidentStatus = "moved_out"
)

func (e *FlatResidentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlatResidentStatus(s)
	case string:
		*e = FlatResidentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FlatResidentStatus: %T", src)
	}
	return nil
}

type NullFlatResidentStatus struct {
	FlatResidentStatus FlatResidentStatus `json:"flat_resident_status"`
	Valid              bool               `json:"valid"` // Valid is true if FlatResidentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlatResidentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FlatResidentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlatResidentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlatResidentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlatResidentStatus), nil
}

type FlatStatus string

const (
	FlatStatusVacant   FlatStatus = "vacant"
	FlatStatusOccupied FlatStatus = "occupied"
	FlatStatusBlocked  FlatStatus = "blocked"
)

func (e *FlatStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlatStatus(s)
	case string:
		*e = FlatStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FlatStatus: %T", src)
	}
	return nil
}

type NullFlatStatus struct {
	FlatStatus FlatStatus `json:"flat_status"`
	Valid      bool       `json:"valid"` // Valid is true if FlatStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlatStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FlatStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlatStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlatStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlatStatus), nil
}

type GlobalRole string

const (
	GlobalRoleUser       GlobalRole = "user"
	GlobalRoleDeveloper  GlobalRole = "developer"
	GlobalRoleSuperAdmin GlobalRole = "super_admin"
)

func (e *GlobalRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GlobalRole(s)
	case string:
		*e = GlobalRole(s)
	default:
		return fmt.Errorf("unsupported scan type for GlobalRole: %T", src)
	}
	return nil
}

type NullGlobalRole struct {
	GlobalRole GlobalRole `json:"global_role"`
	Valid      bool       `json:"valid"` // Valid is true if GlobalRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGlobalRole) Scan(value interface{}) error {
	if value == nil {
		ns.GlobalRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GlobalRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGlobalRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GlobalRole), nil
}

type SocietyMemberRole string

const (
	SocietyMemberRoleOwner    SocietyMemberRole = "owner"
	SocietyMemberRoleAdmin    SocietyMemberRole = "admin"
	SocietyMemberRoleStaff    SocietyMemberRole = "staff"
	SocietyMemberRoleResident SocietyMemberRole = "resident"
)

func (e *SocietyMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SocietyMemberRole(s)
	case string:
		*e = SocietyMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for SocietyMemberRole: %T", src)
	}
	return nil
}

type NullSocietyMemberRole struct {
	SocietyMemberRole SocietyMemberRole `json:"society_member_role"`
	Valid             bool              `json:"valid"` // Valid is true if SocietyMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSocietyMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.SocietyMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SocietyMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSocietyMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SocietyMemberRole), nil
}

type SocietyMemberStatus string

const (
	SocietyMemberStatusPending   SocietyMemberStatus = "pending"
	SocietyMemberStatusActive    SocietyMemberStatus = "active"
	SocietyMemberStatusSuspended SocietyMemberStatus = "suspended"
	SocietyMemberStatusRemoved   SocietyMemberStatus = "removed"
)

func (e *SocietyMemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SocietyMemberStatus(s)
	case string:
		*e = SocietyMemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SocietyMemberStatus: %T", src)
	}
	return nil
}

type NullSocietyMemberStatus struct {
	SocietyMemberStatus SocietyMemberStatus `json:"society_member_status"`
	Valid               bool                `json:"valid"` // Valid is true if SocietyMemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSocietyMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SocietyMemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SocietyMemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSocietyMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SocietyMemberStatus), nil
}

type SocietyStatus string

const (
	SocietyStatusPending   SocietyStatus = "pending"
	SocietyStatusActive    SocietyStatus = "active"
	SocietyStatusSuspended SocietyStatus = "suspended"
	SocietyStatusRejected  SocietyStatus = "rejected"
)

func (e *SocietyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SocietyStatus(s)
	case string:
		*e = SocietyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SocietyStatus: %T", src)
	}
	return nil
}

type NullSocietyStatus struct {
	SocietyStatus SocietyStatus `json:"society_status"`
	Valid         bool          `json:"valid"` // Valid is true if SocietyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSocietyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SocietyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SocietyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSocietyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SocietyStatus), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusPending   SubscriptionStatus = "pending"
	SubscriptionStatusTrial     SubscriptionStatus = "trial"
	SubscriptionStatusActive    SubscriptionStatus = "active"
	SubscriptionStatusExpired   SubscriptionStatus = "expired"
	SubscriptionStatusCancelled SubscriptionStatus = "cancelled"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type VerificationPurpose string

const (
	VerificationPurposeEmailVerification VerificationPurpose = "email_verification"
	VerificationPurposePhoneVerification VerificationPurpose = "phone_verification"
	VerificationPurposePasswordReset     VerificationPurpose = "password_reset"
	VerificationPurposeLoginOtp          VerificationPurpose = "login_otp"
)

func (e *VerificationPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationPurpose(s)
	case string:
		*e = VerificationPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationPurpose: %T", src)
	}
	return nil
}

type NullVerificationPurpose struct {
	VerificationPurpose VerificationPurpose `json:"verification_purpose"`
	Valid               bool                `json:"valid"` // Valid is true if VerificationPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationPurpose), nil
}

type Flat struct {
	ID         int64              `db:"id" json:"id"`
	SocietyID  int64              `db:"society_id" json:"society_id"`
	Block      *string            `db:"block" json:"block"`
	Floor      *string            `db:"floor" json:"floor"`
	FlatNumber string             `db:"flat_number" json:"flat_number"`
	Status     FlatStatus         `db:"status" json:"status"`
	IsActive   bool               `db:"is_active" json:"is_active"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	CreatedBy  *int64             `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type FlatClaimRequest struct {
	ID               int64              `db:"id" json:"id"`
	SocietyID        int64              `db:"society_id" json:"society_id"`
	FlatID           int64              `db:"flat_id" json:"flat_id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	RequestedRole    FlatResidentRole   `db:"requested_role" json:"requested_role"`
	RequestedPrimary bool               `db:"requested_primary" json:"requested_primary"`
	Status           FlatClaimStatus    `db:"status" json:"status"`
	Note             *string            `db:"note" json:"note"`
	RejectionReason  *string            `db:"rejection_reason" json:"rejection_reason"`
	ReviewedBy       *int64             `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	CancelledAt      pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	Metadata         []byte             `db:"metadata" json:"metadata"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type FlatResident struct {
	ID         int64              `db:"id" json:"id"`
	SocietyID  int64              `db:"society_id" json:"society_id"`
	FlatID     int64              `db:"flat_id" json:"flat_id"`
	UserID     int64              `db:"user_id" json:"user_id"`
	Role       FlatResidentRole   `db:"role" json:"role"`
	Status     FlatResidentStatus `db:"status" json:"status"`
	IsPrimary  bool               `db:"is_primary" json:"is_primary"`
	MovedInAt  pgtype.Timestamptz `db:"moved_in_at" json:"moved_in_at"`
	MovedOutAt pgtype.Timestamptz `db:"moved_out_at" json:"moved_out_at"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	CreatedBy  *int64             `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Plan struct {
	ID               int64              `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	Code             string             `db:"code" json:"code"`
	Description      *string            `db:"description" json:"description"`
	PriceAmountPaise int64              `db:"price_amount_paise" json:"price_amount_paise"`
	Currency         string             `db:"currency" json:"currency"`
	BillingCycle     BillingCycle       `db:"billing_cycle" json:"billing_cycle"`
	MaxFlats         int32              `db:"max_flats" json:"max_flats"`
	MaxAdmins        int32              `db:"max_admins" json:"max_admins"`
	MaxStaff         int32              `db:"max_staff" json:"max_staff"`
	MaxResidents     int32              `db:"max_residents" json:"max_residents"`
	Features         []byte             `db:"features" json:"features"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Society struct {
	ID               int64              `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	SocietyCode      string             `db:"society_code" json:"society_code"`
	Email            *string            `db:"email" json:"email"`
	PhoneNumber      *string            `db:"phone_number" json:"phone_number"`
	AddressLine1     *string            `db:"address_line1" json:"address_line1"`
	AddressLine2     *string            `db:"address_line2" json:"address_line2"`
	Landmark         *string            `db:"landmark" json:"landmark"`
	City             *string            `db:"city" json:"city"`
	State            *string            `db:"state" json:"state"`
	Pincode          *string            `db:"pincode" json:"pincode"`
	Country          string             `db:"country" json:"country"`
	TotalFlats       int32              `db:"total_flats" json:"total_flats"`
	TotalBlocks      int32              `db:"total_blocks" json:"total_blocks"`
	Status           SocietyStatus      `db:"status" json:"status"`
	CreatedBy        int64              `db:"created_by" json:"created_by"`
	ApprovedBy       *int64             `db:"approved_by" json:"approved_by"`
	ApprovedAt       pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	RejectedBy       *int64             `db:"rejected_by" json:"rejected_by"`
	RejectedAt       pgtype.Timestamptz `db:"rejected_at" json:"rejected_at"`
	RejectionReason  *string            `db:"rejection_reason" json:"rejection_reason"`
	SuspendedBy      *int64             `db:"suspended_by" json:"suspended_by"`
	SuspendedAt      pgtype.Timestamptz `db:"suspended_at" json:"suspended_at"`
	SuspensionReason *string            `db:"suspension_reason" json:"suspension_reason"`
	Metadata         []byte             `db:"metadata" json:"metadata"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type SocietyMember struct {
	ID           int64               `db:"id" json:"id"`
	SocietyID    int64               `db:"society_id" json:"society_id"`
	UserID       int64               `db:"user_id" json:"user_id"`
	Role         SocietyMemberRole   `db:"role" json:"role"`
	Status       SocietyMemberStatus `db:"status" json:"status"`
	InvitedBy    *int64              `db:"invited_by" json:"invited_by"`
	JoinedAt     pgtype.Timestamptz  `db:"joined_at" json:"joined_at"`
	RemovedBy    *int64              `db:"removed_by" json:"removed_by"`
	RemovedAt    pgtype.Timestamptz  `db:"removed_at" json:"removed_at"`
	RemoveReason *string             `db:"remove_reason" json:"remove_reason"`
	Metadata     []byte              `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type SocietySubscription struct {
	ID                 int64              `db:"id" json:"id"`
	SocietyID          int64              `db:"society_id" json:"society_id"`
	PlanID             *int64             `db:"plan_id" json:"plan_id"`
	Status             SubscriptionStatus `db:"status" json:"status"`
	StartsAt           pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt             pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	TrialEndsAt        pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	PlanName           string             `db:"plan_name" json:"plan_name"`
	PlanCode           string             `db:"plan_code" json:"plan_code"`
	PriceAmountPaise   int64              `db:"price_amount_paise" json:"price_amount_paise"`
	Currency           string             `db:"currency" json:"currency"`
	BillingCycle       BillingCycle       `db:"billing_cycle" json:"billing_cycle"`
	MaxFlats           int32              `db:"max_flats" json:"max_flats"`
	MaxAdmins          int32              `db:"max_admins" json:"max_admins"`
	MaxStaff           int32              `db:"max_staff" json:"max_staff"`
	MaxResidents       int32              `db:"max_residents" json:"max_residents"`
	Features           []byte             `db:"features" json:"features"`
	ActivatedAt        pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	ActivatedBy        *int64             `db:"activated_by" json:"activated_by"`
	ExpiredAt          pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	CancelledAt        pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CancelledBy        *int64             `db:"cancelled_by" json:"cancelled_by"`
	CancellationReason *string            `db:"cancellation_reason" json:"cancellation_reason"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedBy          *int64             `db:"created_by" json:"created_by"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID                int64              `db:"id" json:"id"`
	FirstName         *string            `db:"first_name" json:"first_name"`
	LastName          *string            `db:"last_name" json:"last_name"`
	FullName          string             `db:"full_name" json:"full_name"`
	Email             *string            `db:"email" json:"email"`
	PhoneNumber       *string            `db:"phone_number" json:"phone_number"`
	PasswordHash      *string            `db:"password_hash" json:"password_hash"`
	AuthProvider      AuthProvider       `db:"auth_provider" json:"auth_provider"`
	ProviderID        *string            `db:"provider_id" json:"provider_id"`
	GlobalRole        GlobalRole         `db:"global_role" json:"global_role"`
	EmailVerified     bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified     bool               `db:"phone_verified" json:"phone_verified"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	IsBlocked         bool               `db:"is_blocked" json:"is_blocked"`
	BlockedReason     *string            `db:"blocked_reason" json:"blocked_reason"`
	AvatarUrl         *string            `db:"avatar_url" json:"avatar_url"`
	DateOfBirth       pgtype.Date        `db:"date_of_birth" json:"date_of_birth"`
	Gender            *string            `db:"gender" json:"gender"`
	Timezone          string             `db:"timezone" json:"timezone"`
	Language          string             `db:"language" json:"language"`
	LastLoginAt       pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserVerification struct {
	ID          int64               `db:"id" json:"id"`
	UserID      int64               `db:"user_id" json:"user_id"`
	Purpose     VerificationPurpose `db:"purpose" json:"purpose"`
	Target      string              `db:"target" json:"target"`
	OtpHash     string              `db:"otp_hash" json:"otp_hash"`
	Attempts    int32               `db:"attempts" json:"attempts"`
	MaxAttempts int32               `db:"max_attempts" json:"max_attempts"`
	IsUsed      bool                `db:"is_used" json:"is_used"`
	ExpiresAt   pgtype.Timestamptz  `db:"expires_at" json:"expires_at"`
	UsedAt      pgtype.Timestamptz  `db:"used_at" json:"used_at"`
	CreatedAt   pgtype.Timestamptz  `db:"created_at" json:"created_at"`
}
