// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider string

const (
	AuthProviderEmail  AuthProvider = "email"
	AuthProviderGoogle AuthProvider = "google"
	AuthProviderApple  AuthProvider = "apple"
	AuthProviderPhone  AuthProvider = "phone"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type BillingCycle string

const (
	BillingCycleMonthly BillingCycle = "monthly"
	BillingCycleYearly  BillingCycle = "yearly"
)

func (e *BillingCycle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingCycle(s)
	case string:
		*e = BillingCycle(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingCycle: %T", src)
	}
	return nil
}

type NullBillingCycle struct {
	BillingCycle BillingCycle `json:"billing_cycle"`
	Valid        bool         `json:"valid"` // Valid is true if BillingCycle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingCycle) Scan(value interface{}) error {
	if value == nil {
		ns.BillingCycle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingCycle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingCycle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingCycle), nil
}

type FlatClaimStatus string

const (
	FlatClaimStatusPending   FlatClaimStatus = "pending"
	FlatClaimStatusApproved  FlatClaimStatus = "approved"
	FlatClaimStatusRejected  FlatClaimStatus = "rejected"
	FlatClaimStatusCancelled FlatClaimStatus = "cancelled"
)

func (e *FlatClaimStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlatClaimStatus(s)
	case string:
		*e = FlatClaimStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FlatClaimStatus: %T", src)
	}
	return nil
}

type NullFlatClaimStatus struct {
	FlatClaimStatus FlatClaimStatus `json:"flat_claim_status"`
	Valid           bool            `json:"valid"` // Valid is true if FlatClaimStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlatClaimStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FlatClaimStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlatClaimStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlatClaimStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlatClaimStatus), nil
}

type FlatResidentRole string

const (
	FlatResidentRoleOwner  FlatResidentRole = "owner"
	FlatResidentRoleTenant FlatResidentRole = "tenant"
	FlatResidentRoleFamily FlatResidentRole = "family"
)

func (e *FlatResidentRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlatResidentRole(s)
	case string:
		*e = FlatResidentRole(s)
	default:
		return fmt.Errorf("unsupported scan type for FlatResidentRole: %T", src)
	}
	return nil
}

type NullFlatResidentRole struct {
	FlatResidentRole FlatResidentRole `json:"flat_resident_role"`
	Valid            bool             `json:"valid"` // Valid is true if FlatResidentRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlatResidentRole) Scan(value interface{}) error {
	if value == nil {
		ns.FlatResidentRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlatResidentRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlatResidentRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlatResidentRole), nil
}

type FlatResidentStatus string

const (
	FlatResidentStatusActive   FlatResidentStatus = "active"
	FlatResidentStatusInactive FlatResidentStatus = "inactive"
	FlatResidentStatusMovedOut FlatResidentStatus = "moved_out"
)

func (e *FlatResidentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlatResidentStatus(s)
	case string:
		*e = FlatResidentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FlatResidentStatus: %T", src)
	}
	return nil
}

type NullFlatResidentStatus struct {
	FlatResidentStatus FlatResidentStatus `json:"flat_resident_status"`
	Valid              bool               `json:"valid"` // Valid is true if FlatResidentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlatResidentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FlatResidentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlatResidentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlatResidentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlatResidentStatus), nil
}

type FlatStatus string

const (
	FlatStatusVacant   FlatStatus = "vacant"
	FlatStatusOccupied FlatStatus = "occupied"
	FlatStatusBlocked  FlatStatus = "blocked"
)

func (e *FlatStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlatStatus(s)
	case string:
		*e = FlatStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FlatStatus: %T", src)
	}
	return nil
}

type NullFlatStatus struct {
	FlatStatus FlatStatus `json:"flat_status"`
	Valid      bool       `json:"valid"` // Valid is true if FlatStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlatStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FlatStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlatStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlatStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlatStatus), nil
}

type GlobalRole string

const (
	GlobalRoleUser       GlobalRole = "user"
	GlobalRoleDeveloper  GlobalRole = "developer"
	GlobalRoleSuperAdmin GlobalRole = "super_admin"
)

func (e *GlobalRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GlobalRole(s)
	case string:
		*e = GlobalRole(s)
	default:
		return fmt.Errorf("unsupported scan type for GlobalRole: %T", src)
	}
	return nil
}

type NullGlobalRole struct {
	GlobalRole GlobalRole `json:"global_role"`
	Valid      bool       `json:"valid"` // Valid is true if GlobalRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGlobalRole) Scan(value interface{}) error {
	if value == nil {
		ns.GlobalRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GlobalRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGlobalRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GlobalRole), nil
}

type SocietyMemberRole string

const (
	SocietyMemberRoleOwner    SocietyMemberRole = "owner"
	SocietyMemberRoleAdmin    SocietyMemberRole = "admin"
	SocietyMemberRoleStaff    SocietyMemberRole = "staff"
	SocietyMemberRoleResident SocietyMemberRole = "resident"
)

func (e *SocietyMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SocietyMemberRole(s)
	case string:
		*e = SocietyMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for SocietyMemberRole: %T", src)
	}
	return nil
}

type NullSocietyMemberRole struct {
	SocietyMemberRole SocietyMemberRole `json:"society_member_role"`
	Valid             bool              `json:"valid"` // Valid is true if SocietyMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSocietyMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.SocietyMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SocietyMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSocietyMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SocietyMemberRole), nil
}

type SocietyMemberStatus string

const (
	SocietyMemberStatusPending   SocietyMemberStatus = "pending"
	SocietyMemberStatusActive    SocietyMemberStatus = "active"
	SocietyMemberStatusSuspended SocietyMemberStatus = "suspended"
	SocietyMemberStatusRemoved   SocietyMemberStatus = "removed"
)

func (e *SocietyMemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SocietyMemberStatus(s)
	case string:
		*e = SocietyMemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SocietyMemberStatus: %T", src)
	}
	return nil
}

type NullSocietyMemberStatus struct {
	SocietyMemberStatus SocietyMemberStatus `json:"society_member_status"`
	Valid               bool                `json:"valid"` // Valid is true if SocietyMemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSocietyMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SocietyMemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SocietyMemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSocietyMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SocietyMemberStatus), nil
}

type SocietyStatus string

const (
	SocietyStatusPending   SocietyStatus = "pending"
	SocietyStatusActive    SocietyStatus = "active"
	SocietyStatusSuspended SocietyStatus = "suspended"
	SocietyStatusRejected  SocietyStatus = "rejected"
)

func (e *SocietyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SocietyStatus(s)
	case string:
		*e = SocietyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SocietyStatus: %T", src)
	}
	return nil
}

type NullSocietyStatus struct {
	SocietyStatus SocietyStatus `json:"society_status"`
	Valid         bool          `json:"valid"` // Valid is true if SocietyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSocietyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SocietyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SocietyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSocietyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SocietyStatus), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusPending   SubscriptionStatus = "pending"
	SubscriptionStatusTrial     SubscriptionStatus = "trial"
	SubscriptionStatusActive    SubscriptionStatus = "active"
	SubscriptionStatusExpired   SubscriptionStatus = "expired"
	SubscriptionStatusCancelled SubscriptionStatus = "cancelled"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type VerificationPurpose string

const (
	VerificationPurposeEmailVerification VerificationPurpose = "email_verification"
	VerificationPurposePhoneVerification VerificationPurpose = "phone_verification"
	VerificationPurposePasswordReset     VerificationPurpose = "password_reset"
	VerificationPurposeLoginOtp          VerificationPurpose = "login_otp"
)

func (e *VerificationPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationPurpose(s)
	case string:
		*e = VerificationPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationPurpose: %T", src)
	}
	return nil
}

type NullVerificationPurpose struct {
	VerificationPurpose VerificationPurpose `json:"verification_purpose"`
	Valid               bool                `json:"valid"` // Valid is true if VerificationPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationPurpose), nil
}

type VisitorApprovalMode string

const (
	VisitorApprovalModeMandatory VisitorApprovalMode = "mandatory"
	VisitorApprovalModeOptional  VisitorApprovalMode = "optional"
	VisitorApprovalModeHybrid    VisitorApprovalMode = "hybrid"
)

func (e *VisitorApprovalMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisitorApprovalMode(s)
	case string:
		*e = VisitorApprovalMode(s)
	default:
		return fmt.Errorf("unsupported scan type for VisitorApprovalMode: %T", src)
	}
	return nil
}

type NullVisitorApprovalMode struct {
	VisitorApprovalMode VisitorApprovalMode `json:"visitor_approval_mode"`
	Valid               bool                `json:"valid"` // Valid is true if VisitorApprovalMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisitorApprovalMode) Scan(value interface{}) error {
	if value == nil {
		ns.VisitorApprovalMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisitorApprovalMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisitorApprovalMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisitorApprovalMode), nil
}

type VisitorEventType string

const (
	VisitorEventTypeCreated     VisitorEventType = "created"
	VisitorEventTypeApproved    VisitorEventType = "approved"
	VisitorEventTypeRejected    VisitorEventType = "rejected"
	VisitorEventTypeCheckedIn   VisitorEventType = "checked_in"
	VisitorEventTypeCheckedOut  VisitorEventType = "checked_out"
	VisitorEventTypeCancelled   VisitorEventType = "cancelled"
	VisitorEventTypeExpired     VisitorEventType = "expired"
	VisitorEventTypeAutoClosed  VisitorEventType = "auto_closed"
	VisitorEventTypeQrGenerated VisitorEventType = "qr_generated"
	VisitorEventTypeQrUsed      VisitorEventType = "qr_used"
)

func (e *VisitorEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisitorEventType(s)
	case string:
		*e = VisitorEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for VisitorEventType: %T", src)
	}
	return nil
}

type NullVisitorEventType struct {
	VisitorEventType VisitorEventType `json:"visitor_event_type"`
	Valid            bool             `json:"valid"` // Valid is true if VisitorEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisitorEventType) Scan(value interface{}) error {
	if value == nil {
		ns.VisitorEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisitorEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisitorEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisitorEventType), nil
}

type VisitorInviteStatus string

const (
	VisitorInviteStatusActive    VisitorInviteStatus = "active"
	VisitorInviteStatusUsed      VisitorInviteStatus = "used"
	VisitorInviteStatusExpired   VisitorInviteStatus = "expired"
	VisitorInviteStatusCancelled VisitorInviteStatus = "cancelled"
)

func (e *VisitorInviteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisitorInviteStatus(s)
	case string:
		*e = VisitorInviteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VisitorInviteStatus: %T", src)
	}
	return nil
}

type NullVisitorInviteStatus struct {
	VisitorInviteStatus VisitorInviteStatus `json:"visitor_invite_status"`
	Valid               bool                `json:"valid"` // Valid is true if VisitorInviteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisitorInviteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VisitorInviteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisitorInviteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisitorInviteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisitorInviteStatus), nil
}

type VisitorPurpose string

const (
	VisitorPurposeGuest       VisitorPurpose = "guest"
	VisitorPurposeDelivery    VisitorPurpose = "delivery"
	VisitorPurposeCab         VisitorPurpose = "cab"
	VisitorPurposeService     VisitorPurpose = "service"
	VisitorPurposeMaintenance VisitorPurpose = "maintenance"
	VisitorPurposeStaff       VisitorPurpose = "staff"
	VisitorPurposeOther       VisitorPurpose = "other"
)

func (e *VisitorPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisitorPurpose(s)
	case string:
		*e = VisitorPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for VisitorPurpose: %T", src)
	}
	return nil
}

type NullVisitorPurpose struct {
	VisitorPurpose VisitorPurpose `json:"visitor_purpose"`
	Valid          bool           `json:"valid"` // Valid is true if VisitorPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisitorPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.VisitorPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisitorPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisitorPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisitorPurpose), nil
}

type VisitorSource string

const (
	VisitorSourceResidentLink VisitorSource = "resident_link"
	VisitorSourcePublicQr     VisitorSource = "public_qr"
	VisitorSourceGuardEntry   VisitorSource = "guard_entry"
	VisitorSourceQuickLink    VisitorSource = "quick_link"
)

func (e *VisitorSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisitorSource(s)
	case string:
		*e = VisitorSource(s)
	default:
		return fmt.Errorf("unsupported scan type for VisitorSource: %T", src)
	}
	return nil
}

type NullVisitorSource struct {
	VisitorSource VisitorSource `json:"visitor_source"`
	Valid         bool          `json:"valid"` // Valid is true if VisitorSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisitorSource) Scan(value interface{}) error {
	if value == nil {
		ns.VisitorSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisitorSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisitorSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisitorSource), nil
}

type VisitorStatus string

const (
	VisitorStatusWaitingApproval VisitorStatus = "waiting_approval"
	VisitorStatusApproved        VisitorStatus = "approved"
	VisitorStatusRejected        VisitorStatus = "rejected"
	VisitorStatusCheckedIn       VisitorStatus = "checked_in"
	VisitorStatusCheckedOut      VisitorStatus = "checked_out"
	VisitorStatusCancelled       VisitorStatus = "cancelled"
	VisitorStatusExpired         VisitorStatus = "expired"
	VisitorStatusAutoClosed      VisitorStatus = "auto_closed"
)

func (e *VisitorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisitorStatus(s)
	case string:
		*e = VisitorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VisitorStatus: %T", src)
	}
	return nil
}

type NullVisitorStatus struct {
	VisitorStatus VisitorStatus `json:"visitor_status"`
	Valid         bool          `json:"valid"` // Valid is true if VisitorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisitorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VisitorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisitorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisitorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisitorStatus), nil
}

type VisitorVehicleType string

const (
	VisitorVehicleTypeBike  VisitorVehicleType = "bike"
	VisitorVehicleTypeCar   VisitorVehicleType = "car"
	VisitorVehicleTypeAuto  VisitorVehicleType = "auto"
	VisitorVehicleTypeCab   VisitorVehicleType = "cab"
	VisitorVehicleTypeTruck VisitorVehicleType = "truck"
	VisitorVehicleTypeOther VisitorVehicleType = "other"
)

func (e *VisitorVehicleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisitorVehicleType(s)
	case string:
		*e = VisitorVehicleType(s)
	default:
		return fmt.Errorf("unsupported scan type for VisitorVehicleType: %T", src)
	}
	return nil
}

type NullVisitorVehicleType struct {
	VisitorVehicleType VisitorVehicleType `json:"visitor_vehicle_type"`
	Valid              bool               `json:"valid"` // Valid is true if VisitorVehicleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisitorVehicleType) Scan(value interface{}) error {
	if value == nil {
		ns.VisitorVehicleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisitorVehicleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisitorVehicleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisitorVehicleType), nil
}

type Flat struct {
	ID         int64              `db:"id" json:"id"`
	SocietyID  int64              `db:"society_id" json:"society_id"`
	Block      *string            `db:"block" json:"block"`
	Floor      *string            `db:"floor" json:"floor"`
	FlatNumber string             `db:"flat_number" json:"flat_number"`
	Status     FlatStatus         `db:"status" json:"status"`
	IsActive   bool               `db:"is_active" json:"is_active"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	CreatedBy  *int64             `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type FlatClaimRequest struct {
	ID               int64              `db:"id" json:"id"`
	SocietyID        int64              `db:"society_id" json:"society_id"`
	FlatID           int64              `db:"flat_id" json:"flat_id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	RequestedRole    FlatResidentRole   `db:"requested_role" json:"requested_role"`
	RequestedPrimary bool               `db:"requested_primary" json:"requested_primary"`
	Status           FlatClaimStatus    `db:"status" json:"status"`
	Note             *string            `db:"note" json:"note"`
	RejectionReason  *string            `db:"rejection_reason" json:"rejection_reason"`
	ReviewedBy       *int64             `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	CancelledAt      pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	Metadata         []byte             `db:"metadata" json:"metadata"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type FlatResident struct {
	ID         int64              `db:"id" json:"id"`
	SocietyID  int64              `db:"society_id" json:"society_id"`
	FlatID     int64              `db:"flat_id" json:"flat_id"`
	UserID     int64              `db:"user_id" json:"user_id"`
	Role       FlatResidentRole   `db:"role" json:"role"`
	Status     FlatResidentStatus `db:"status" json:"status"`
	IsPrimary  bool               `db:"is_primary" json:"is_primary"`
	MovedInAt  pgtype.Timestamptz `db:"moved_in_at" json:"moved_in_at"`
	MovedOutAt pgtype.Timestamptz `db:"moved_out_at" json:"moved_out_at"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	CreatedBy  *int64             `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type FlatVisitorSetting struct {
	ID                          int64              `db:"id" json:"id"`
	SocietyID                   int64              `db:"society_id" json:"society_id"`
	FlatID                      int64              `db:"flat_id" json:"flat_id"`
	Purpose                     VisitorPurpose     `db:"purpose" json:"purpose"`
	ApprovalRequired            bool               `db:"approval_required" json:"approval_required"`
	DefaultVisitDurationMinutes *int32             `db:"default_visit_duration_minutes" json:"default_visit_duration_minutes"`
	IsEnabled                   bool               `db:"is_enabled" json:"is_enabled"`
	Metadata                    []byte             `db:"metadata" json:"metadata"`
	UpdatedBy                   *int64             `db:"updated_by" json:"updated_by"`
	CreatedAt                   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Plan struct {
	ID               int64              `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	Code             string             `db:"code" json:"code"`
	Description      *string            `db:"description" json:"description"`
	PriceAmountPaise int64              `db:"price_amount_paise" json:"price_amount_paise"`
	Currency         string             `db:"currency" json:"currency"`
	BillingCycle     BillingCycle       `db:"billing_cycle" json:"billing_cycle"`
	MaxFlats         int32              `db:"max_flats" json:"max_flats"`
	MaxAdmins        int32              `db:"max_admins" json:"max_admins"`
	MaxStaff         int32              `db:"max_staff" json:"max_staff"`
	MaxResidents     int32              `db:"max_residents" json:"max_residents"`
	Features         []byte             `db:"features" json:"features"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Society struct {
	ID               int64              `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	SocietyCode      string             `db:"society_code" json:"society_code"`
	Email            *string            `db:"email" json:"email"`
	PhoneNumber      *string            `db:"phone_number" json:"phone_number"`
	AddressLine1     *string            `db:"address_line1" json:"address_line1"`
	AddressLine2     *string            `db:"address_line2" json:"address_line2"`
	Landmark         *string            `db:"landmark" json:"landmark"`
	City             *string            `db:"city" json:"city"`
	State            *string            `db:"state" json:"state"`
	Pincode          *string            `db:"pincode" json:"pincode"`
	Country          string             `db:"country" json:"country"`
	TotalFlats       int32              `db:"total_flats" json:"total_flats"`
	TotalBlocks      int32              `db:"total_blocks" json:"total_blocks"`
	Status           SocietyStatus      `db:"status" json:"status"`
	CreatedBy        int64              `db:"created_by" json:"created_by"`
	ApprovedBy       *int64             `db:"approved_by" json:"approved_by"`
	ApprovedAt       pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	RejectedBy       *int64             `db:"rejected_by" json:"rejected_by"`
	RejectedAt       pgtype.Timestamptz `db:"rejected_at" json:"rejected_at"`
	RejectionReason  *string            `db:"rejection_reason" json:"rejection_reason"`
	SuspendedBy      *int64             `db:"suspended_by" json:"suspended_by"`
	SuspendedAt      pgtype.Timestamptz `db:"suspended_at" json:"suspended_at"`
	SuspensionReason *string            `db:"suspension_reason" json:"suspension_reason"`
	Metadata         []byte             `db:"metadata" json:"metadata"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type SocietyMember struct {
	ID           int64               `db:"id" json:"id"`
	SocietyID    int64               `db:"society_id" json:"society_id"`
	UserID       int64               `db:"user_id" json:"user_id"`
	Role         SocietyMemberRole   `db:"role" json:"role"`
	Status       SocietyMemberStatus `db:"status" json:"status"`
	InvitedBy    *int64              `db:"invited_by" json:"invited_by"`
	JoinedAt     pgtype.Timestamptz  `db:"joined_at" json:"joined_at"`
	RemovedBy    *int64              `db:"removed_by" json:"removed_by"`
	RemovedAt    pgtype.Timestamptz  `db:"removed_at" json:"removed_at"`
	RemoveReason *string             `db:"remove_reason" json:"remove_reason"`
	Metadata     []byte              `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type SocietySubscription struct {
	ID                 int64              `db:"id" json:"id"`
	SocietyID          int64              `db:"society_id" json:"society_id"`
	PlanID             *int64             `db:"plan_id" json:"plan_id"`
	Status             SubscriptionStatus `db:"status" json:"status"`
	StartsAt           pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt             pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	TrialEndsAt        pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	PlanName           string             `db:"plan_name" json:"plan_name"`
	PlanCode           string             `db:"plan_code" json:"plan_code"`
	PriceAmountPaise   int64              `db:"price_amount_paise" json:"price_amount_paise"`
	Currency           string             `db:"currency" json:"currency"`
	BillingCycle       BillingCycle       `db:"billing_cycle" json:"billing_cycle"`
	MaxFlats           int32              `db:"max_flats" json:"max_flats"`
	MaxAdmins          int32              `db:"max_admins" json:"max_admins"`
	MaxStaff           int32              `db:"max_staff" json:"max_staff"`
	MaxResidents       int32              `db:"max_residents" json:"max_residents"`
	Features           []byte             `db:"features" json:"features"`
	ActivatedAt        pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	ActivatedBy        *int64             `db:"activated_by" json:"activated_by"`
	ExpiredAt          pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	CancelledAt        pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CancelledBy        *int64             `db:"cancelled_by" json:"cancelled_by"`
	CancellationReason *string            `db:"cancellation_reason" json:"cancellation_reason"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedBy          *int64             `db:"created_by" json:"created_by"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SocietyVisitorSetting struct {
	ID                          int64               `db:"id" json:"id"`
	SocietyID                   int64               `db:"society_id" json:"society_id"`
	ApprovalMode                VisitorApprovalMode `db:"approval_mode" json:"approval_mode"`
	DefaultVisitDurationMinutes int32               `db:"default_visit_duration_minutes" json:"default_visit_duration_minutes"`
	GracePeriodMinutes          int32               `db:"grace_period_minutes" json:"grace_period_minutes"`
	QrExpiryMinutes             int32               `db:"qr_expiry_minutes" json:"qr_expiry_minutes"`
	AllowResidentPreApproval    bool                `db:"allow_resident_pre_approval" json:"allow_resident_pre_approval"`
	AllowPublicQrEntry          bool                `db:"allow_public_qr_entry" json:"allow_public_qr_entry"`
	AllowGuardEntry             bool                `db:"allow_guard_entry" json:"allow_guard_entry"`
	IsActive                    bool                `db:"is_active" json:"is_active"`
	Metadata                    []byte              `db:"metadata" json:"metadata"`
	UpdatedBy                   *int64              `db:"updated_by" json:"updated_by"`
	CreatedAt                   pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID                int64              `db:"id" json:"id"`
	FirstName         *string            `db:"first_name" json:"first_name"`
	LastName          *string            `db:"last_name" json:"last_name"`
	FullName          string             `db:"full_name" json:"full_name"`
	Email             *string            `db:"email" json:"email"`
	PhoneNumber       *string            `db:"phone_number" json:"phone_number"`
	PasswordHash      *string            `db:"password_hash" json:"password_hash"`
	AuthProvider      AuthProvider       `db:"auth_provider" json:"auth_provider"`
	ProviderID        *string            `db:"provider_id" json:"provider_id"`
	GlobalRole        GlobalRole         `db:"global_role" json:"global_role"`
	EmailVerified     bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified     bool               `db:"phone_verified" json:"phone_verified"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	IsBlocked         bool               `db:"is_blocked" json:"is_blocked"`
	BlockedReason     *string            `db:"blocked_reason" json:"blocked_reason"`
	AvatarUrl         *string            `db:"avatar_url" json:"avatar_url"`
	DateOfBirth       pgtype.Date        `db:"date_of_birth" json:"date_of_birth"`
	Gender            *string            `db:"gender" json:"gender"`
	Timezone          string             `db:"timezone" json:"timezone"`
	Language          string             `db:"language" json:"language"`
	LastLoginAt       pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserVerification struct {
	ID          int64               `db:"id" json:"id"`
	UserID      int64               `db:"user_id" json:"user_id"`
	Purpose     VerificationPurpose `db:"purpose" json:"purpose"`
	Target      string              `db:"target" json:"target"`
	OtpHash     string              `db:"otp_hash" json:"otp_hash"`
	Attempts    int32               `db:"attempts" json:"attempts"`
	MaxAttempts int32               `db:"max_attempts" json:"max_attempts"`
	IsUsed      bool                `db:"is_used" json:"is_used"`
	ExpiresAt   pgtype.Timestamptz  `db:"expires_at" json:"expires_at"`
	UsedAt      pgtype.Timestamptz  `db:"used_at" json:"used_at"`
	CreatedAt   pgtype.Timestamptz  `db:"created_at" json:"created_at"`
}

type Visitor struct {
	ID          int64              `db:"id" json:"id"`
	FullName    string             `db:"full_name" json:"full_name"`
	PhoneNumber *string            `db:"phone_number" json:"phone_number"`
	Email       *string            `db:"email" json:"email"`
	PhotoUrl    *string            `db:"photo_url" json:"photo_url"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type VisitorEntry struct {
	ID                 int64               `db:"id" json:"id"`
	SocietyID          int64               `db:"society_id" json:"society_id"`
	FlatID             int64               `db:"flat_id" json:"flat_id"`
	VisitorID          int64               `db:"visitor_id" json:"visitor_id"`
	InviteID           *int64              `db:"invite_id" json:"invite_id"`
	Source             VisitorSource       `db:"source" json:"source"`
	Purpose            VisitorPurpose      `db:"purpose" json:"purpose"`
	Status             VisitorStatus       `db:"status" json:"status"`
	VehicleNumber      *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType        *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionsCount    int32               `db:"companions_count" json:"companions_count"`
	CompanionDetails   []byte              `db:"companion_details" json:"companion_details"`
	ExpectedAt         pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	CheckedInAt        pgtype.Timestamptz  `db:"checked_in_at" json:"checked_in_at"`
	CheckedOutAt       pgtype.Timestamptz  `db:"checked_out_at" json:"checked_out_at"`
	AutoClosedAt       pgtype.Timestamptz  `db:"auto_closed_at" json:"auto_closed_at"`
	ApprovedBy         *int64              `db:"approved_by" json:"approved_by"`
	RejectedBy         *int64              `db:"rejected_by" json:"rejected_by"`
	HandledByGuardID   *int64              `db:"handled_by_guard_id" json:"handled_by_guard_id"`
	CreatedBy          *int64              `db:"created_by" json:"created_by"`
	QrTokenHash        *string             `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt        pgtype.Timestamptz  `db:"qr_expires_at" json:"qr_expires_at"`
	QrUsedAt           pgtype.Timestamptz  `db:"qr_used_at" json:"qr_used_at"`
	Notes              *string             `db:"notes" json:"notes"`
	RejectionReason    *string             `db:"rejection_reason" json:"rejection_reason"`
	Metadata           []byte              `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type VisitorEntryEvent struct {
	ID             int64              `db:"id" json:"id"`
	VisitorEntryID int64              `db:"visitor_entry_id" json:"visitor_entry_id"`
	SocietyID      int64              `db:"society_id" json:"society_id"`
	ActorUserID    *int64             `db:"actor_user_id" json:"actor_user_id"`
	EventType      VisitorEventType   `db:"event_type" json:"event_type"`
	Message        *string            `db:"message" json:"message"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type VisitorInvite struct {
	ID        int64               `db:"id" json:"id"`
	SocietyID int64               `db:"society_id" json:"society_id"`
	FlatID    int64               `db:"flat_id" json:"flat_id"`
	CreatedBy int64               `db:"created_by" json:"created_by"`
	Purpose   VisitorPurpose      `db:"purpose" json:"purpose"`
	TokenHash string              `db:"token_hash" json:"token_hash"`
	Status    VisitorInviteStatus `db:"status" json:"status"`
	ExpiresAt pgtype.Timestamptz  `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz  `db:"used_at" json:"used_at"`
	Metadata  []byte              `db:"metadata" json:"metadata"`
	CreatedAt pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}
