// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"
)

const activatePlan = `-- name: ActivatePlan :one
UPDATE plans
SET is_active = TRUE, updated_at = NOW()
WHERE id = $1
RETURNING id, name, code, description, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, is_active, created_at, updated_at
`

func (q *Queries) ActivatePlan(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRow(ctx, activatePlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPlans = `-- name: CountPlans :one
SELECT COUNT(*)
FROM plans
WHERE ($1::bigint IS NULL OR id = $1::bigint)
  AND ($2::text IS NULL OR code = $2::text)
  AND ($3::text IS NULL OR name = $3::text)
  AND ($4::billing_cycle IS NULL OR billing_cycle = $4::billing_cycle)
  AND ($5::bool IS NULL OR is_active = $5::bool)
  AND ($6::bigint IS NULL OR price_amount_paise >= $6::bigint)
  AND ($7::bigint IS NULL OR price_amount_paise <= $7::bigint)
  AND (
      COALESCE($8::text, '') = ''
      OR name ILIKE '%' || $8::text || '%'
      OR code ILIKE '%' || $8::text || '%'
      OR COALESCE(description, '') ILIKE '%' || $8::text || '%'
  )
`

type CountPlansParams struct {
	ID            *int64        `db:"id" json:"id"`
	Code          *string       `db:"code" json:"code"`
	Name          *string       `db:"name" json:"name"`
	BillingCycle  *BillingCycle `db:"billing_cycle" json:"billing_cycle"`
	IsActive      *bool         `db:"is_active" json:"is_active"`
	MinPricePaise *int64        `db:"min_price_paise" json:"min_price_paise"`
	MaxPricePaise *int64        `db:"max_price_paise" json:"max_price_paise"`
	Search        *string       `db:"search" json:"search"`
}

func (q *Queries) CountPlans(ctx context.Context, arg CountPlansParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlans,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.BillingCycle,
		arg.IsActive,
		arg.MinPricePaise,
		arg.MaxPricePaise,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    name, code, description, price_amount_paise, currency, billing_cycle,
    max_flats, max_admins, max_staff, max_residents, features, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, COALESCE($11, '{}'::jsonb), TRUE
)
RETURNING id, name, code, description, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, is_active, created_at, updated_at
`

type CreatePlanParams struct {
	Name             string       `db:"name" json:"name"`
	Code             string       `db:"code" json:"code"`
	Description      *string      `db:"description" json:"description"`
	PriceAmountPaise int64        `db:"price_amount_paise" json:"price_amount_paise"`
	Currency         string       `db:"currency" json:"currency"`
	BillingCycle     BillingCycle `db:"billing_cycle" json:"billing_cycle"`
	MaxFlats         int32        `db:"max_flats" json:"max_flats"`
	MaxAdmins        int32        `db:"max_admins" json:"max_admins"`
	MaxStaff         int32        `db:"max_staff" json:"max_staff"`
	MaxResidents     int32        `db:"max_residents" json:"max_residents"`
	Features         interface{}  `db:"features" json:"features"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.PriceAmountPaise,
		arg.Currency,
		arg.BillingCycle,
		arg.MaxFlats,
		arg.MaxAdmins,
		arg.MaxStaff,
		arg.MaxResidents,
		arg.Features,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivatePlan = `-- name: DeactivatePlan :one
UPDATE plans
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1
RETURNING id, name, code, description, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, is_active, created_at, updated_at
`

func (q *Queries) DeactivatePlan(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRow(ctx, deactivatePlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, code, description, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, is_active, created_at, updated_at
FROM plans
WHERE ($1::bigint IS NULL OR id = $1::bigint)
  AND ($2::text IS NULL OR code = $2::text)
  AND ($3::text IS NULL OR name = $3::text)
  AND ($4::billing_cycle IS NULL OR billing_cycle = $4::billing_cycle)
  AND ($5::bool IS NULL OR is_active = $5::bool)
  AND ($6::bigint IS NULL OR price_amount_paise >= $6::bigint)
  AND ($7::bigint IS NULL OR price_amount_paise <= $7::bigint)
  AND (
      COALESCE($8::text, '') = ''
      OR name ILIKE '%' || $8::text || '%'
      OR code ILIKE '%' || $8::text || '%'
      OR COALESCE(description, '') ILIKE '%' || $8::text || '%'
  )
ORDER BY id DESC
LIMIT 1
`

type GetPlanParams struct {
	ID            *int64        `db:"id" json:"id"`
	Code          *string       `db:"code" json:"code"`
	Name          *string       `db:"name" json:"name"`
	BillingCycle  *BillingCycle `db:"billing_cycle" json:"billing_cycle"`
	IsActive      *bool         `db:"is_active" json:"is_active"`
	MinPricePaise *int64        `db:"min_price_paise" json:"min_price_paise"`
	MaxPricePaise *int64        `db:"max_price_paise" json:"max_price_paise"`
	Search        *string       `db:"search" json:"search"`
}

func (q *Queries) GetPlan(ctx context.Context, arg GetPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.BillingCycle,
		arg.IsActive,
		arg.MinPricePaise,
		arg.MaxPricePaise,
		arg.Search,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, code, description, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, is_active, created_at, updated_at
FROM plans
WHERE ($1::bigint IS NULL OR id = $1::bigint)
  AND ($2::text IS NULL OR code = $2::text)
  AND ($3::text IS NULL OR name = $3::text)
  AND ($4::billing_cycle IS NULL OR billing_cycle = $4::billing_cycle)
  AND ($5::bool IS NULL OR is_active = $5::bool)
  AND ($6::bigint IS NULL OR price_amount_paise >= $6::bigint)
  AND ($7::bigint IS NULL OR price_amount_paise <= $7::bigint)
  AND (
      COALESCE($8::text, '') = ''
      OR name ILIKE '%' || $8::text || '%'
      OR code ILIKE '%' || $8::text || '%'
      OR COALESCE(description, '') ILIKE '%' || $8::text || '%'
  )
ORDER BY price_amount_paise ASC, id DESC
LIMIT $10 OFFSET $9
`

type ListPlansParams struct {
	ID            *int64        `db:"id" json:"id"`
	Code          *string       `db:"code" json:"code"`
	Name          *string       `db:"name" json:"name"`
	BillingCycle  *BillingCycle `db:"billing_cycle" json:"billing_cycle"`
	IsActive      *bool         `db:"is_active" json:"is_active"`
	MinPricePaise *int64        `db:"min_price_paise" json:"min_price_paise"`
	MaxPricePaise *int64        `db:"max_price_paise" json:"max_price_paise"`
	Search        *string       `db:"search" json:"search"`
	Offset        int32         `db:"offset" json:"offset"`
	Limit         int32         `db:"limit" json:"limit"`
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.BillingCycle,
		arg.IsActive,
		arg.MinPricePaise,
		arg.MaxPricePaise,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.PriceAmountPaise,
			&i.Currency,
			&i.BillingCycle,
			&i.MaxFlats,
			&i.MaxAdmins,
			&i.MaxStaff,
			&i.MaxResidents,
			&i.Features,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET
    name = COALESCE($1, name),
    code = COALESCE($2, code),
    description = COALESCE($3, description),
    price_amount_paise = COALESCE($4, price_amount_paise),
    currency = COALESCE($5, currency),
    billing_cycle = COALESCE($6, billing_cycle),
    max_flats = COALESCE($7, max_flats),
    max_admins = COALESCE($8, max_admins),
    max_staff = COALESCE($9, max_staff),
    max_residents = COALESCE($10, max_residents),
    features = COALESCE($11, features),
    updated_at = NOW()
WHERE id = $12
RETURNING id, name, code, description, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, is_active, created_at, updated_at
`

type UpdatePlanParams struct {
	Name             *string       `db:"name" json:"name"`
	Code             *string       `db:"code" json:"code"`
	Description      *string       `db:"description" json:"description"`
	PriceAmountPaise *int64        `db:"price_amount_paise" json:"price_amount_paise"`
	Currency         *string       `db:"currency" json:"currency"`
	BillingCycle     *BillingCycle `db:"billing_cycle" json:"billing_cycle"`
	MaxFlats         *int32        `db:"max_flats" json:"max_flats"`
	MaxAdmins        *int32        `db:"max_admins" json:"max_admins"`
	MaxStaff         *int32        `db:"max_staff" json:"max_staff"`
	MaxResidents     *int32        `db:"max_residents" json:"max_residents"`
	Features         []byte        `db:"features" json:"features"`
	ID               int64         `db:"id" json:"id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.PriceAmountPaise,
		arg.Currency,
		arg.BillingCycle,
		arg.MaxFlats,
		arg.MaxAdmins,
		arg.MaxStaff,
		arg.MaxResidents,
		arg.Features,
		arg.ID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
