// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: society.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveSociety = `-- name: ApproveSociety :one
UPDATE societies
SET status = 'active', approved_by = $2, approved_at = NOW(), rejected_by = NULL, rejected_at = NULL,
    rejection_reason = NULL, suspended_by = NULL, suspended_at = NULL, suspension_reason = NULL, updated_at = NOW()
WHERE id = $1 AND status = 'pending' AND deleted_at IS NULL
RETURNING id, name, society_code, email, phone_number, address_line1, address_line2, landmark, city, state, pincode, country, total_flats, total_blocks, status, created_by, approved_by, approved_at, rejected_by, rejected_at, rejection_reason, suspended_by, suspended_at, suspension_reason, metadata, created_at, updated_at, deleted_at
`

type ApproveSocietyParams struct {
	ID         int64  `db:"id" json:"id"`
	ApprovedBy *int64 `db:"approved_by" json:"approved_by"`
}

func (q *Queries) ApproveSociety(ctx context.Context, arg ApproveSocietyParams) (Society, error) {
	row := q.db.QueryRow(ctx, approveSociety, arg.ID, arg.ApprovedBy)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocietyCode,
		&i.Email,
		&i.PhoneNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.Country,
		&i.TotalFlats,
		&i.TotalBlocks,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.SuspendedBy,
		&i.SuspendedAt,
		&i.SuspensionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countPendingSocietiesByCreator = `-- name: CountPendingSocietiesByCreator :one
SELECT COUNT(*)
FROM societies
WHERE created_by = $1 AND status = 'pending' AND deleted_at IS NULL
`

func (q *Queries) CountPendingSocietiesByCreator(ctx context.Context, createdBy int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSocietiesByCreator, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSocieties = `-- name: CountSocieties :one
SELECT COUNT(*)
FROM societies
LEFT JOIN users created_user ON created_user.id = societies.created_by
LEFT JOIN users approved_user ON approved_user.id = societies.approved_by
LEFT JOIN users rejected_user ON rejected_user.id = societies.rejected_by
LEFT JOIN users suspended_user ON suspended_user.id = societies.suspended_by
WHERE ($1::bigint IS NULL OR societies.id = $1::bigint)
  AND ($2::society_status IS NULL OR societies.status = $2::society_status)
  AND ($3::bigint IS NULL OR societies.created_by = $3::bigint)
  AND ($4::bigint IS NULL OR societies.approved_by = $4::bigint)
  AND ($5::bigint IS NULL OR societies.rejected_by = $5::bigint)
  AND ($6::bigint IS NULL OR societies.suspended_by = $6::bigint)
  AND ($7::timestamptz IS NULL OR societies.created_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR societies.created_at <= $8::timestamptz)
  AND ($9::text = '' OR societies.society_code ILIKE '%' || $9::text || '%')
  AND ($10::text = '' OR societies.name ILIKE '%' || $10::text || '%')
  AND ($11::text = '' OR societies.city ILIKE '%' || $11::text || '%')
  AND ($12::text = '' OR societies.state ILIKE '%' || $12::text || '%')
  AND ($13::text = '' OR societies.country ILIKE '%' || $13::text || '%')
  AND ($14::text = '' OR societies.pincode ILIKE '%' || $14::text || '%')
  AND (
      $15::text = ''
      OR (
          $16::text IN ('', 'all')
          AND (
              societies.name ILIKE '%' || $15::text || '%'
              OR societies.society_code ILIKE '%' || $15::text || '%'
              OR COALESCE(societies.email, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(societies.phone_number, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(societies.city, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(societies.state, '') ILIKE '%' || $15::text || '%'
              OR societies.status::text ILIKE '%' || $15::text || '%'
          )
      )
      OR (
          $16::text IN ('', 'all', 'created_by')
          AND (
              COALESCE(created_user.full_name, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(created_user.email, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(created_user.phone_number, '') ILIKE '%' || $15::text || '%'
          )
      )
      OR (
          $16::text IN ('', 'all', 'approved_by')
          AND (
              COALESCE(approved_user.full_name, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(approved_user.email, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(approved_user.phone_number, '') ILIKE '%' || $15::text || '%'
          )
      )
      OR (
          $16::text IN ('', 'all', 'rejected_by')
          AND (
              COALESCE(rejected_user.full_name, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(rejected_user.email, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(rejected_user.phone_number, '') ILIKE '%' || $15::text || '%'
          )
      )
      OR (
          $16::text IN ('', 'all', 'suspended_by')
          AND (
              COALESCE(suspended_user.full_name, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(suspended_user.email, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(suspended_user.phone_number, '') ILIKE '%' || $15::text || '%'
          )
      )
  )
  AND societies.deleted_at IS NULL
`

type CountSocietiesParams struct {
	ID          *int64             `db:"id" json:"id"`
	Status      *SocietyStatus     `db:"status" json:"status"`
	CreatedBy   *int64             `db:"created_by" json:"created_by"`
	ApprovedBy  *int64             `db:"approved_by" json:"approved_by"`
	RejectedBy  *int64             `db:"rejected_by" json:"rejected_by"`
	SuspendedBy *int64             `db:"suspended_by" json:"suspended_by"`
	CreatedFrom pgtype.Timestamptz `db:"created_from" json:"created_from"`
	CreatedTo   pgtype.Timestamptz `db:"created_to" json:"created_to"`
	Code        string             `db:"code" json:"code"`
	Name        string             `db:"name" json:"name"`
	City        string             `db:"city" json:"city"`
	State       string             `db:"state" json:"state"`
	Country     string             `db:"country" json:"country"`
	Pincode     string             `db:"pincode" json:"pincode"`
	Search      string             `db:"search" json:"search"`
	SearchMode  string             `db:"search_mode" json:"search_mode"`
}

func (q *Queries) CountSocieties(ctx context.Context, arg CountSocietiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSocieties,
		arg.ID,
		arg.Status,
		arg.CreatedBy,
		arg.ApprovedBy,
		arg.RejectedBy,
		arg.SuspendedBy,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Code,
		arg.Name,
		arg.City,
		arg.State,
		arg.Country,
		arg.Pincode,
		arg.Search,
		arg.SearchMode,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSociety = `-- name: CreateSociety :one
INSERT INTO societies (
    name, society_code, email, phone_number,
    address_line1, address_line2, landmark, city, state, pincode, country,
    total_flats, total_blocks, status, created_by, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10, COALESCE($14, 'India'),
    $11, $12, 'pending', $13, COALESCE($15, '{}'::jsonb)
)
RETURNING id, name, society_code, email, phone_number, address_line1, address_line2, landmark, city, state, pincode, country, total_flats, total_blocks, status, created_by, approved_by, approved_at, rejected_by, rejected_at, rejection_reason, suspended_by, suspended_at, suspension_reason, metadata, created_at, updated_at, deleted_at
`

type CreateSocietyParams struct {
	Name         string      `db:"name" json:"name"`
	SocietyCode  string      `db:"society_code" json:"society_code"`
	Email        *string     `db:"email" json:"email"`
	PhoneNumber  *string     `db:"phone_number" json:"phone_number"`
	AddressLine1 *string     `db:"address_line1" json:"address_line1"`
	AddressLine2 *string     `db:"address_line2" json:"address_line2"`
	Landmark     *string     `db:"landmark" json:"landmark"`
	City         *string     `db:"city" json:"city"`
	State        *string     `db:"state" json:"state"`
	Pincode      *string     `db:"pincode" json:"pincode"`
	TotalFlats   int32       `db:"total_flats" json:"total_flats"`
	TotalBlocks  int32       `db:"total_blocks" json:"total_blocks"`
	CreatedBy    int64       `db:"created_by" json:"created_by"`
	Country      interface{} `db:"country" json:"country"`
	Metadata     interface{} `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateSociety(ctx context.Context, arg CreateSocietyParams) (Society, error) {
	row := q.db.QueryRow(ctx, createSociety,
		arg.Name,
		arg.SocietyCode,
		arg.Email,
		arg.PhoneNumber,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Landmark,
		arg.City,
		arg.State,
		arg.Pincode,
		arg.TotalFlats,
		arg.TotalBlocks,
		arg.CreatedBy,
		arg.Country,
		arg.Metadata,
	)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocietyCode,
		&i.Email,
		&i.PhoneNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.Country,
		&i.TotalFlats,
		&i.TotalBlocks,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.SuspendedBy,
		&i.SuspendedAt,
		&i.SuspensionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSociety = `-- name: GetSociety :one
SELECT id, name, society_code, email, phone_number, address_line1, address_line2, landmark, city, state, pincode, country, total_flats, total_blocks, status, created_by, approved_by, approved_at, rejected_by, rejected_at, rejection_reason, suspended_by, suspended_at, suspension_reason, metadata, created_at, updated_at, deleted_at
FROM societies
WHERE ($1::bigint IS NULL OR id = $1::bigint)
  AND ($2::text IS NULL OR society_code = $2::text)
  AND ($3::bigint IS NULL OR created_by = $3::bigint)
  AND ($4::society_status IS NULL OR status = $4::society_status)
  AND ($5::bool OR deleted_at IS NULL)
ORDER BY id DESC
LIMIT 1
`

type GetSocietyParams struct {
	ID             *int64         `db:"id" json:"id"`
	Code           *string        `db:"code" json:"code"`
	CreatedBy      *int64         `db:"created_by" json:"created_by"`
	Status         *SocietyStatus `db:"status" json:"status"`
	IncludeDeleted bool           `db:"include_deleted" json:"include_deleted"`
}

func (q *Queries) GetSociety(ctx context.Context, arg GetSocietyParams) (Society, error) {
	row := q.db.QueryRow(ctx, getSociety,
		arg.ID,
		arg.Code,
		arg.CreatedBy,
		arg.Status,
		arg.IncludeDeleted,
	)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocietyCode,
		&i.Email,
		&i.PhoneNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.Country,
		&i.TotalFlats,
		&i.TotalBlocks,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.SuspendedBy,
		&i.SuspendedAt,
		&i.SuspensionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSocieties = `-- name: ListSocieties :many
SELECT societies.id, societies.name, societies.society_code, societies.email, societies.phone_number, societies.address_line1, societies.address_line2, societies.landmark, societies.city, societies.state, societies.pincode, societies.country, societies.total_flats, societies.total_blocks, societies.status, societies.created_by, societies.approved_by, societies.approved_at, societies.rejected_by, societies.rejected_at, societies.rejection_reason, societies.suspended_by, societies.suspended_at, societies.suspension_reason, societies.metadata, societies.created_at, societies.updated_at, societies.deleted_at
FROM societies
LEFT JOIN users created_user ON created_user.id = societies.created_by
LEFT JOIN users approved_user ON approved_user.id = societies.approved_by
LEFT JOIN users rejected_user ON rejected_user.id = societies.rejected_by
LEFT JOIN users suspended_user ON suspended_user.id = societies.suspended_by
WHERE ($1::bigint IS NULL OR societies.id = $1::bigint)
  AND ($2::society_status IS NULL OR societies.status = $2::society_status)
  AND ($3::bigint IS NULL OR societies.created_by = $3::bigint)
  AND ($4::bigint IS NULL OR societies.approved_by = $4::bigint)
  AND ($5::bigint IS NULL OR societies.rejected_by = $5::bigint)
  AND ($6::bigint IS NULL OR societies.suspended_by = $6::bigint)
  AND ($7::timestamptz IS NULL OR societies.created_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR societies.created_at <= $8::timestamptz)
  AND ($9::text = '' OR societies.society_code ILIKE '%' || $9::text || '%')
  AND ($10::text = '' OR societies.name ILIKE '%' || $10::text || '%')
  AND ($11::text = '' OR societies.city ILIKE '%' || $11::text || '%')
  AND ($12::text = '' OR societies.state ILIKE '%' || $12::text || '%')
  AND ($13::text = '' OR societies.country ILIKE '%' || $13::text || '%')
  AND ($14::text = '' OR societies.pincode ILIKE '%' || $14::text || '%')
  AND (
      $15::text = ''
      OR (
          $16::text IN ('', 'all')
          AND (
              societies.name ILIKE '%' || $15::text || '%'
              OR societies.society_code ILIKE '%' || $15::text || '%'
              OR COALESCE(societies.email, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(societies.phone_number, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(societies.city, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(societies.state, '') ILIKE '%' || $15::text || '%'
              OR societies.status::text ILIKE '%' || $15::text || '%'
          )
      )
      OR (
          $16::text IN ('', 'all', 'created_by')
          AND (
              COALESCE(created_user.full_name, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(created_user.email, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(created_user.phone_number, '') ILIKE '%' || $15::text || '%'
          )
      )
      OR (
          $16::text IN ('', 'all', 'approved_by')
          AND (
              COALESCE(approved_user.full_name, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(approved_user.email, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(approved_user.phone_number, '') ILIKE '%' || $15::text || '%'
          )
      )
      OR (
          $16::text IN ('', 'all', 'rejected_by')
          AND (
              COALESCE(rejected_user.full_name, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(rejected_user.email, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(rejected_user.phone_number, '') ILIKE '%' || $15::text || '%'
          )
      )
      OR (
          $16::text IN ('', 'all', 'suspended_by')
          AND (
              COALESCE(suspended_user.full_name, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(suspended_user.email, '') ILIKE '%' || $15::text || '%'
              OR COALESCE(suspended_user.phone_number, '') ILIKE '%' || $15::text || '%'
          )
      )
  )
  AND societies.deleted_at IS NULL
ORDER BY
    CASE WHEN $17 = 'name' AND $18 = 'asc' THEN societies.name END ASC,
    CASE WHEN $17 = 'name' AND $18 = 'desc' THEN societies.name END DESC,
    CASE WHEN $17 = 'city' AND $18 = 'asc' THEN societies.city END ASC,
    CASE WHEN $17 = 'city' AND $18 = 'desc' THEN societies.city END DESC,
    CASE WHEN $17 = 'status' AND $18 = 'asc' THEN societies.status END ASC,
    CASE WHEN $17 = 'status' AND $18 = 'desc' THEN societies.status END DESC,
    CASE WHEN $17 = 'updated_at' AND $18 = 'asc' THEN societies.updated_at END ASC,
    CASE WHEN $17 = 'updated_at' AND $18 = 'desc' THEN societies.updated_at END DESC,
    CASE WHEN $18 = 'asc' THEN societies.created_at END ASC,
    societies.created_at DESC
LIMIT $20 OFFSET $19
`

type ListSocietiesParams struct {
	ID          *int64             `db:"id" json:"id"`
	Status      *SocietyStatus     `db:"status" json:"status"`
	CreatedBy   *int64             `db:"created_by" json:"created_by"`
	ApprovedBy  *int64             `db:"approved_by" json:"approved_by"`
	RejectedBy  *int64             `db:"rejected_by" json:"rejected_by"`
	SuspendedBy *int64             `db:"suspended_by" json:"suspended_by"`
	CreatedFrom pgtype.Timestamptz `db:"created_from" json:"created_from"`
	CreatedTo   pgtype.Timestamptz `db:"created_to" json:"created_to"`
	Code        string             `db:"code" json:"code"`
	Name        string             `db:"name" json:"name"`
	City        string             `db:"city" json:"city"`
	State       string             `db:"state" json:"state"`
	Country     string             `db:"country" json:"country"`
	Pincode     string             `db:"pincode" json:"pincode"`
	Search      string             `db:"search" json:"search"`
	SearchMode  string             `db:"search_mode" json:"search_mode"`
	SortBy      interface{}        `db:"sort_by" json:"sort_by"`
	SortOrder   interface{}        `db:"sort_order" json:"sort_order"`
	Offset      int32              `db:"offset" json:"offset"`
	Limit       int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListSocieties(ctx context.Context, arg ListSocietiesParams) ([]Society, error) {
	rows, err := q.db.Query(ctx, listSocieties,
		arg.ID,
		arg.Status,
		arg.CreatedBy,
		arg.ApprovedBy,
		arg.RejectedBy,
		arg.SuspendedBy,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Code,
		arg.Name,
		arg.City,
		arg.State,
		arg.Country,
		arg.Pincode,
		arg.Search,
		arg.SearchMode,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Society{}
	for rows.Next() {
		var i Society
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SocietyCode,
			&i.Email,
			&i.PhoneNumber,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Landmark,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.Country,
			&i.TotalFlats,
			&i.TotalBlocks,
			&i.Status,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.SuspendedBy,
			&i.SuspendedAt,
			&i.SuspensionReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateSociety = `-- name: ReactivateSociety :one
UPDATE societies
SET status = 'active', approved_by = $2, approved_at = NOW(), suspended_by = NULL, suspended_at = NULL,
    suspension_reason = NULL, updated_at = NOW()
WHERE id = $1 AND status = 'suspended' AND deleted_at IS NULL
RETURNING id, name, society_code, email, phone_number, address_line1, address_line2, landmark, city, state, pincode, country, total_flats, total_blocks, status, created_by, approved_by, approved_at, rejected_by, rejected_at, rejection_reason, suspended_by, suspended_at, suspension_reason, metadata, created_at, updated_at, deleted_at
`

type ReactivateSocietyParams struct {
	ID         int64  `db:"id" json:"id"`
	ApprovedBy *int64 `db:"approved_by" json:"approved_by"`
}

func (q *Queries) ReactivateSociety(ctx context.Context, arg ReactivateSocietyParams) (Society, error) {
	row := q.db.QueryRow(ctx, reactivateSociety, arg.ID, arg.ApprovedBy)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocietyCode,
		&i.Email,
		&i.PhoneNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.Country,
		&i.TotalFlats,
		&i.TotalBlocks,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.SuspendedBy,
		&i.SuspendedAt,
		&i.SuspensionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const rejectSociety = `-- name: RejectSociety :one
UPDATE societies
SET status = 'rejected', rejected_by = $2, rejected_at = NOW(), rejection_reason = $3, updated_at = NOW()
WHERE id = $1 AND status = 'pending' AND deleted_at IS NULL
RETURNING id, name, society_code, email, phone_number, address_line1, address_line2, landmark, city, state, pincode, country, total_flats, total_blocks, status, created_by, approved_by, approved_at, rejected_by, rejected_at, rejection_reason, suspended_by, suspended_at, suspension_reason, metadata, created_at, updated_at, deleted_at
`

type RejectSocietyParams struct {
	ID              int64   `db:"id" json:"id"`
	RejectedBy      *int64  `db:"rejected_by" json:"rejected_by"`
	RejectionReason *string `db:"rejection_reason" json:"rejection_reason"`
}

func (q *Queries) RejectSociety(ctx context.Context, arg RejectSocietyParams) (Society, error) {
	row := q.db.QueryRow(ctx, rejectSociety, arg.ID, arg.RejectedBy, arg.RejectionReason)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocietyCode,
		&i.Email,
		&i.PhoneNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.Country,
		&i.TotalFlats,
		&i.TotalBlocks,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.SuspendedBy,
		&i.SuspendedAt,
		&i.SuspensionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const restoreSociety = `-- name: RestoreSociety :one
UPDATE societies
SET status = 'pending', deleted_at = NULL, approved_by = NULL, approved_at = NULL, rejected_by = NULL,
    rejected_at = NULL, rejection_reason = NULL, suspended_by = NULL, suspended_at = NULL,
    suspension_reason = NULL, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, name, society_code, email, phone_number, address_line1, address_line2, landmark, city, state, pincode, country, total_flats, total_blocks, status, created_by, approved_by, approved_at, rejected_by, rejected_at, rejection_reason, suspended_by, suspended_at, suspension_reason, metadata, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreSociety(ctx context.Context, id int64) (Society, error) {
	row := q.db.QueryRow(ctx, restoreSociety, id)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocietyCode,
		&i.Email,
		&i.PhoneNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.Country,
		&i.TotalFlats,
		&i.TotalBlocks,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.SuspendedBy,
		&i.SuspendedAt,
		&i.SuspensionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteSociety = `-- name: SoftDeleteSociety :exec
UPDATE societies
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSociety(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteSociety, id)
	return err
}

const suspendSociety = `-- name: SuspendSociety :one
UPDATE societies
SET status = 'suspended', suspended_by = $2, suspended_at = NOW(), suspension_reason = $3, updated_at = NOW()
WHERE id = $1 AND status = 'active' AND deleted_at IS NULL
RETURNING id, name, society_code, email, phone_number, address_line1, address_line2, landmark, city, state, pincode, country, total_flats, total_blocks, status, created_by, approved_by, approved_at, rejected_by, rejected_at, rejection_reason, suspended_by, suspended_at, suspension_reason, metadata, created_at, updated_at, deleted_at
`

type SuspendSocietyParams struct {
	ID               int64   `db:"id" json:"id"`
	SuspendedBy      *int64  `db:"suspended_by" json:"suspended_by"`
	SuspensionReason *string `db:"suspension_reason" json:"suspension_reason"`
}

func (q *Queries) SuspendSociety(ctx context.Context, arg SuspendSocietyParams) (Society, error) {
	row := q.db.QueryRow(ctx, suspendSociety, arg.ID, arg.SuspendedBy, arg.SuspensionReason)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocietyCode,
		&i.Email,
		&i.PhoneNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.Country,
		&i.TotalFlats,
		&i.TotalBlocks,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.SuspendedBy,
		&i.SuspendedAt,
		&i.SuspensionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSociety = `-- name: UpdateSociety :one
UPDATE societies
SET
    name = COALESCE($1, name),
    email = COALESCE($2, email),
    phone_number = COALESCE($3, phone_number),
    address_line1 = COALESCE($4, address_line1),
    address_line2 = COALESCE($5, address_line2),
    landmark = COALESCE($6, landmark),
    city = COALESCE($7, city),
    state = COALESCE($8, state),
    pincode = COALESCE($9, pincode),
    country = COALESCE($10, country),
    total_flats = COALESCE($11, total_flats),
    total_blocks = COALESCE($12, total_blocks),
    metadata = COALESCE($13, metadata),
    updated_at = NOW()
WHERE id = $14
  AND deleted_at IS NULL
RETURNING id, name, society_code, email, phone_number, address_line1, address_line2, landmark, city, state, pincode, country, total_flats, total_blocks, status, created_by, approved_by, approved_at, rejected_by, rejected_at, rejection_reason, suspended_by, suspended_at, suspension_reason, metadata, created_at, updated_at, deleted_at
`

type UpdateSocietyParams struct {
	Name         *string `db:"name" json:"name"`
	Email        *string `db:"email" json:"email"`
	PhoneNumber  *string `db:"phone_number" json:"phone_number"`
	AddressLine1 *string `db:"address_line1" json:"address_line1"`
	AddressLine2 *string `db:"address_line2" json:"address_line2"`
	Landmark     *string `db:"landmark" json:"landmark"`
	City         *string `db:"city" json:"city"`
	State        *string `db:"state" json:"state"`
	Pincode      *string `db:"pincode" json:"pincode"`
	Country      *string `db:"country" json:"country"`
	TotalFlats   *int32  `db:"total_flats" json:"total_flats"`
	TotalBlocks  *int32  `db:"total_blocks" json:"total_blocks"`
	Metadata     []byte  `db:"metadata" json:"metadata"`
	ID           int64   `db:"id" json:"id"`
}

func (q *Queries) UpdateSociety(ctx context.Context, arg UpdateSocietyParams) (Society, error) {
	row := q.db.QueryRow(ctx, updateSociety,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Landmark,
		arg.City,
		arg.State,
		arg.Pincode,
		arg.Country,
		arg.TotalFlats,
		arg.TotalBlocks,
		arg.Metadata,
		arg.ID,
	)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SocietyCode,
		&i.Email,
		&i.PhoneNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.Country,
		&i.TotalFlats,
		&i.TotalBlocks,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.SuspendedBy,
		&i.SuspendedAt,
		&i.SuspensionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
