// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: society_member.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSocietyMember = `-- name: AddSocietyMember :one
INSERT INTO society_members (society_id, user_id, role, status, invited_by, metadata)
VALUES ($1, $2, $3, 'active', $4, COALESCE($5, '{}'::jsonb))
RETURNING id, society_id, user_id, role, status, invited_by, joined_at, removed_by, removed_at, remove_reason, metadata, created_at, updated_at
`

type AddSocietyMemberParams struct {
	SocietyID int64             `db:"society_id" json:"society_id"`
	UserID    int64             `db:"user_id" json:"user_id"`
	Role      SocietyMemberRole `db:"role" json:"role"`
	InvitedBy *int64            `db:"invited_by" json:"invited_by"`
	Metadata  interface{}       `db:"metadata" json:"metadata"`
}

func (q *Queries) AddSocietyMember(ctx context.Context, arg AddSocietyMemberParams) (SocietyMember, error) {
	row := q.db.QueryRow(ctx, addSocietyMember,
		arg.SocietyID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
		arg.Metadata,
	)
	var i SocietyMember
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.RemovedBy,
		&i.RemovedAt,
		&i.RemoveReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const changeSocietyMemberRole = `-- name: ChangeSocietyMemberRole :one
UPDATE society_members
SET role = $3, updated_at = NOW()
WHERE society_id = $1 AND user_id = $2
RETURNING id, society_id, user_id, role, status, invited_by, joined_at, removed_by, removed_at, remove_reason, metadata, created_at, updated_at
`

type ChangeSocietyMemberRoleParams struct {
	SocietyID int64             `db:"society_id" json:"society_id"`
	UserID    int64             `db:"user_id" json:"user_id"`
	Role      SocietyMemberRole `db:"role" json:"role"`
}

func (q *Queries) ChangeSocietyMemberRole(ctx context.Context, arg ChangeSocietyMemberRoleParams) (SocietyMember, error) {
	row := q.db.QueryRow(ctx, changeSocietyMemberRole, arg.SocietyID, arg.UserID, arg.Role)
	var i SocietyMember
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.RemovedBy,
		&i.RemovedAt,
		&i.RemoveReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveOwners = `-- name: CountActiveOwners :one
SELECT COUNT(*)
FROM society_members
WHERE society_id = $1 AND role = 'owner' AND status = 'active'
`

func (q *Queries) CountActiveOwners(ctx context.Context, societyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOwners, societyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSocietyMembers = `-- name: CountSocietyMembers :one
SELECT COUNT(*)
FROM society_members sm
JOIN users u ON u.id = sm.user_id
LEFT JOIN users invited_user ON invited_user.id = sm.invited_by
LEFT JOIN users removed_user ON removed_user.id = sm.removed_by
WHERE sm.society_id = $1
  AND ($2::society_member_role IS NULL OR sm.role = $2::society_member_role)
  AND ($3::society_member_status IS NULL OR sm.status = $3::society_member_status)
  AND ($4::bigint IS NULL OR sm.user_id = $4::bigint)
  AND ($5::bigint IS NULL OR sm.invited_by = $5::bigint)
  AND ($6::bigint IS NULL OR sm.removed_by = $6::bigint)
  AND ($7::timestamptz IS NULL OR sm.joined_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR sm.joined_at <= $8::timestamptz)
  AND (
      $9::text = ''
      OR (
          $10::text IN ('', 'all', 'resident')
          AND (
              u.full_name ILIKE '%' || $9::text || '%'
              OR COALESCE(u.email, '') ILIKE '%' || $9::text || '%'
              OR COALESCE(u.phone_number, '') ILIKE '%' || $9::text || '%'
          )
      )
      OR (
          $10::text IN ('', 'all', 'invited_by')
          AND (
              COALESCE(invited_user.full_name, '') ILIKE '%' || $9::text || '%'
              OR COALESCE(invited_user.email, '') ILIKE '%' || $9::text || '%'
              OR COALESCE(invited_user.phone_number, '') ILIKE '%' || $9::text || '%'
          )
      )
      OR (
          $10::text IN ('', 'all', 'removed_by')
          AND (
              COALESCE(removed_user.full_name, '') ILIKE '%' || $9::text || '%'
              OR COALESCE(removed_user.email, '') ILIKE '%' || $9::text || '%'
              OR COALESCE(removed_user.phone_number, '') ILIKE '%' || $9::text || '%'
          )
      )
      OR (
          $10::text IN ('', 'all')
          AND (
              sm.role::text ILIKE '%' || $9::text || '%'
              OR sm.status::text ILIKE '%' || $9::text || '%'
          )
      )
  )
`

type CountSocietyMembersParams struct {
	SocietyID  int64                `db:"society_id" json:"society_id"`
	Role       *SocietyMemberRole   `db:"role" json:"role"`
	Status     *SocietyMemberStatus `db:"status" json:"status"`
	UserID     *int64               `db:"user_id" json:"user_id"`
	InvitedBy  *int64               `db:"invited_by" json:"invited_by"`
	RemovedBy  *int64               `db:"removed_by" json:"removed_by"`
	JoinedFrom pgtype.Timestamptz   `db:"joined_from" json:"joined_from"`
	JoinedTo   pgtype.Timestamptz   `db:"joined_to" json:"joined_to"`
	Search     string               `db:"search" json:"search"`
	SearchMode string               `db:"search_mode" json:"search_mode"`
}

func (q *Queries) CountSocietyMembers(ctx context.Context, arg CountSocietyMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSocietyMembers,
		arg.SocietyID,
		arg.Role,
		arg.Status,
		arg.UserID,
		arg.InvitedBy,
		arg.RemovedBy,
		arg.JoinedFrom,
		arg.JoinedTo,
		arg.Search,
		arg.SearchMode,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const demoteActiveOwners = `-- name: DemoteActiveOwners :exec
UPDATE society_members
SET role = 'admin', updated_at = NOW()
WHERE society_id = $1 AND role = 'owner' AND status = 'active' AND user_id <> $2
`

type DemoteActiveOwnersParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DemoteActiveOwners(ctx context.Context, arg DemoteActiveOwnersParams) error {
	_, err := q.db.Exec(ctx, demoteActiveOwners, arg.SocietyID, arg.UserID)
	return err
}

const getSocietyMember = `-- name: GetSocietyMember :one
SELECT
    sm.id, sm.society_id, sm.user_id, sm.role, sm.status, sm.invited_by, sm.joined_at, sm.removed_by, sm.removed_at, sm.remove_reason, sm.metadata, sm.created_at, sm.updated_at,
    u.full_name AS user_full_name,
    u.email AS user_email,
    u.phone_number AS user_phone
FROM society_members sm
JOIN users u ON u.id = sm.user_id
WHERE ($1::bigint IS NULL OR sm.id = $1::bigint)
  AND ($2::bigint IS NULL OR sm.society_id = $2::bigint)
  AND ($3::bigint IS NULL OR sm.user_id = $3::bigint)
  AND ($4::society_member_role IS NULL OR sm.role = $4::society_member_role)
  AND ($5::society_member_status IS NULL OR sm.status = $5::society_member_status)
  AND ($6::text IS NULL OR u.email = $6::text)
  AND ($7::text IS NULL OR u.phone_number = $7::text)
ORDER BY sm.id DESC
LIMIT 1
`

type GetSocietyMemberParams struct {
	ID        *int64               `db:"id" json:"id"`
	SocietyID *int64               `db:"society_id" json:"society_id"`
	UserID    *int64               `db:"user_id" json:"user_id"`
	Role      *SocietyMemberRole   `db:"role" json:"role"`
	Status    *SocietyMemberStatus `db:"status" json:"status"`
	Email     *string              `db:"email" json:"email"`
	Phone     *string              `db:"phone" json:"phone"`
}

type GetSocietyMemberRow struct {
	ID           int64               `db:"id" json:"id"`
	SocietyID    int64               `db:"society_id" json:"society_id"`
	UserID       int64               `db:"user_id" json:"user_id"`
	Role         SocietyMemberRole   `db:"role" json:"role"`
	Status       SocietyMemberStatus `db:"status" json:"status"`
	InvitedBy    *int64              `db:"invited_by" json:"invited_by"`
	JoinedAt     pgtype.Timestamptz  `db:"joined_at" json:"joined_at"`
	RemovedBy    *int64              `db:"removed_by" json:"removed_by"`
	RemovedAt    pgtype.Timestamptz  `db:"removed_at" json:"removed_at"`
	RemoveReason *string             `db:"remove_reason" json:"remove_reason"`
	Metadata     []byte              `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	UserFullName string              `db:"user_full_name" json:"user_full_name"`
	UserEmail    *string             `db:"user_email" json:"user_email"`
	UserPhone    *string             `db:"user_phone" json:"user_phone"`
}

func (q *Queries) GetSocietyMember(ctx context.Context, arg GetSocietyMemberParams) (GetSocietyMemberRow, error) {
	row := q.db.QueryRow(ctx, getSocietyMember,
		arg.ID,
		arg.SocietyID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.Email,
		arg.Phone,
	)
	var i GetSocietyMemberRow
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.RemovedBy,
		&i.RemovedAt,
		&i.RemoveReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserFullName,
		&i.UserEmail,
		&i.UserPhone,
	)
	return i, err
}

const listSocietyMembers = `-- name: ListSocietyMembers :many
SELECT
    sm.id, sm.society_id, sm.user_id, sm.role, sm.status, sm.invited_by, sm.joined_at, sm.removed_by, sm.removed_at, sm.remove_reason, sm.metadata, sm.created_at, sm.updated_at,
    u.full_name AS user_full_name,
    u.email AS user_email,
    u.phone_number AS user_phone
FROM society_members sm
JOIN users u ON u.id = sm.user_id
LEFT JOIN users invited_user ON invited_user.id = sm.invited_by
LEFT JOIN users removed_user ON removed_user.id = sm.removed_by
WHERE sm.society_id = $1
  AND ($2::society_member_role IS NULL OR sm.role = $2::society_member_role)
  AND ($3::society_member_status IS NULL OR sm.status = $3::society_member_status)
  AND ($4::bigint IS NULL OR sm.user_id = $4::bigint)
  AND ($5::bigint IS NULL OR sm.invited_by = $5::bigint)
  AND ($6::bigint IS NULL OR sm.removed_by = $6::bigint)
  AND ($7::timestamptz IS NULL OR sm.joined_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR sm.joined_at <= $8::timestamptz)
  AND (
      $9::text = ''
      OR (
          $10::text IN ('', 'all', 'resident')
          AND (
              u.full_name ILIKE '%' || $9::text || '%'
              OR COALESCE(u.email, '') ILIKE '%' || $9::text || '%'
              OR COALESCE(u.phone_number, '') ILIKE '%' || $9::text || '%'
          )
      )
      OR (
          $10::text IN ('', 'all', 'invited_by')
          AND (
              COALESCE(invited_user.full_name, '') ILIKE '%' || $9::text || '%'
              OR COALESCE(invited_user.email, '') ILIKE '%' || $9::text || '%'
              OR COALESCE(invited_user.phone_number, '') ILIKE '%' || $9::text || '%'
          )
      )
      OR (
          $10::text IN ('', 'all', 'removed_by')
          AND (
              COALESCE(removed_user.full_name, '') ILIKE '%' || $9::text || '%'
              OR COALESCE(removed_user.email, '') ILIKE '%' || $9::text || '%'
              OR COALESCE(removed_user.phone_number, '') ILIKE '%' || $9::text || '%'
          )
      )
      OR (
          $10::text IN ('', 'all')
          AND (
              sm.role::text ILIKE '%' || $9::text || '%'
              OR sm.status::text ILIKE '%' || $9::text || '%'
          )
      )
  )
ORDER BY
    CASE WHEN $11 = 'role' AND $12 = 'asc' THEN sm.role END ASC,
    CASE WHEN $11 = 'role' AND $12 = 'desc' THEN sm.role END DESC,
    CASE WHEN $11 = 'status' AND $12 = 'asc' THEN sm.status END ASC,
    CASE WHEN $11 = 'status' AND $12 = 'desc' THEN sm.status END DESC,
    CASE WHEN $11 = 'joined_at' AND $12 = 'asc' THEN sm.joined_at END ASC,
    sm.joined_at DESC
LIMIT $14 OFFSET $13
`

type ListSocietyMembersParams struct {
	SocietyID  int64                `db:"society_id" json:"society_id"`
	Role       *SocietyMemberRole   `db:"role" json:"role"`
	Status     *SocietyMemberStatus `db:"status" json:"status"`
	UserID     *int64               `db:"user_id" json:"user_id"`
	InvitedBy  *int64               `db:"invited_by" json:"invited_by"`
	RemovedBy  *int64               `db:"removed_by" json:"removed_by"`
	JoinedFrom pgtype.Timestamptz   `db:"joined_from" json:"joined_from"`
	JoinedTo   pgtype.Timestamptz   `db:"joined_to" json:"joined_to"`
	Search     string               `db:"search" json:"search"`
	SearchMode string               `db:"search_mode" json:"search_mode"`
	SortBy     interface{}          `db:"sort_by" json:"sort_by"`
	SortOrder  interface{}          `db:"sort_order" json:"sort_order"`
	Offset     int32                `db:"offset" json:"offset"`
	Limit      int32                `db:"limit" json:"limit"`
}

type ListSocietyMembersRow struct {
	ID           int64               `db:"id" json:"id"`
	SocietyID    int64               `db:"society_id" json:"society_id"`
	UserID       int64               `db:"user_id" json:"user_id"`
	Role         SocietyMemberRole   `db:"role" json:"role"`
	Status       SocietyMemberStatus `db:"status" json:"status"`
	InvitedBy    *int64              `db:"invited_by" json:"invited_by"`
	JoinedAt     pgtype.Timestamptz  `db:"joined_at" json:"joined_at"`
	RemovedBy    *int64              `db:"removed_by" json:"removed_by"`
	RemovedAt    pgtype.Timestamptz  `db:"removed_at" json:"removed_at"`
	RemoveReason *string             `db:"remove_reason" json:"remove_reason"`
	Metadata     []byte              `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	UserFullName string              `db:"user_full_name" json:"user_full_name"`
	UserEmail    *string             `db:"user_email" json:"user_email"`
	UserPhone    *string             `db:"user_phone" json:"user_phone"`
}

func (q *Queries) ListSocietyMembers(ctx context.Context, arg ListSocietyMembersParams) ([]ListSocietyMembersRow, error) {
	rows, err := q.db.Query(ctx, listSocietyMembers,
		arg.SocietyID,
		arg.Role,
		arg.Status,
		arg.UserID,
		arg.InvitedBy,
		arg.RemovedBy,
		arg.JoinedFrom,
		arg.JoinedTo,
		arg.Search,
		arg.SearchMode,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocietyMembersRow{}
	for rows.Next() {
		var i ListSocietyMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.RemovedBy,
			&i.RemovedAt,
			&i.RemoveReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserFullName,
			&i.UserEmail,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocietyMembershipsByUser = `-- name: ListSocietyMembershipsByUser :many
SELECT
    sm.id, sm.society_id, sm.user_id, sm.role, sm.status, sm.invited_by, sm.joined_at, sm.removed_by, sm.removed_at, sm.remove_reason, sm.metadata, sm.created_at, sm.updated_at,
    u.full_name AS user_full_name,
    u.email AS user_email,
    u.phone_number AS user_phone
FROM society_members sm
JOIN users u ON u.id = sm.user_id
WHERE sm.user_id = $1
  AND sm.status != 'removed'
ORDER BY sm.joined_at DESC
`

type ListSocietyMembershipsByUserRow struct {
	ID           int64               `db:"id" json:"id"`
	SocietyID    int64               `db:"society_id" json:"society_id"`
	UserID       int64               `db:"user_id" json:"user_id"`
	Role         SocietyMemberRole   `db:"role" json:"role"`
	Status       SocietyMemberStatus `db:"status" json:"status"`
	InvitedBy    *int64              `db:"invited_by" json:"invited_by"`
	JoinedAt     pgtype.Timestamptz  `db:"joined_at" json:"joined_at"`
	RemovedBy    *int64              `db:"removed_by" json:"removed_by"`
	RemovedAt    pgtype.Timestamptz  `db:"removed_at" json:"removed_at"`
	RemoveReason *string             `db:"remove_reason" json:"remove_reason"`
	Metadata     []byte              `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	UserFullName string              `db:"user_full_name" json:"user_full_name"`
	UserEmail    *string             `db:"user_email" json:"user_email"`
	UserPhone    *string             `db:"user_phone" json:"user_phone"`
}

func (q *Queries) ListSocietyMembershipsByUser(ctx context.Context, userID int64) ([]ListSocietyMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSocietyMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocietyMembershipsByUserRow{}
	for rows.Next() {
		var i ListSocietyMembershipsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.RemovedBy,
			&i.RemovedAt,
			&i.RemoveReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserFullName,
			&i.UserEmail,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteMemberToOwner = `-- name: PromoteMemberToOwner :one
UPDATE society_members
SET role = 'owner', status = 'active', removed_by = NULL, removed_at = NULL, remove_reason = NULL, updated_at = NOW()
WHERE society_id = $1 AND user_id = $2
RETURNING id, society_id, user_id, role, status, invited_by, joined_at, removed_by, removed_at, remove_reason, metadata, created_at, updated_at
`

type PromoteMemberToOwnerParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) PromoteMemberToOwner(ctx context.Context, arg PromoteMemberToOwnerParams) (SocietyMember, error) {
	row := q.db.QueryRow(ctx, promoteMemberToOwner, arg.SocietyID, arg.UserID)
	var i SocietyMember
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.RemovedBy,
		&i.RemovedAt,
		&i.RemoveReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reactivateSocietyMember = `-- name: ReactivateSocietyMember :one
UPDATE society_members
SET status = 'active', removed_by = NULL, removed_at = NULL, remove_reason = NULL, updated_at = NOW()
WHERE society_id = $1 AND user_id = $2 AND status IN ('suspended', 'removed')
RETURNING id, society_id, user_id, role, status, invited_by, joined_at, removed_by, removed_at, remove_reason, metadata, created_at, updated_at
`

type ReactivateSocietyMemberParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) ReactivateSocietyMember(ctx context.Context, arg ReactivateSocietyMemberParams) (SocietyMember, error) {
	row := q.db.QueryRow(ctx, reactivateSocietyMember, arg.SocietyID, arg.UserID)
	var i SocietyMember
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.RemovedBy,
		&i.RemovedAt,
		&i.RemoveReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeSocietyMember = `-- name: RemoveSocietyMember :exec
UPDATE society_members
SET status = 'removed', removed_by = $3, removed_at = NOW(), remove_reason = $4, updated_at = NOW()
WHERE society_id = $1 AND user_id = $2 AND status != 'removed'
`

type RemoveSocietyMemberParams struct {
	SocietyID    int64   `db:"society_id" json:"society_id"`
	UserID       int64   `db:"user_id" json:"user_id"`
	RemovedBy    *int64  `db:"removed_by" json:"removed_by"`
	RemoveReason *string `db:"remove_reason" json:"remove_reason"`
}

func (q *Queries) RemoveSocietyMember(ctx context.Context, arg RemoveSocietyMemberParams) error {
	_, err := q.db.Exec(ctx, removeSocietyMember,
		arg.SocietyID,
		arg.UserID,
		arg.RemovedBy,
		arg.RemoveReason,
	)
	return err
}

const suspendSocietyMember = `-- name: SuspendSocietyMember :one
UPDATE society_members
SET status = 'suspended', updated_at = NOW()
WHERE society_id = $1 AND user_id = $2 AND status = 'active'
RETURNING id, society_id, user_id, role, status, invited_by, joined_at, removed_by, removed_at, remove_reason, metadata, created_at, updated_at
`

type SuspendSocietyMemberParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) SuspendSocietyMember(ctx context.Context, arg SuspendSocietyMemberParams) (SocietyMember, error) {
	row := q.db.QueryRow(ctx, suspendSocietyMember, arg.SocietyID, arg.UserID)
	var i SocietyMember
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.RemovedBy,
		&i.RemovedAt,
		&i.RemoveReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertResidentSocietyMember = `-- name: UpsertResidentSocietyMember :one
INSERT INTO society_members (society_id, user_id, role, status, invited_by, metadata)
VALUES ($1, $2, 'resident', 'active', $3, '{}'::jsonb)
ON CONFLICT (society_id, user_id) DO UPDATE
SET
    role = CASE
        WHEN society_members.role IN ('owner', 'admin', 'staff') THEN society_members.role
        ELSE 'resident'
    END,
    status = 'active',
    removed_by = NULL,
    removed_at = NULL,
    remove_reason = NULL,
    updated_at = NOW()
RETURNING id, society_id, user_id, role, status, invited_by, joined_at, removed_by, removed_at, remove_reason, metadata, created_at, updated_at
`

type UpsertResidentSocietyMemberParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	UserID    int64  `db:"user_id" json:"user_id"`
	InvitedBy *int64 `db:"invited_by" json:"invited_by"`
}

func (q *Queries) UpsertResidentSocietyMember(ctx context.Context, arg UpsertResidentSocietyMemberParams) (SocietyMember, error) {
	row := q.db.QueryRow(ctx, upsertResidentSocietyMember, arg.SocietyID, arg.UserID, arg.InvitedBy)
	var i SocietyMember
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.RemovedBy,
		&i.RemovedAt,
		&i.RemoveReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
