// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSubscription = `-- name: ActivateSubscription :one
UPDATE society_subscriptions
SET status = 'active', starts_at = $2, ends_at = $3, activated_by = $4, activated_at = NOW(),
    cancelled_at = NULL, cancelled_by = NULL, cancellation_reason = NULL, expired_at = NULL,
    metadata = COALESCE($5, metadata), updated_at = NOW()
WHERE id = $1 AND status IN ('pending', 'trial', 'expired')
RETURNING id, society_id, plan_id, status, starts_at, ends_at, trial_ends_at, plan_name, plan_code, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, activated_at, activated_by, expired_at, cancelled_at, cancelled_by, cancellation_reason, metadata, created_by, created_at, updated_at
`

type ActivateSubscriptionParams struct {
	ID          int64              `db:"id" json:"id"`
	StartsAt    pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt      pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	ActivatedBy *int64             `db:"activated_by" json:"activated_by"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
}

func (q *Queries) ActivateSubscription(ctx context.Context, arg ActivateSubscriptionParams) (SocietySubscription, error) {
	row := q.db.QueryRow(ctx, activateSubscription,
		arg.ID,
		arg.StartsAt,
		arg.EndsAt,
		arg.ActivatedBy,
		arg.Metadata,
	)
	var i SocietySubscription
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.TrialEndsAt,
		&i.PlanName,
		&i.PlanCode,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelSubscription = `-- name: CancelSubscription :one
UPDATE society_subscriptions
SET status = 'cancelled', cancelled_by = $2, cancelled_at = NOW(), cancellation_reason = $3,
    metadata = COALESCE($4, metadata), updated_at = NOW()
WHERE id = $1 AND status != 'cancelled'
RETURNING id, society_id, plan_id, status, starts_at, ends_at, trial_ends_at, plan_name, plan_code, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, activated_at, activated_by, expired_at, cancelled_at, cancelled_by, cancellation_reason, metadata, created_by, created_at, updated_at
`

type CancelSubscriptionParams struct {
	ID                 int64   `db:"id" json:"id"`
	CancelledBy        *int64  `db:"cancelled_by" json:"cancelled_by"`
	CancellationReason *string `db:"cancellation_reason" json:"cancellation_reason"`
	Metadata           []byte  `db:"metadata" json:"metadata"`
}

func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) (SocietySubscription, error) {
	row := q.db.QueryRow(ctx, cancelSubscription,
		arg.ID,
		arg.CancelledBy,
		arg.CancellationReason,
		arg.Metadata,
	)
	var i SocietySubscription
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.TrialEndsAt,
		&i.PlanName,
		&i.PlanCode,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const changeSubscriptionPlan = `-- name: ChangeSubscriptionPlan :one
UPDATE society_subscriptions ss
SET plan_id = p.id,
    plan_name = p.name,
    plan_code = p.code,
    price_amount_paise = p.price_amount_paise,
    currency = p.currency,
    billing_cycle = p.billing_cycle,
    max_flats = p.max_flats,
    max_admins = p.max_admins,
    max_staff = p.max_staff,
    max_residents = p.max_residents,
    features = p.features,
    updated_at = NOW()
FROM plans p
WHERE ss.id = $1 AND p.id = $2 AND p.is_active = TRUE
RETURNING ss.id, ss.society_id, ss.plan_id, ss.status, ss.starts_at, ss.ends_at, ss.trial_ends_at, ss.plan_name, ss.plan_code, ss.price_amount_paise, ss.currency, ss.billing_cycle, ss.max_flats, ss.max_admins, ss.max_staff, ss.max_residents, ss.features, ss.activated_at, ss.activated_by, ss.expired_at, ss.cancelled_at, ss.cancelled_by, ss.cancellation_reason, ss.metadata, ss.created_by, ss.created_at, ss.updated_at
`

type ChangeSubscriptionPlanParams struct {
	ID   int64 `db:"id" json:"id"`
	ID_2 int64 `db:"id_2" json:"id_2"`
}

func (q *Queries) ChangeSubscriptionPlan(ctx context.Context, arg ChangeSubscriptionPlanParams) (SocietySubscription, error) {
	row := q.db.QueryRow(ctx, changeSubscriptionPlan, arg.ID, arg.ID_2)
	var i SocietySubscription
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.TrialEndsAt,
		&i.PlanName,
		&i.PlanCode,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveAdminsForQuota = `-- name: CountActiveAdminsForQuota :one
SELECT COUNT(*)
FROM society_members
WHERE society_id = $1 AND status = 'active' AND role IN ('admin', 'owner')
`

func (q *Queries) CountActiveAdminsForQuota(ctx context.Context, societyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdminsForQuota, societyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveFlatsForQuota = `-- name: CountActiveFlatsForQuota :one
SELECT COUNT(*)
FROM flats
WHERE society_id = $1 AND is_active = TRUE
`

func (q *Queries) CountActiveFlatsForQuota(ctx context.Context, societyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveFlatsForQuota, societyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveResidentsForQuota = `-- name: CountActiveResidentsForQuota :one
SELECT COUNT(*)
FROM society_members
WHERE society_id = $1 AND status = 'active' AND role = 'resident'
`

func (q *Queries) CountActiveResidentsForQuota(ctx context.Context, societyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveResidentsForQuota, societyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveStaffForQuota = `-- name: CountActiveStaffForQuota :one
SELECT COUNT(*)
FROM society_members
WHERE society_id = $1 AND status = 'active' AND role = 'staff'
`

func (q *Queries) CountActiveStaffForQuota(ctx context.Context, societyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveStaffForQuota, societyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPendingSubscription = `-- name: CreatePendingSubscription :one
INSERT INTO society_subscriptions (
    society_id, plan_id, status, plan_name, plan_code, price_amount_paise, currency,
    billing_cycle, max_flats, max_admins, max_staff, max_residents, features, metadata, created_by
)
SELECT
    $1::bigint AS society_id,
    p.id AS plan_id,
    'pending'::subscription_status AS status,
    p.name AS plan_name,
    p.code AS plan_code,
    p.price_amount_paise AS price_amount_paise,
    p.currency AS currency,
    p.billing_cycle, p.max_flats, p.max_admins, p.max_staff, p.max_residents, p.features,
    COALESCE($2, '{}'::jsonb) AS metadata,
    $3::bigint AS created_by
FROM plans p
WHERE p.id = $4::bigint AND p.is_active = TRUE
RETURNING id, society_id, plan_id, status, starts_at, ends_at, trial_ends_at, plan_name, plan_code, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, activated_at, activated_by, expired_at, cancelled_at, cancelled_by, cancellation_reason, metadata, created_by, created_at, updated_at
`

type CreatePendingSubscriptionParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	Metadata  []byte `db:"metadata" json:"metadata"`
	CreatedBy int64  `db:"created_by" json:"created_by"`
	PlanID    int64  `db:"plan_id" json:"plan_id"`
}

func (q *Queries) CreatePendingSubscription(ctx context.Context, arg CreatePendingSubscriptionParams) (SocietySubscription, error) {
	row := q.db.QueryRow(ctx, createPendingSubscription,
		arg.SocietyID,
		arg.Metadata,
		arg.CreatedBy,
		arg.PlanID,
	)
	var i SocietySubscription
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.TrialEndsAt,
		&i.PlanName,
		&i.PlanCode,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrialSubscription = `-- name: CreateTrialSubscription :one
INSERT INTO society_subscriptions (
    society_id, plan_id, status, starts_at, ends_at, trial_ends_at,
    plan_name, plan_code, price_amount_paise, currency, billing_cycle,
    max_flats, max_admins, max_staff, max_residents, features, metadata, created_by
)
SELECT
    $1::bigint AS society_id,
    p.id AS plan_id,
    'trial'::subscription_status AS status,
    $2::timestamptz AS starts_at,
    $3::timestamptz AS ends_at,
    $4::timestamptz AS trial_ends_at,
    p.name, p.code, p.price_amount_paise, p.currency, p.billing_cycle,
    p.max_flats, p.max_admins, p.max_staff, p.max_residents, p.features,
    COALESCE($5, '{}'::jsonb) AS metadata,
    $6::bigint AS created_by
FROM plans p
WHERE p.id = $7::bigint AND p.is_active = TRUE
RETURNING id, society_id, plan_id, status, starts_at, ends_at, trial_ends_at, plan_name, plan_code, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, activated_at, activated_by, expired_at, cancelled_at, cancelled_by, cancellation_reason, metadata, created_by, created_at, updated_at
`

type CreateTrialSubscriptionParams struct {
	SocietyID   int64              `db:"society_id" json:"society_id"`
	StartsAt    pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt      pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	TrialEndsAt pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedBy   int64              `db:"created_by" json:"created_by"`
	PlanID      int64              `db:"plan_id" json:"plan_id"`
}

func (q *Queries) CreateTrialSubscription(ctx context.Context, arg CreateTrialSubscriptionParams) (SocietySubscription, error) {
	row := q.db.QueryRow(ctx, createTrialSubscription,
		arg.SocietyID,
		arg.StartsAt,
		arg.EndsAt,
		arg.TrialEndsAt,
		arg.Metadata,
		arg.CreatedBy,
		arg.PlanID,
	)
	var i SocietySubscription
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.TrialEndsAt,
		&i.PlanName,
		&i.PlanCode,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireSubscription = `-- name: ExpireSubscription :one
UPDATE society_subscriptions
SET status = 'expired', expired_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status IN ('trial', 'active')
RETURNING id, society_id, plan_id, status, starts_at, ends_at, trial_ends_at, plan_name, plan_code, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, activated_at, activated_by, expired_at, cancelled_at, cancelled_by, cancellation_reason, metadata, created_by, created_at, updated_at
`

func (q *Queries) ExpireSubscription(ctx context.Context, id int64) (SocietySubscription, error) {
	row := q.db.QueryRow(ctx, expireSubscription, id)
	var i SocietySubscription
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.TrialEndsAt,
		&i.PlanName,
		&i.PlanCode,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSubscriptionForUpdate = `-- name: GetActiveSubscriptionForUpdate :one
SELECT id, society_id, plan_id, status, starts_at, ends_at, trial_ends_at, plan_name, plan_code, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, activated_at, activated_by, expired_at, cancelled_at, cancelled_by, cancellation_reason, metadata, created_by, created_at, updated_at
FROM society_subscriptions
WHERE society_id = $1::bigint
  AND status IN ('trial', 'active')
  AND (ends_at IS NULL OR ends_at > NOW())
ORDER BY id DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetActiveSubscriptionForUpdate(ctx context.Context, societyID int64) (SocietySubscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionForUpdate, societyID)
	var i SocietySubscription
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.TrialEndsAt,
		&i.PlanName,
		&i.PlanCode,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT
    ss.id, ss.society_id, ss.plan_id, ss.status, ss.starts_at, ss.ends_at, ss.trial_ends_at, ss.plan_name, ss.plan_code, ss.price_amount_paise, ss.currency, ss.billing_cycle, ss.max_flats, ss.max_admins, ss.max_staff, ss.max_residents, ss.features, ss.activated_at, ss.activated_by, ss.expired_at, ss.cancelled_at, ss.cancelled_by, ss.cancellation_reason, ss.metadata, ss.created_by, ss.created_at, ss.updated_at,
    s.name AS society_name,
    s.society_code AS society_code,
    p.name AS current_plan_name,
    p.code AS current_plan_code
FROM society_subscriptions ss
JOIN societies s ON s.id = ss.society_id
LEFT JOIN plans p ON p.id = ss.plan_id
LEFT JOIN users created_user ON created_user.id = ss.created_by
LEFT JOIN users activated_user ON activated_user.id = ss.activated_by
LEFT JOIN users cancelled_user ON cancelled_user.id = ss.cancelled_by
WHERE ($1::bigint IS NULL OR ss.id = $1::bigint)
  AND ($2::bigint IS NULL OR ss.society_id = $2::bigint)
  AND ($3::bigint IS NULL OR ss.plan_id = $3::bigint)
  AND ($4::subscription_status IS NULL OR ss.status = $4::subscription_status)
  AND ($5::text IS NULL OR ss.plan_code = $5::text)
  AND ($6::billing_cycle IS NULL OR ss.billing_cycle = $6::billing_cycle)
  AND (
      $7::bool IS NULL
      OR $7::bool = FALSE
      OR (ss.status IN ('trial', 'active') AND (ss.ends_at IS NULL OR ss.ends_at > NOW()))
  )
  AND ($8::timestamptz IS NULL OR ss.starts_at >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR ss.starts_at <= $9::timestamptz)
  AND ($10::timestamptz IS NULL OR ss.ends_at >= $10::timestamptz)
  AND ($11::timestamptz IS NULL OR ss.ends_at <= $11::timestamptz)
  AND ($12::timestamptz IS NULL OR ss.ends_at <= $12::timestamptz)
  AND (
      $13::bool IS NULL
      OR $13::bool = FALSE
      OR (ss.ends_at IS NOT NULL AND ss.ends_at <= NOW())
  )
  AND (
      COALESCE($14::text, '') = ''
      OR (
          COALESCE($15::text, 'all') IN ('', 'all', 'society')
          AND (
              s.name ILIKE '%' || $14::text || '%'
              OR s.society_code ILIKE '%' || $14::text || '%'
          )
      )
      OR (
          COALESCE($15::text, 'all') IN ('', 'all', 'plan')
          AND (
              ss.plan_name ILIKE '%' || $14::text || '%'
              OR ss.plan_code ILIKE '%' || $14::text || '%'
          )
      )
      OR (
          COALESCE($15::text, 'all') IN ('', 'all', 'action_user')
          AND (
              COALESCE(created_user.full_name, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(created_user.email, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(created_user.phone_number, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(activated_user.full_name, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(activated_user.email, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(activated_user.phone_number, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(cancelled_user.full_name, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(cancelled_user.email, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(cancelled_user.phone_number, '') ILIKE '%' || $14::text || '%'
          )
      )
      OR (
          COALESCE($15::text, 'all') IN ('', 'all', 'resident_member')
          AND EXISTS (
              SELECT 1
              FROM society_members sm
              JOIN users member_user ON member_user.id = sm.user_id
              WHERE sm.society_id = ss.society_id
                AND sm.status != 'removed'
                AND (
                    member_user.full_name ILIKE '%' || $14::text || '%'
                    OR COALESCE(member_user.email, '') ILIKE '%' || $14::text || '%'
                    OR COALESCE(member_user.phone_number, '') ILIKE '%' || $14::text || '%'
                )
          )
      )
      OR (
          COALESCE($15::text, 'all') IN ('', 'all')
          AND ss.status::text ILIKE '%' || $14::text || '%'
      )
  )
ORDER BY ss.id DESC
LIMIT 1
`

type GetSubscriptionParams struct {
	ID             *int64              `db:"id" json:"id"`
	SocietyID      *int64              `db:"society_id" json:"society_id"`
	PlanID         *int64              `db:"plan_id" json:"plan_id"`
	Status         *SubscriptionStatus `db:"status" json:"status"`
	PlanCode       *string             `db:"plan_code" json:"plan_code"`
	BillingCycle   *BillingCycle       `db:"billing_cycle" json:"billing_cycle"`
	IsActiveOnly   *bool               `db:"is_active_only" json:"is_active_only"`
	StartsAfter    pgtype.Timestamptz  `db:"starts_after" json:"starts_after"`
	StartsBefore   pgtype.Timestamptz  `db:"starts_before" json:"starts_before"`
	EndsAfter      pgtype.Timestamptz  `db:"ends_after" json:"ends_after"`
	EndsBefore     pgtype.Timestamptz  `db:"ends_before" json:"ends_before"`
	ExpiringBefore pgtype.Timestamptz  `db:"expiring_before" json:"expiring_before"`
	ExpiredOnly    *bool               `db:"expired_only" json:"expired_only"`
	Search         *string             `db:"search" json:"search"`
	SearchMode     *string             `db:"search_mode" json:"search_mode"`
}

type GetSubscriptionRow struct {
	ID                 int64              `db:"id" json:"id"`
	SocietyID          int64              `db:"society_id" json:"society_id"`
	PlanID             *int64             `db:"plan_id" json:"plan_id"`
	Status             SubscriptionStatus `db:"status" json:"status"`
	StartsAt           pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt             pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	TrialEndsAt        pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	PlanName           string             `db:"plan_name" json:"plan_name"`
	PlanCode           string             `db:"plan_code" json:"plan_code"`
	PriceAmountPaise   int64              `db:"price_amount_paise" json:"price_amount_paise"`
	Currency           string             `db:"currency" json:"currency"`
	BillingCycle       BillingCycle       `db:"billing_cycle" json:"billing_cycle"`
	MaxFlats           int32              `db:"max_flats" json:"max_flats"`
	MaxAdmins          int32              `db:"max_admins" json:"max_admins"`
	MaxStaff           int32              `db:"max_staff" json:"max_staff"`
	MaxResidents       int32              `db:"max_residents" json:"max_residents"`
	Features           []byte             `db:"features" json:"features"`
	ActivatedAt        pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	ActivatedBy        *int64             `db:"activated_by" json:"activated_by"`
	ExpiredAt          pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	CancelledAt        pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CancelledBy        *int64             `db:"cancelled_by" json:"cancelled_by"`
	CancellationReason *string            `db:"cancellation_reason" json:"cancellation_reason"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedBy          *int64             `db:"created_by" json:"created_by"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SocietyName        string             `db:"society_name" json:"society_name"`
	SocietyCode        string             `db:"society_code" json:"society_code"`
	CurrentPlanName    *string            `db:"current_plan_name" json:"current_plan_name"`
	CurrentPlanCode    *string            `db:"current_plan_code" json:"current_plan_code"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (GetSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getSubscription,
		arg.ID,
		arg.SocietyID,
		arg.PlanID,
		arg.Status,
		arg.PlanCode,
		arg.BillingCycle,
		arg.IsActiveOnly,
		arg.StartsAfter,
		arg.StartsBefore,
		arg.EndsAfter,
		arg.EndsBefore,
		arg.ExpiringBefore,
		arg.ExpiredOnly,
		arg.Search,
		arg.SearchMode,
	)
	var i GetSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.TrialEndsAt,
		&i.PlanName,
		&i.PlanCode,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SocietyName,
		&i.SocietyCode,
		&i.CurrentPlanName,
		&i.CurrentPlanCode,
	)
	return i, err
}

const getSubscriptionStats = `-- name: GetSubscriptionStats :one
SELECT
    COUNT(*) AS total_subscriptions,
    COUNT(*) FILTER (WHERE status = 'pending') AS pending_subscriptions,
    COUNT(*) FILTER (WHERE status = 'trial') AS trial_subscriptions,
    COUNT(*) FILTER (WHERE status = 'active') AS active_subscriptions,
    COUNT(*) FILTER (WHERE status = 'expired') AS expired_subscriptions,
    COUNT(*) FILTER (WHERE status = 'cancelled') AS cancelled_subscriptions
FROM society_subscriptions ss
WHERE ($1::bigint IS NULL OR ss.society_id = $1::bigint)
  AND ($2::bigint IS NULL OR ss.plan_id = $2::bigint)
  AND ($3::subscription_status IS NULL OR ss.status = $3::subscription_status)
  AND ($4::text IS NULL OR ss.plan_code = $4::text)
  AND ($5::billing_cycle IS NULL OR ss.billing_cycle = $5::billing_cycle)
`

type GetSubscriptionStatsParams struct {
	SocietyID    *int64              `db:"society_id" json:"society_id"`
	PlanID       *int64              `db:"plan_id" json:"plan_id"`
	Status       *SubscriptionStatus `db:"status" json:"status"`
	PlanCode     *string             `db:"plan_code" json:"plan_code"`
	BillingCycle *BillingCycle       `db:"billing_cycle" json:"billing_cycle"`
}

type GetSubscriptionStatsRow struct {
	TotalSubscriptions     int64 `db:"total_subscriptions" json:"total_subscriptions"`
	PendingSubscriptions   int64 `db:"pending_subscriptions" json:"pending_subscriptions"`
	TrialSubscriptions     int64 `db:"trial_subscriptions" json:"trial_subscriptions"`
	ActiveSubscriptions    int64 `db:"active_subscriptions" json:"active_subscriptions"`
	ExpiredSubscriptions   int64 `db:"expired_subscriptions" json:"expired_subscriptions"`
	CancelledSubscriptions int64 `db:"cancelled_subscriptions" json:"cancelled_subscriptions"`
}

func (q *Queries) GetSubscriptionStats(ctx context.Context, arg GetSubscriptionStatsParams) (GetSubscriptionStatsRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionStats,
		arg.SocietyID,
		arg.PlanID,
		arg.Status,
		arg.PlanCode,
		arg.BillingCycle,
	)
	var i GetSubscriptionStatsRow
	err := row.Scan(
		&i.TotalSubscriptions,
		&i.PendingSubscriptions,
		&i.TrialSubscriptions,
		&i.ActiveSubscriptions,
		&i.ExpiredSubscriptions,
		&i.CancelledSubscriptions,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT
    ss.id, ss.society_id, ss.plan_id, ss.status, ss.starts_at, ss.ends_at, ss.trial_ends_at, ss.plan_name, ss.plan_code, ss.price_amount_paise, ss.currency, ss.billing_cycle, ss.max_flats, ss.max_admins, ss.max_staff, ss.max_residents, ss.features, ss.activated_at, ss.activated_by, ss.expired_at, ss.cancelled_at, ss.cancelled_by, ss.cancellation_reason, ss.metadata, ss.created_by, ss.created_at, ss.updated_at,
    s.name AS society_name,
    s.society_code AS society_code,
    p.name AS current_plan_name,
    p.code AS current_plan_code
FROM society_subscriptions ss
JOIN societies s ON s.id = ss.society_id
LEFT JOIN plans p ON p.id = ss.plan_id
LEFT JOIN users created_user ON created_user.id = ss.created_by
LEFT JOIN users activated_user ON activated_user.id = ss.activated_by
LEFT JOIN users cancelled_user ON cancelled_user.id = ss.cancelled_by
WHERE ($1::bigint IS NULL OR ss.id = $1::bigint)
  AND ($2::bigint IS NULL OR ss.society_id = $2::bigint)
  AND ($3::bigint IS NULL OR ss.plan_id = $3::bigint)
  AND ($4::subscription_status IS NULL OR ss.status = $4::subscription_status)
  AND ($5::text IS NULL OR ss.plan_code = $5::text)
  AND ($6::billing_cycle IS NULL OR ss.billing_cycle = $6::billing_cycle)
  AND (
      $7::bool IS NULL
      OR $7::bool = FALSE
      OR (ss.status IN ('trial', 'active') AND (ss.ends_at IS NULL OR ss.ends_at > NOW()))
  )
  AND ($8::timestamptz IS NULL OR ss.starts_at >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR ss.starts_at <= $9::timestamptz)
  AND ($10::timestamptz IS NULL OR ss.ends_at >= $10::timestamptz)
  AND ($11::timestamptz IS NULL OR ss.ends_at <= $11::timestamptz)
  AND ($12::timestamptz IS NULL OR ss.ends_at <= $12::timestamptz)
  AND (
      $13::bool IS NULL
      OR $13::bool = FALSE
      OR (ss.ends_at IS NOT NULL AND ss.ends_at <= NOW())
  )
  AND (
      COALESCE($14::text, '') = ''
      OR (
          COALESCE($15::text, 'all') IN ('', 'all', 'society')
          AND (
              s.name ILIKE '%' || $14::text || '%'
              OR s.society_code ILIKE '%' || $14::text || '%'
          )
      )
      OR (
          COALESCE($15::text, 'all') IN ('', 'all', 'plan')
          AND (
              ss.plan_name ILIKE '%' || $14::text || '%'
              OR ss.plan_code ILIKE '%' || $14::text || '%'
          )
      )
      OR (
          COALESCE($15::text, 'all') IN ('', 'all', 'action_user')
          AND (
              COALESCE(created_user.full_name, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(created_user.email, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(created_user.phone_number, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(activated_user.full_name, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(activated_user.email, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(activated_user.phone_number, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(cancelled_user.full_name, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(cancelled_user.email, '') ILIKE '%' || $14::text || '%'
              OR COALESCE(cancelled_user.phone_number, '') ILIKE '%' || $14::text || '%'
          )
      )
      OR (
          COALESCE($15::text, 'all') IN ('', 'all', 'resident_member')
          AND EXISTS (
              SELECT 1
              FROM society_members sm
              JOIN users member_user ON member_user.id = sm.user_id
              WHERE sm.society_id = ss.society_id
                AND sm.status != 'removed'
                AND (
                    member_user.full_name ILIKE '%' || $14::text || '%'
                    OR COALESCE(member_user.email, '') ILIKE '%' || $14::text || '%'
                    OR COALESCE(member_user.phone_number, '') ILIKE '%' || $14::text || '%'
                )
          )
      )
      OR (
          COALESCE($15::text, 'all') IN ('', 'all')
          AND ss.status::text ILIKE '%' || $14::text || '%'
      )
  )
ORDER BY ss.created_at DESC
LIMIT $17 OFFSET $16
`

type ListSubscriptionsParams struct {
	ID             *int64              `db:"id" json:"id"`
	SocietyID      *int64              `db:"society_id" json:"society_id"`
	PlanID         *int64              `db:"plan_id" json:"plan_id"`
	Status         *SubscriptionStatus `db:"status" json:"status"`
	PlanCode       *string             `db:"plan_code" json:"plan_code"`
	BillingCycle   *BillingCycle       `db:"billing_cycle" json:"billing_cycle"`
	IsActiveOnly   *bool               `db:"is_active_only" json:"is_active_only"`
	StartsAfter    pgtype.Timestamptz  `db:"starts_after" json:"starts_after"`
	StartsBefore   pgtype.Timestamptz  `db:"starts_before" json:"starts_before"`
	EndsAfter      pgtype.Timestamptz  `db:"ends_after" json:"ends_after"`
	EndsBefore     pgtype.Timestamptz  `db:"ends_before" json:"ends_before"`
	ExpiringBefore pgtype.Timestamptz  `db:"expiring_before" json:"expiring_before"`
	ExpiredOnly    *bool               `db:"expired_only" json:"expired_only"`
	Search         *string             `db:"search" json:"search"`
	SearchMode     *string             `db:"search_mode" json:"search_mode"`
	Offset         int32               `db:"offset" json:"offset"`
	Limit          int32               `db:"limit" json:"limit"`
}

type ListSubscriptionsRow struct {
	ID                 int64              `db:"id" json:"id"`
	SocietyID          int64              `db:"society_id" json:"society_id"`
	PlanID             *int64             `db:"plan_id" json:"plan_id"`
	Status             SubscriptionStatus `db:"status" json:"status"`
	StartsAt           pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt             pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	TrialEndsAt        pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	PlanName           string             `db:"plan_name" json:"plan_name"`
	PlanCode           string             `db:"plan_code" json:"plan_code"`
	PriceAmountPaise   int64              `db:"price_amount_paise" json:"price_amount_paise"`
	Currency           string             `db:"currency" json:"currency"`
	BillingCycle       BillingCycle       `db:"billing_cycle" json:"billing_cycle"`
	MaxFlats           int32              `db:"max_flats" json:"max_flats"`
	MaxAdmins          int32              `db:"max_admins" json:"max_admins"`
	MaxStaff           int32              `db:"max_staff" json:"max_staff"`
	MaxResidents       int32              `db:"max_residents" json:"max_residents"`
	Features           []byte             `db:"features" json:"features"`
	ActivatedAt        pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	ActivatedBy        *int64             `db:"activated_by" json:"activated_by"`
	ExpiredAt          pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	CancelledAt        pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CancelledBy        *int64             `db:"cancelled_by" json:"cancelled_by"`
	CancellationReason *string            `db:"cancellation_reason" json:"cancellation_reason"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedBy          *int64             `db:"created_by" json:"created_by"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SocietyName        string             `db:"society_name" json:"society_name"`
	SocietyCode        string             `db:"society_code" json:"society_code"`
	CurrentPlanName    *string            `db:"current_plan_name" json:"current_plan_name"`
	CurrentPlanCode    *string            `db:"current_plan_code" json:"current_plan_code"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]ListSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptions,
		arg.ID,
		arg.SocietyID,
		arg.PlanID,
		arg.Status,
		arg.PlanCode,
		arg.BillingCycle,
		arg.IsActiveOnly,
		arg.StartsAfter,
		arg.StartsBefore,
		arg.EndsAfter,
		arg.EndsBefore,
		arg.ExpiringBefore,
		arg.ExpiredOnly,
		arg.Search,
		arg.SearchMode,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsRow{}
	for rows.Next() {
		var i ListSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.PlanID,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.TrialEndsAt,
			&i.PlanName,
			&i.PlanCode,
			&i.PriceAmountPaise,
			&i.Currency,
			&i.BillingCycle,
			&i.MaxFlats,
			&i.MaxAdmins,
			&i.MaxStaff,
			&i.MaxResidents,
			&i.Features,
			&i.ActivatedAt,
			&i.ActivatedBy,
			&i.ExpiredAt,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancellationReason,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SocietyName,
			&i.SocietyCode,
			&i.CurrentPlanName,
			&i.CurrentPlanCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewSubscription = `-- name: RenewSubscription :one
UPDATE society_subscriptions
SET status = 'active', starts_at = $2, ends_at = $3, activated_by = $4, activated_at = NOW(),
    expired_at = NULL, metadata = COALESCE($5, metadata), updated_at = NOW()
WHERE id = $1 AND status IN ('active', 'trial', 'expired')
RETURNING id, society_id, plan_id, status, starts_at, ends_at, trial_ends_at, plan_name, plan_code, price_amount_paise, currency, billing_cycle, max_flats, max_admins, max_staff, max_residents, features, activated_at, activated_by, expired_at, cancelled_at, cancelled_by, cancellation_reason, metadata, created_by, created_at, updated_at
`

type RenewSubscriptionParams struct {
	ID          int64              `db:"id" json:"id"`
	StartsAt    pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt      pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	ActivatedBy *int64             `db:"activated_by" json:"activated_by"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
}

func (q *Queries) RenewSubscription(ctx context.Context, arg RenewSubscriptionParams) (SocietySubscription, error) {
	row := q.db.QueryRow(ctx, renewSubscription,
		arg.ID,
		arg.StartsAt,
		arg.EndsAt,
		arg.ActivatedBy,
		arg.Metadata,
	)
	var i SocietySubscription
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.TrialEndsAt,
		&i.PlanName,
		&i.PlanCode,
		&i.PriceAmountPaise,
		&i.Currency,
		&i.BillingCycle,
		&i.MaxFlats,
		&i.MaxAdmins,
		&i.MaxStaff,
		&i.MaxResidents,
		&i.Features,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
