// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name,
    last_name,
    full_name,
    email,
    phone_number,
    password_hash,
    auth_provider,
    global_role,
    email_verified,
    phone_verified,
    is_active,
    is_blocked,
    timezone,
    language,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::auth_provider,
    $8::global_role,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING
    id,
    first_name,
    last_name,
    full_name,
    email,
    phone_number,
    password_hash,
    auth_provider,
    provider_id,
    global_role,
    email_verified,
    phone_verified,
    is_active,
    is_blocked,
    blocked_reason,
    avatar_url,
    date_of_birth,
    gender,
    timezone,
    language,
    last_login_at,
    password_changed_at,
    deleted_at,
    metadata,
    created_at,
    updated_at
`

type CreateUserParams struct {
	FirstName     *string      `db:"first_name" json:"first_name"`
	LastName      *string      `db:"last_name" json:"last_name"`
	FullName      string       `db:"full_name" json:"full_name"`
	Email         *string      `db:"email" json:"email"`
	PhoneNumber   *string      `db:"phone_number" json:"phone_number"`
	PasswordHash  *string      `db:"password_hash" json:"password_hash"`
	AuthProvider  AuthProvider `db:"auth_provider" json:"auth_provider"`
	GlobalRole    GlobalRole   `db:"global_role" json:"global_role"`
	EmailVerified bool         `db:"email_verified" json:"email_verified"`
	PhoneVerified bool         `db:"phone_verified" json:"phone_verified"`
	IsActive      bool         `db:"is_active" json:"is_active"`
	IsBlocked     bool         `db:"is_blocked" json:"is_blocked"`
	Timezone      string       `db:"timezone" json:"timezone"`
	Language      string       `db:"language" json:"language"`
	Metadata      []byte       `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.AuthProvider,
		arg.GlobalRole,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.IsActive,
		arg.IsBlocked,
		arg.Timezone,
		arg.Language,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.ProviderID,
		&i.GlobalRole,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.IsActive,
		&i.IsBlocked,
		&i.BlockedReason,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Timezone,
		&i.Language,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE LOWER(email) = LOWER($1)
      AND deleted_at IS NULL
)
`

func (q *Queries) EmailExists(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    first_name,
    last_name,
    full_name,
    email,
    phone_number,
    password_hash,
    auth_provider,
    provider_id,
    global_role,
    email_verified,
    phone_verified,
    is_active,
    is_blocked,
    blocked_reason,
    avatar_url,
    date_of_birth,
    gender,
    timezone,
    language,
    last_login_at,
    password_changed_at,
    deleted_at,
    metadata,
    created_at,
    updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.ProviderID,
		&i.GlobalRole,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.IsActive,
		&i.IsBlocked,
		&i.BlockedReason,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Timezone,
		&i.Language,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    first_name,
    last_name,
    full_name,
    email,
    phone_number,
    password_hash,
    auth_provider,
    provider_id,
    global_role,
    email_verified,
    phone_verified,
    is_active,
    is_blocked,
    blocked_reason,
    avatar_url,
    date_of_birth,
    gender,
    timezone,
    language,
    last_login_at,
    password_changed_at,
    deleted_at,
    metadata,
    created_at,
    updated_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.ProviderID,
		&i.GlobalRole,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.IsActive,
		&i.IsBlocked,
		&i.BlockedReason,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Timezone,
		&i.Language,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT
    id,
    first_name,
    last_name,
    full_name,
    email,
    phone_number,
    password_hash,
    auth_provider,
    provider_id,
    global_role,
    email_verified,
    phone_verified,
    is_active,
    is_blocked,
    blocked_reason,
    avatar_url,
    date_of_birth,
    gender,
    timezone,
    language,
    last_login_at,
    password_changed_at,
    deleted_at,
    metadata,
    created_at,
    updated_at
FROM users
WHERE phone_number = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.ProviderID,
		&i.GlobalRole,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.IsActive,
		&i.IsBlocked,
		&i.BlockedReason,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Timezone,
		&i.Language,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const phoneExists = `-- name: PhoneExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE phone_number = $1
      AND deleted_at IS NULL
)
`

func (q *Queries) PhoneExists(ctx context.Context, phoneNumber *string) (bool, error) {
	row := q.db.QueryRow(ctx, phoneExists, phoneNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET
    last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET
    password_hash = $2,
    password_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserPasswordHashParams struct {
	ID           int64   `db:"id" json:"id"`
	PasswordHash *string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
