// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_verifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserVerification = `-- name: CreateUserVerification :one
INSERT INTO user_verifications (
    user_id,
    purpose,
    target,
    otp_hash,
    attempts,
    max_attempts,
    is_used,
    expires_at
)
VALUES (
    $1,
    $2::verification_purpose,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    user_id,
    purpose,
    target,
    otp_hash,
    attempts,
    max_attempts,
    is_used,
    expires_at,
    used_at,
    created_at
`

type CreateUserVerificationParams struct {
	UserID      int64               `db:"user_id" json:"user_id"`
	Purpose     VerificationPurpose `db:"purpose" json:"purpose"`
	Target      string              `db:"target" json:"target"`
	OtpHash     string              `db:"otp_hash" json:"otp_hash"`
	Attempts    int32               `db:"attempts" json:"attempts"`
	MaxAttempts int32               `db:"max_attempts" json:"max_attempts"`
	IsUsed      bool                `db:"is_used" json:"is_used"`
	ExpiresAt   pgtype.Timestamptz  `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateUserVerification(ctx context.Context, arg CreateUserVerificationParams) (UserVerification, error) {
	row := q.db.QueryRow(ctx, createUserVerification,
		arg.UserID,
		arg.Purpose,
		arg.Target,
		arg.OtpHash,
		arg.Attempts,
		arg.MaxAttempts,
		arg.IsUsed,
		arg.ExpiresAt,
	)
	var i UserVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.OtpHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActiveUserVerificationByPurpose = `-- name: DeleteActiveUserVerificationByPurpose :exec
UPDATE user_verifications
SET is_used = true,
    used_at = NOW()
WHERE user_id = $1
  AND purpose = $2::verification_purpose
  AND target = $3
  AND is_used = false
`

type DeleteActiveUserVerificationByPurposeParams struct {
	UserID  int64               `db:"user_id" json:"user_id"`
	Purpose VerificationPurpose `db:"purpose" json:"purpose"`
	Target  string              `db:"target" json:"target"`
}

func (q *Queries) DeleteActiveUserVerificationByPurpose(ctx context.Context, arg DeleteActiveUserVerificationByPurposeParams) error {
	_, err := q.db.Exec(ctx, deleteActiveUserVerificationByPurpose, arg.UserID, arg.Purpose, arg.Target)
	return err
}

const deleteUsedOrExpiredUserVerifications = `-- name: DeleteUsedOrExpiredUserVerifications :exec
DELETE FROM user_verifications
WHERE is_used = TRUE
   OR expires_at < NOW()
`

func (q *Queries) DeleteUsedOrExpiredUserVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteUsedOrExpiredUserVerifications)
	return err
}

const getActiveUserVerification = `-- name: GetActiveUserVerification :one
SELECT
    id,
    user_id,
    purpose,
    target,
    otp_hash,
    attempts,
    max_attempts,
    is_used,
    expires_at,
    used_at,
    created_at
FROM user_verifications
WHERE user_id = $1
  AND purpose = $2::verification_purpose
  AND target = $3
  AND is_used = false
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveUserVerificationParams struct {
	UserID  int64               `db:"user_id" json:"user_id"`
	Purpose VerificationPurpose `db:"purpose" json:"purpose"`
	Target  string              `db:"target" json:"target"`
}

func (q *Queries) GetActiveUserVerification(ctx context.Context, arg GetActiveUserVerificationParams) (UserVerification, error) {
	row := q.db.QueryRow(ctx, getActiveUserVerification, arg.UserID, arg.Purpose, arg.Target)
	var i UserVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.OtpHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementUserVerificationAttempts = `-- name: IncrementUserVerificationAttempts :exec
UPDATE user_verifications
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementUserVerificationAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementUserVerificationAttempts, id)
	return err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET
    email_verified = TRUE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}

const markUserVerificationUsed = `-- name: MarkUserVerificationUsed :exec
UPDATE user_verifications
SET is_used = true,
    used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkUserVerificationUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markUserVerificationUsed, id)
	return err
}
