// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visitor_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSocietyFlatVisitorSettings = `-- name: CountSocietyFlatVisitorSettings :one
SELECT COUNT(*)
FROM flat_visitor_settings fvs
JOIN flats f ON f.id = fvs.flat_id
WHERE fvs.society_id = $1
  AND ($2::bigint IS NULL OR fvs.flat_id = $2::bigint)
  AND ($3::text IS NULL OR f.block = $3::text)
  AND ($4::visitor_purpose IS NULL OR fvs.purpose = $4::visitor_purpose)
`

type CountSocietyFlatVisitorSettingsParams struct {
	SocietyID int64           `db:"society_id" json:"society_id"`
	FlatID    *int64          `db:"flat_id" json:"flat_id"`
	Block     *string         `db:"block" json:"block"`
	Purpose   *VisitorPurpose `db:"purpose" json:"purpose"`
}

func (q *Queries) CountSocietyFlatVisitorSettings(ctx context.Context, arg CountSocietyFlatVisitorSettingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSocietyFlatVisitorSettings,
		arg.SocietyID,
		arg.FlatID,
		arg.Block,
		arg.Purpose,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDefaultFlatVisitorSettings = `-- name: CreateDefaultFlatVisitorSettings :exec
INSERT INTO flat_visitor_settings (
    society_id,
    flat_id,
    purpose,
    approval_required,
    updated_by
)
VALUES
    ($1, $2, 'guest', TRUE, $3),
    ($1, $2, 'delivery', FALSE, $3),
    ($1, $2, 'cab', FALSE, $3),
    ($1, $2, 'service', TRUE, $3),
    ($1, $2, 'maintenance', FALSE, $3),
    ($1, $2, 'staff', TRUE, $3),
    ($1, $2, 'other', TRUE, $3)
ON CONFLICT (flat_id, purpose) DO NOTHING
`

type CreateDefaultFlatVisitorSettingsParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	FlatID    int64  `db:"flat_id" json:"flat_id"`
	UpdatedBy *int64 `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateDefaultFlatVisitorSettings(ctx context.Context, arg CreateDefaultFlatVisitorSettingsParams) error {
	_, err := q.db.Exec(ctx, createDefaultFlatVisitorSettings, arg.SocietyID, arg.FlatID, arg.UpdatedBy)
	return err
}

const createDefaultSocietyVisitorSettings = `-- name: CreateDefaultSocietyVisitorSettings :exec
INSERT INTO society_visitor_settings (society_id, updated_by)
VALUES ($1, $2)
ON CONFLICT (society_id) DO NOTHING
`

type CreateDefaultSocietyVisitorSettingsParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	UpdatedBy *int64 `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateDefaultSocietyVisitorSettings(ctx context.Context, arg CreateDefaultSocietyVisitorSettingsParams) error {
	_, err := q.db.Exec(ctx, createDefaultSocietyVisitorSettings, arg.SocietyID, arg.UpdatedBy)
	return err
}

const deleteFlatVisitorSettings = `-- name: DeleteFlatVisitorSettings :exec
DELETE FROM flat_visitor_settings
WHERE society_id = $1
  AND flat_id = $2
`

type DeleteFlatVisitorSettingsParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
}

func (q *Queries) DeleteFlatVisitorSettings(ctx context.Context, arg DeleteFlatVisitorSettingsParams) error {
	_, err := q.db.Exec(ctx, deleteFlatVisitorSettings, arg.SocietyID, arg.FlatID)
	return err
}

const getFlatVisitorPurposeSetting = `-- name: GetFlatVisitorPurposeSetting :one
SELECT id, society_id, flat_id, purpose, approval_required, default_visit_duration_minutes, is_enabled, metadata, updated_by, created_at, updated_at
FROM flat_visitor_settings
WHERE society_id = $1
  AND flat_id = $2
  AND purpose = $3
`

type GetFlatVisitorPurposeSettingParams struct {
	SocietyID int64          `db:"society_id" json:"society_id"`
	FlatID    int64          `db:"flat_id" json:"flat_id"`
	Purpose   VisitorPurpose `db:"purpose" json:"purpose"`
}

func (q *Queries) GetFlatVisitorPurposeSetting(ctx context.Context, arg GetFlatVisitorPurposeSettingParams) (FlatVisitorSetting, error) {
	row := q.db.QueryRow(ctx, getFlatVisitorPurposeSetting, arg.SocietyID, arg.FlatID, arg.Purpose)
	var i FlatVisitorSetting
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.Purpose,
		&i.ApprovalRequired,
		&i.DefaultVisitDurationMinutes,
		&i.IsEnabled,
		&i.Metadata,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSocietyVisitorSettings = `-- name: GetSocietyVisitorSettings :one
SELECT id, society_id, approval_mode, default_visit_duration_minutes, grace_period_minutes, qr_expiry_minutes, allow_resident_pre_approval, allow_public_qr_entry, allow_guard_entry, is_active, metadata, updated_by, created_at, updated_at, allow_guard_on_behalf_approval
FROM society_visitor_settings
WHERE society_id = $1
`

func (q *Queries) GetSocietyVisitorSettings(ctx context.Context, societyID int64) (SocietyVisitorSetting, error) {
	row := q.db.QueryRow(ctx, getSocietyVisitorSettings, societyID)
	var i SocietyVisitorSetting
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.ApprovalMode,
		&i.DefaultVisitDurationMinutes,
		&i.GracePeriodMinutes,
		&i.QrExpiryMinutes,
		&i.AllowResidentPreApproval,
		&i.AllowPublicQrEntry,
		&i.AllowGuardEntry,
		&i.IsActive,
		&i.Metadata,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllowGuardOnBehalfApproval,
	)
	return i, err
}

const listFlatVisitorSettings = `-- name: ListFlatVisitorSettings :many
SELECT id, society_id, flat_id, purpose, approval_required, default_visit_duration_minutes, is_enabled, metadata, updated_by, created_at, updated_at
FROM flat_visitor_settings
WHERE society_id = $1
  AND flat_id = $2
ORDER BY CASE purpose
    WHEN 'guest' THEN 1
    WHEN 'delivery' THEN 2
    WHEN 'cab' THEN 3
    WHEN 'service' THEN 4
    WHEN 'maintenance' THEN 5
    WHEN 'staff' THEN 6
    ELSE 7
END
`

type ListFlatVisitorSettingsParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
}

func (q *Queries) ListFlatVisitorSettings(ctx context.Context, arg ListFlatVisitorSettingsParams) ([]FlatVisitorSetting, error) {
	rows, err := q.db.Query(ctx, listFlatVisitorSettings, arg.SocietyID, arg.FlatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlatVisitorSetting{}
	for rows.Next() {
		var i FlatVisitorSetting
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.FlatID,
			&i.Purpose,
			&i.ApprovalRequired,
			&i.DefaultVisitDurationMinutes,
			&i.IsEnabled,
			&i.Metadata,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocietyFlatVisitorSettings = `-- name: ListSocietyFlatVisitorSettings :many
SELECT
    fvs.id, fvs.society_id, fvs.flat_id, fvs.purpose, fvs.approval_required, fvs.default_visit_duration_minutes, fvs.is_enabled, fvs.metadata, fvs.updated_by, fvs.created_at, fvs.updated_at,
    f.flat_number,
    f.block
FROM flat_visitor_settings fvs
JOIN flats f ON f.id = fvs.flat_id
WHERE fvs.society_id = $1
  AND ($2::bigint IS NULL OR fvs.flat_id = $2::bigint)
  AND ($3::text IS NULL OR f.block = $3::text)
  AND ($4::visitor_purpose IS NULL OR fvs.purpose = $4::visitor_purpose)
ORDER BY f.block NULLS LAST, f.flat_number, CASE fvs.purpose
    WHEN 'guest' THEN 1
    WHEN 'delivery' THEN 2
    WHEN 'cab' THEN 3
    WHEN 'service' THEN 4
    WHEN 'maintenance' THEN 5
    WHEN 'staff' THEN 6
    ELSE 7
END
LIMIT $6 OFFSET $5
`

type ListSocietyFlatVisitorSettingsParams struct {
	SocietyID int64           `db:"society_id" json:"society_id"`
	FlatID    *int64          `db:"flat_id" json:"flat_id"`
	Block     *string         `db:"block" json:"block"`
	Purpose   *VisitorPurpose `db:"purpose" json:"purpose"`
	Offset    int32           `db:"offset" json:"offset"`
	Limit     int32           `db:"limit" json:"limit"`
}

type ListSocietyFlatVisitorSettingsRow struct {
	ID                          int64              `db:"id" json:"id"`
	SocietyID                   int64              `db:"society_id" json:"society_id"`
	FlatID                      int64              `db:"flat_id" json:"flat_id"`
	Purpose                     VisitorPurpose     `db:"purpose" json:"purpose"`
	ApprovalRequired            bool               `db:"approval_required" json:"approval_required"`
	DefaultVisitDurationMinutes *int32             `db:"default_visit_duration_minutes" json:"default_visit_duration_minutes"`
	IsEnabled                   bool               `db:"is_enabled" json:"is_enabled"`
	Metadata                    []byte             `db:"metadata" json:"metadata"`
	UpdatedBy                   *int64             `db:"updated_by" json:"updated_by"`
	CreatedAt                   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FlatNumber                  string             `db:"flat_number" json:"flat_number"`
	Block                       *string            `db:"block" json:"block"`
}

func (q *Queries) ListSocietyFlatVisitorSettings(ctx context.Context, arg ListSocietyFlatVisitorSettingsParams) ([]ListSocietyFlatVisitorSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSocietyFlatVisitorSettings,
		arg.SocietyID,
		arg.FlatID,
		arg.Block,
		arg.Purpose,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocietyFlatVisitorSettingsRow{}
	for rows.Next() {
		var i ListSocietyFlatVisitorSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.FlatID,
			&i.Purpose,
			&i.ApprovalRequired,
			&i.DefaultVisitDurationMinutes,
			&i.IsEnabled,
			&i.Metadata,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FlatNumber,
			&i.Block,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlatVisitorPurposeSetting = `-- name: UpdateFlatVisitorPurposeSetting :one
UPDATE flat_visitor_settings
SET
    approval_required = COALESCE($1::boolean, approval_required),
    default_visit_duration_minutes = COALESCE($2::integer, default_visit_duration_minutes),
    is_enabled = COALESCE($3::boolean, is_enabled),
    updated_by = $4,
    updated_at = NOW()
WHERE society_id = $5
  AND flat_id = $6
  AND purpose = $7
RETURNING id, society_id, flat_id, purpose, approval_required, default_visit_duration_minutes, is_enabled, metadata, updated_by, created_at, updated_at
`

type UpdateFlatVisitorPurposeSettingParams struct {
	ApprovalRequired            *bool          `db:"approval_required" json:"approval_required"`
	DefaultVisitDurationMinutes *int32         `db:"default_visit_duration_minutes" json:"default_visit_duration_minutes"`
	IsEnabled                   *bool          `db:"is_enabled" json:"is_enabled"`
	UpdatedBy                   *int64         `db:"updated_by" json:"updated_by"`
	SocietyID                   int64          `db:"society_id" json:"society_id"`
	FlatID                      int64          `db:"flat_id" json:"flat_id"`
	Purpose                     VisitorPurpose `db:"purpose" json:"purpose"`
}

func (q *Queries) UpdateFlatVisitorPurposeSetting(ctx context.Context, arg UpdateFlatVisitorPurposeSettingParams) (FlatVisitorSetting, error) {
	row := q.db.QueryRow(ctx, updateFlatVisitorPurposeSetting,
		arg.ApprovalRequired,
		arg.DefaultVisitDurationMinutes,
		arg.IsEnabled,
		arg.UpdatedBy,
		arg.SocietyID,
		arg.FlatID,
		arg.Purpose,
	)
	var i FlatVisitorSetting
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.Purpose,
		&i.ApprovalRequired,
		&i.DefaultVisitDurationMinutes,
		&i.IsEnabled,
		&i.Metadata,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSocietyVisitorSettings = `-- name: UpdateSocietyVisitorSettings :one
UPDATE society_visitor_settings
SET
    approval_mode = COALESCE($1::visitor_approval_mode, approval_mode),
    default_visit_duration_minutes = COALESCE($2::integer, default_visit_duration_minutes),
    grace_period_minutes = COALESCE($3::integer, grace_period_minutes),
    qr_expiry_minutes = COALESCE($4::integer, qr_expiry_minutes),
    allow_resident_pre_approval = COALESCE($5::boolean, allow_resident_pre_approval),
    allow_public_qr_entry = COALESCE($6::boolean, allow_public_qr_entry),
    allow_guard_entry = COALESCE($7::boolean, allow_guard_entry),
    allow_guard_on_behalf_approval = COALESCE($8::boolean, allow_guard_on_behalf_approval),
    is_active = COALESCE($9::boolean, is_active),
    updated_by = $10,
    updated_at = NOW()
WHERE society_id = $11
RETURNING id, society_id, approval_mode, default_visit_duration_minutes, grace_period_minutes, qr_expiry_minutes, allow_resident_pre_approval, allow_public_qr_entry, allow_guard_entry, is_active, metadata, updated_by, created_at, updated_at, allow_guard_on_behalf_approval
`

type UpdateSocietyVisitorSettingsParams struct {
	ApprovalMode                *VisitorApprovalMode `db:"approval_mode" json:"approval_mode"`
	DefaultVisitDurationMinutes *int32               `db:"default_visit_duration_minutes" json:"default_visit_duration_minutes"`
	GracePeriodMinutes          *int32               `db:"grace_period_minutes" json:"grace_period_minutes"`
	QrExpiryMinutes             *int32               `db:"qr_expiry_minutes" json:"qr_expiry_minutes"`
	AllowResidentPreApproval    *bool                `db:"allow_resident_pre_approval" json:"allow_resident_pre_approval"`
	AllowPublicQrEntry          *bool                `db:"allow_public_qr_entry" json:"allow_public_qr_entry"`
	AllowGuardEntry             *bool                `db:"allow_guard_entry" json:"allow_guard_entry"`
	AllowGuardOnBehalfApproval  *bool                `db:"allow_guard_on_behalf_approval" json:"allow_guard_on_behalf_approval"`
	IsActive                    *bool                `db:"is_active" json:"is_active"`
	UpdatedBy                   *int64               `db:"updated_by" json:"updated_by"`
	SocietyID                   int64                `db:"society_id" json:"society_id"`
}

func (q *Queries) UpdateSocietyVisitorSettings(ctx context.Context, arg UpdateSocietyVisitorSettingsParams) (SocietyVisitorSetting, error) {
	row := q.db.QueryRow(ctx, updateSocietyVisitorSettings,
		arg.ApprovalMode,
		arg.DefaultVisitDurationMinutes,
		arg.GracePeriodMinutes,
		arg.QrExpiryMinutes,
		arg.AllowResidentPreApproval,
		arg.AllowPublicQrEntry,
		arg.AllowGuardEntry,
		arg.AllowGuardOnBehalfApproval,
		arg.IsActive,
		arg.UpdatedBy,
		arg.SocietyID,
	)
	var i SocietyVisitorSetting
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.ApprovalMode,
		&i.DefaultVisitDurationMinutes,
		&i.GracePeriodMinutes,
		&i.QrExpiryMinutes,
		&i.AllowResidentPreApproval,
		&i.AllowPublicQrEntry,
		&i.AllowGuardEntry,
		&i.IsActive,
		&i.Metadata,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllowGuardOnBehalfApproval,
	)
	return i, err
}
