// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visitor_entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveVisitorEntry = `-- name: ApproveVisitorEntry :one
UPDATE visitor_entries
SET status = 'approved',
    approved_by = $3,
    approved_at = NOW(),
    qr_token_hash = $4,
    qr_expires_at = $5,
    updated_at = NOW()
WHERE id = $1
  AND society_id = $2
  AND status = 'waiting_approval'
RETURNING id, society_id, flat_id, visitor_id, invite_id, source, purpose, status, vehicle_number, vehicle_type, companions_count, companion_details, expected_at, expected_checkout_at, checked_in_at, checked_out_at, auto_closed_at, approved_by, rejected_by, handled_by_guard_id, created_by, qr_token_hash, qr_expires_at, qr_used_at, notes, rejection_reason, metadata, created_at, updated_at, approved_at, delivery_partner, service_provider
`

type ApproveVisitorEntryParams struct {
	ID          int64              `db:"id" json:"id"`
	SocietyID   int64              `db:"society_id" json:"society_id"`
	ApprovedBy  *int64             `db:"approved_by" json:"approved_by"`
	QrTokenHash *string            `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt pgtype.Timestamptz `db:"qr_expires_at" json:"qr_expires_at"`
}

func (q *Queries) ApproveVisitorEntry(ctx context.Context, arg ApproveVisitorEntryParams) (VisitorEntry, error) {
	row := q.db.QueryRow(ctx, approveVisitorEntry,
		arg.ID,
		arg.SocietyID,
		arg.ApprovedBy,
		arg.QrTokenHash,
		arg.QrExpiresAt,
	)
	var i VisitorEntry
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.VisitorID,
		&i.InviteID,
		&i.Source,
		&i.Purpose,
		&i.Status,
		&i.VehicleNumber,
		&i.VehicleType,
		&i.CompanionsCount,
		&i.CompanionDetails,
		&i.ExpectedAt,
		&i.ExpectedCheckoutAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.AutoClosedAt,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.HandledByGuardID,
		&i.CreatedBy,
		&i.QrTokenHash,
		&i.QrExpiresAt,
		&i.QrUsedAt,
		&i.Notes,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovedAt,
		&i.DeliveryPartner,
		&i.ServiceProvider,
	)
	return i, err
}

const autoCloseExpiredVisitorEntries = `-- name: AutoCloseExpiredVisitorEntries :exec
UPDATE visitor_entries
SET status = 'auto_closed',
    auto_closed_at = NOW(),
    updated_at = NOW()
WHERE status = 'checked_in'
  AND expected_checkout_at IS NOT NULL
  AND expected_checkout_at < NOW()
`

func (q *Queries) AutoCloseExpiredVisitorEntries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, autoCloseExpiredVisitorEntries)
	return err
}

const cancelVisitorInvite = `-- name: CancelVisitorInvite :one
UPDATE visitor_invites
SET status = 'cancelled',
    updated_at = NOW()
WHERE id = $1
  AND society_id = $2
  AND status = 'active'
RETURNING id, society_id, flat_id, created_by, purpose, token_hash, status, expires_at, used_at, metadata, created_at, updated_at
`

type CancelVisitorInviteParams struct {
	ID        int64 `db:"id" json:"id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
}

func (q *Queries) CancelVisitorInvite(ctx context.Context, arg CancelVisitorInviteParams) (VisitorInvite, error) {
	row := q.db.QueryRow(ctx, cancelVisitorInvite, arg.ID, arg.SocietyID)
	var i VisitorInvite
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.CreatedBy,
		&i.Purpose,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkInVisitorEntry = `-- name: CheckInVisitorEntry :one
UPDATE visitor_entries
SET status = 'checked_in',
    checked_in_at = NOW(),
    handled_by_guard_id = $3,
    qr_used_at = COALESCE(qr_used_at, NOW()),
    updated_at = NOW()
WHERE id = $1
  AND society_id = $2
  AND status = 'approved'
RETURNING id, society_id, flat_id, visitor_id, invite_id, source, purpose, status, vehicle_number, vehicle_type, companions_count, companion_details, expected_at, expected_checkout_at, checked_in_at, checked_out_at, auto_closed_at, approved_by, rejected_by, handled_by_guard_id, created_by, qr_token_hash, qr_expires_at, qr_used_at, notes, rejection_reason, metadata, created_at, updated_at, approved_at, delivery_partner, service_provider
`

type CheckInVisitorEntryParams struct {
	ID               int64  `db:"id" json:"id"`
	SocietyID        int64  `db:"society_id" json:"society_id"`
	HandledByGuardID *int64 `db:"handled_by_guard_id" json:"handled_by_guard_id"`
}

func (q *Queries) CheckInVisitorEntry(ctx context.Context, arg CheckInVisitorEntryParams) (VisitorEntry, error) {
	row := q.db.QueryRow(ctx, checkInVisitorEntry, arg.ID, arg.SocietyID, arg.HandledByGuardID)
	var i VisitorEntry
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.VisitorID,
		&i.InviteID,
		&i.Source,
		&i.Purpose,
		&i.Status,
		&i.VehicleNumber,
		&i.VehicleType,
		&i.CompanionsCount,
		&i.CompanionDetails,
		&i.ExpectedAt,
		&i.ExpectedCheckoutAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.AutoClosedAt,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.HandledByGuardID,
		&i.CreatedBy,
		&i.QrTokenHash,
		&i.QrExpiresAt,
		&i.QrUsedAt,
		&i.Notes,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovedAt,
		&i.DeliveryPartner,
		&i.ServiceProvider,
	)
	return i, err
}

const checkOutVisitorEntry = `-- name: CheckOutVisitorEntry :one
UPDATE visitor_entries
SET status = 'checked_out',
    checked_out_at = NOW(),
    handled_by_guard_id = $3,
    updated_at = NOW()
WHERE id = $1
  AND society_id = $2
  AND status = 'checked_in'
RETURNING id, society_id, flat_id, visitor_id, invite_id, source, purpose, status, vehicle_number, vehicle_type, companions_count, companion_details, expected_at, expected_checkout_at, checked_in_at, checked_out_at, auto_closed_at, approved_by, rejected_by, handled_by_guard_id, created_by, qr_token_hash, qr_expires_at, qr_used_at, notes, rejection_reason, metadata, created_at, updated_at, approved_at, delivery_partner, service_provider
`

type CheckOutVisitorEntryParams struct {
	ID               int64  `db:"id" json:"id"`
	SocietyID        int64  `db:"society_id" json:"society_id"`
	HandledByGuardID *int64 `db:"handled_by_guard_id" json:"handled_by_guard_id"`
}

func (q *Queries) CheckOutVisitorEntry(ctx context.Context, arg CheckOutVisitorEntryParams) (VisitorEntry, error) {
	row := q.db.QueryRow(ctx, checkOutVisitorEntry, arg.ID, arg.SocietyID, arg.HandledByGuardID)
	var i VisitorEntry
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.VisitorID,
		&i.InviteID,
		&i.Source,
		&i.Purpose,
		&i.Status,
		&i.VehicleNumber,
		&i.VehicleType,
		&i.CompanionsCount,
		&i.CompanionDetails,
		&i.ExpectedAt,
		&i.ExpectedCheckoutAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.AutoClosedAt,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.HandledByGuardID,
		&i.CreatedBy,
		&i.QrTokenHash,
		&i.QrExpiresAt,
		&i.QrUsedAt,
		&i.Notes,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovedAt,
		&i.DeliveryPartner,
		&i.ServiceProvider,
	)
	return i, err
}

const countMemberVisitorApprovals = `-- name: CountMemberVisitorApprovals :one
SELECT
    COUNT(*) FILTER (WHERE ve.approved_by = $2)::bigint AS approved_count,
    COUNT(*) FILTER (WHERE ve.rejected_by = $2)::bigint AS rejected_count
FROM visitor_entries ve
WHERE ve.society_id = $1
  AND (ve.approved_by = $2 OR ve.rejected_by = $2)
`

type CountMemberVisitorApprovalsParams struct {
	SocietyID  int64  `db:"society_id" json:"society_id"`
	ApprovedBy *int64 `db:"approved_by" json:"approved_by"`
}

type CountMemberVisitorApprovalsRow struct {
	ApprovedCount int64 `db:"approved_count" json:"approved_count"`
	RejectedCount int64 `db:"rejected_count" json:"rejected_count"`
}

func (q *Queries) CountMemberVisitorApprovals(ctx context.Context, arg CountMemberVisitorApprovalsParams) (CountMemberVisitorApprovalsRow, error) {
	row := q.db.QueryRow(ctx, countMemberVisitorApprovals, arg.SocietyID, arg.ApprovedBy)
	var i CountMemberVisitorApprovalsRow
	err := row.Scan(&i.ApprovedCount, &i.RejectedCount)
	return i, err
}

const countSocietyPendingVisitorApprovals = `-- name: CountSocietyPendingVisitorApprovals :one
SELECT COUNT(*)
FROM visitor_entries ve
JOIN flats f ON f.id = ve.flat_id
WHERE ve.society_id = $1
  AND ve.status = 'waiting_approval'
  AND ($2::bigint IS NULL OR ve.flat_id = $2::bigint)
  AND ($3::text IS NULL OR f.block = $3::text)
`

type CountSocietyPendingVisitorApprovalsParams struct {
	SocietyID int64   `db:"society_id" json:"society_id"`
	FlatID    *int64  `db:"flat_id" json:"flat_id"`
	Block     *string `db:"block" json:"block"`
}

func (q *Queries) CountSocietyPendingVisitorApprovals(ctx context.Context, arg CountSocietyPendingVisitorApprovalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSocietyPendingVisitorApprovals, arg.SocietyID, arg.FlatID, arg.Block)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVisitorEntries = `-- name: CountVisitorEntries :one
SELECT COUNT(*)
FROM visitor_entries ve
JOIN flats f ON f.id = ve.flat_id
WHERE ve.society_id = $1
  AND ($2::bigint IS NULL OR ve.flat_id = $2::bigint)
  AND ($3::visitor_status IS NULL OR ve.status = $3::visitor_status)
  AND ($4::visitor_source IS NULL OR ve.source = $4::visitor_source)
  AND ($5::visitor_purpose IS NULL OR ve.purpose = $5::visitor_purpose)
  AND ($6::text IS NULL OR f.block = $6::text)
  AND ($7::timestamptz IS NULL OR ve.created_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR ve.created_at < $8::timestamptz)
  AND (
      $9::text IS NULL
      OR $10::timestamptz IS NULL
      OR $11::timestamptz IS NULL
      OR (
          $9::text = 'created'
          AND ve.created_at >= $10::timestamptz
          AND ve.created_at < $11::timestamptz
      )
      OR (
          $9::text = 'checked_in'
          AND ve.checked_in_at IS NOT NULL
          AND ve.checked_in_at >= $10::timestamptz
          AND ve.checked_in_at < $11::timestamptz
      )
      OR (
          $9::text = 'checked_out'
          AND ve.checked_out_at IS NOT NULL
          AND ve.checked_out_at >= $10::timestamptz
          AND ve.checked_out_at < $11::timestamptz
      )
      OR (
          $9::text = 'expected'
          AND ve.expected_at IS NOT NULL
          AND ve.expected_at >= $10::timestamptz
          AND ve.expected_at < $11::timestamptz
      )
      OR (
          $9::text = 'activity'
          AND (
              (ve.created_at >= $10::timestamptz AND ve.created_at < $11::timestamptz)
              OR (
                  ve.checked_in_at IS NOT NULL
                  AND ve.checked_in_at >= $10::timestamptz
                  AND ve.checked_in_at < $11::timestamptz
              )
              OR (
                  ve.checked_out_at IS NOT NULL
                  AND ve.checked_out_at >= $10::timestamptz
                  AND ve.checked_out_at < $11::timestamptz
              )
          )
      )
  )
  AND (
      COALESCE($12::text, '') = ''
      OR EXISTS (
          SELECT 1
          FROM visitors v
          WHERE v.id = ve.visitor_id
            AND (
                v.full_name ILIKE '%' || $12::text || '%'
                OR COALESCE(v.phone_number, '') ILIKE '%' || $12::text || '%'
            )
      )
      OR EXISTS (
          SELECT 1
          FROM flats f
          WHERE f.id = ve.flat_id
            AND (
                COALESCE(f.flat_number, '') ILIKE '%' || $12::text || '%'
                OR COALESCE(f.block, '') ILIKE '%' || $12::text || '%'
            )
      )
  )
`

type CountVisitorEntriesParams struct {
	SocietyID   int64              `db:"society_id" json:"society_id"`
	FlatID      *int64             `db:"flat_id" json:"flat_id"`
	Status      *VisitorStatus     `db:"status" json:"status"`
	Source      *VisitorSource     `db:"source" json:"source"`
	Purpose     *VisitorPurpose    `db:"purpose" json:"purpose"`
	Block       *string            `db:"block" json:"block"`
	CreatedFrom pgtype.Timestamptz `db:"created_from" json:"created_from"`
	CreatedTo   pgtype.Timestamptz `db:"created_to" json:"created_to"`
	Event       *string            `db:"event" json:"event"`
	EventFrom   pgtype.Timestamptz `db:"event_from" json:"event_from"`
	EventTo     pgtype.Timestamptz `db:"event_to" json:"event_to"`
	Search      *string            `db:"search" json:"search"`
}

func (q *Queries) CountVisitorEntries(ctx context.Context, arg CountVisitorEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVisitorEntries,
		arg.SocietyID,
		arg.FlatID,
		arg.Status,
		arg.Source,
		arg.Purpose,
		arg.Block,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Event,
		arg.EventFrom,
		arg.EventTo,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWaitingAtGateVisitorEntries = `-- name: CountWaitingAtGateVisitorEntries :one
SELECT COUNT(*)::bigint
FROM visitor_entries ve
WHERE ve.society_id = $1
  AND ve.status = 'approved'
`

func (q *Queries) CountWaitingAtGateVisitorEntries(ctx context.Context, societyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitingAtGateVisitorEntries, societyID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countWaitingAtGateVisitorEntriesFiltered = `-- name: CountWaitingAtGateVisitorEntriesFiltered :one
SELECT COUNT(*)::bigint
FROM visitor_entries ve
JOIN visitors v ON v.id = ve.visitor_id
JOIN flats f ON f.id = ve.flat_id
WHERE ve.society_id = $1
  AND ve.status = 'approved'
  AND (
      COALESCE($2::text, '') = ''
      OR v.full_name ILIKE '%' || $2::text || '%'
      OR COALESCE(v.phone_number, '') ILIKE '%' || $2::text || '%'
      OR COALESCE(f.flat_number, '') ILIKE '%' || $2::text || '%'
      OR COALESCE(f.block, '') ILIKE '%' || $2::text || '%'
      OR COALESCE(ve.vehicle_number, '') ILIKE '%' || $2::text || '%'
      OR COALESCE(ve.delivery_partner, '') ILIKE '%' || $2::text || '%'
      OR ve.purpose::text ILIKE '%' || $2::text || '%'
  )
`

type CountWaitingAtGateVisitorEntriesFilteredParams struct {
	SocietyID int64   `db:"society_id" json:"society_id"`
	Search    *string `db:"search" json:"search"`
}

func (q *Queries) CountWaitingAtGateVisitorEntriesFiltered(ctx context.Context, arg CountWaitingAtGateVisitorEntriesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitingAtGateVisitorEntriesFiltered, arg.SocietyID, arg.Search)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createVisitor = `-- name: CreateVisitor :one
INSERT INTO visitors (full_name, phone_number, email, photo_url, metadata)
VALUES ($1, $2, $3, $4, COALESCE($5, '{}'::jsonb))
RETURNING id, full_name, phone_number, email, photo_url, metadata, created_at, updated_at
`

type CreateVisitorParams struct {
	FullName    string      `db:"full_name" json:"full_name"`
	PhoneNumber *string     `db:"phone_number" json:"phone_number"`
	Email       *string     `db:"email" json:"email"`
	PhotoUrl    *string     `db:"photo_url" json:"photo_url"`
	Metadata    interface{} `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateVisitor(ctx context.Context, arg CreateVisitorParams) (Visitor, error) {
	row := q.db.QueryRow(ctx, createVisitor,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
		arg.PhotoUrl,
		arg.Metadata,
	)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.PhotoUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVisitorEntry = `-- name: CreateVisitorEntry :one
INSERT INTO visitor_entries (
    society_id,
    flat_id,
    visitor_id,
    invite_id,
    source,
    purpose,
    status,
    vehicle_number,
    vehicle_type,
    companions_count,
    companion_details,
    expected_at,
    expected_checkout_at,
    approved_by,
    approved_at,
    delivery_partner,
    service_provider,
    handled_by_guard_id,
    created_by,
    qr_token_hash,
    qr_expires_at,
    notes,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $8,
    $4,
    $5,
    $6,
    $9,
    $10,
    $7,
    COALESCE($11, '[]'::jsonb),
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    COALESCE($23, '{}'::jsonb)
)
RETURNING id, society_id, flat_id, visitor_id, invite_id, source, purpose, status, vehicle_number, vehicle_type, companions_count, companion_details, expected_at, expected_checkout_at, checked_in_at, checked_out_at, auto_closed_at, approved_by, rejected_by, handled_by_guard_id, created_by, qr_token_hash, qr_expires_at, qr_used_at, notes, rejection_reason, metadata, created_at, updated_at, approved_at, delivery_partner, service_provider
`

type CreateVisitorEntryParams struct {
	SocietyID          int64               `db:"society_id" json:"society_id"`
	FlatID             int64               `db:"flat_id" json:"flat_id"`
	VisitorID          int64               `db:"visitor_id" json:"visitor_id"`
	Source             VisitorSource       `db:"source" json:"source"`
	Purpose            VisitorPurpose      `db:"purpose" json:"purpose"`
	Status             VisitorStatus       `db:"status" json:"status"`
	CompanionsCount    int32               `db:"companions_count" json:"companions_count"`
	InviteID           *int64              `db:"invite_id" json:"invite_id"`
	VehicleNumber      *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType        *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionDetails   interface{}         `db:"companion_details" json:"companion_details"`
	ExpectedAt         pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	ApprovedBy         *int64              `db:"approved_by" json:"approved_by"`
	ApprovedAt         pgtype.Timestamptz  `db:"approved_at" json:"approved_at"`
	DeliveryPartner    *string             `db:"delivery_partner" json:"delivery_partner"`
	ServiceProvider    *string             `db:"service_provider" json:"service_provider"`
	HandledByGuardID   *int64              `db:"handled_by_guard_id" json:"handled_by_guard_id"`
	CreatedBy          *int64              `db:"created_by" json:"created_by"`
	QrTokenHash        *string             `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt        pgtype.Timestamptz  `db:"qr_expires_at" json:"qr_expires_at"`
	Notes              *string             `db:"notes" json:"notes"`
	Metadata           interface{}         `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateVisitorEntry(ctx context.Context, arg CreateVisitorEntryParams) (VisitorEntry, error) {
	row := q.db.QueryRow(ctx, createVisitorEntry,
		arg.SocietyID,
		arg.FlatID,
		arg.VisitorID,
		arg.Source,
		arg.Purpose,
		arg.Status,
		arg.CompanionsCount,
		arg.InviteID,
		arg.VehicleNumber,
		arg.VehicleType,
		arg.CompanionDetails,
		arg.ExpectedAt,
		arg.ExpectedCheckoutAt,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.DeliveryPartner,
		arg.ServiceProvider,
		arg.HandledByGuardID,
		arg.CreatedBy,
		arg.QrTokenHash,
		arg.QrExpiresAt,
		arg.Notes,
		arg.Metadata,
	)
	var i VisitorEntry
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.VisitorID,
		&i.InviteID,
		&i.Source,
		&i.Purpose,
		&i.Status,
		&i.VehicleNumber,
		&i.VehicleType,
		&i.CompanionsCount,
		&i.CompanionDetails,
		&i.ExpectedAt,
		&i.ExpectedCheckoutAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.AutoClosedAt,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.HandledByGuardID,
		&i.CreatedBy,
		&i.QrTokenHash,
		&i.QrExpiresAt,
		&i.QrUsedAt,
		&i.Notes,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovedAt,
		&i.DeliveryPartner,
		&i.ServiceProvider,
	)
	return i, err
}

const createVisitorEntryEvent = `-- name: CreateVisitorEntryEvent :one
INSERT INTO visitor_entry_events (visitor_entry_id, society_id, actor_user_id, event_type, message, metadata)
VALUES ($1, $2, $4, $3, $5, COALESCE($6, '{}'::jsonb))
RETURNING id, visitor_entry_id, society_id, actor_user_id, event_type, message, metadata, created_at
`

type CreateVisitorEntryEventParams struct {
	VisitorEntryID int64            `db:"visitor_entry_id" json:"visitor_entry_id"`
	SocietyID      int64            `db:"society_id" json:"society_id"`
	EventType      VisitorEventType `db:"event_type" json:"event_type"`
	ActorUserID    *int64           `db:"actor_user_id" json:"actor_user_id"`
	Message        *string          `db:"message" json:"message"`
	Metadata       interface{}      `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateVisitorEntryEvent(ctx context.Context, arg CreateVisitorEntryEventParams) (VisitorEntryEvent, error) {
	row := q.db.QueryRow(ctx, createVisitorEntryEvent,
		arg.VisitorEntryID,
		arg.SocietyID,
		arg.EventType,
		arg.ActorUserID,
		arg.Message,
		arg.Metadata,
	)
	var i VisitorEntryEvent
	err := row.Scan(
		&i.ID,
		&i.VisitorEntryID,
		&i.SocietyID,
		&i.ActorUserID,
		&i.EventType,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createVisitorInvite = `-- name: CreateVisitorInvite :one
INSERT INTO visitor_invites (society_id, flat_id, created_by, purpose, token_hash, expires_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, '{}'::jsonb))
RETURNING id, society_id, flat_id, created_by, purpose, token_hash, status, expires_at, used_at, metadata, created_at, updated_at
`

type CreateVisitorInviteParams struct {
	SocietyID int64              `db:"society_id" json:"society_id"`
	FlatID    int64              `db:"flat_id" json:"flat_id"`
	CreatedBy int64              `db:"created_by" json:"created_by"`
	Purpose   VisitorPurpose     `db:"purpose" json:"purpose"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Metadata  interface{}        `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateVisitorInvite(ctx context.Context, arg CreateVisitorInviteParams) (VisitorInvite, error) {
	row := q.db.QueryRow(ctx, createVisitorInvite,
		arg.SocietyID,
		arg.FlatID,
		arg.CreatedBy,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i VisitorInvite
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.CreatedBy,
		&i.Purpose,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireOldVisitorInvites = `-- name: ExpireOldVisitorInvites :exec
UPDATE visitor_invites
SET status = 'expired',
    updated_at = NOW()
WHERE status = 'active'
  AND expires_at < NOW()
`

func (q *Queries) ExpireOldVisitorInvites(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOldVisitorInvites)
	return err
}

const generateVisitorEntryQR = `-- name: GenerateVisitorEntryQR :one
UPDATE visitor_entries
SET qr_token_hash = $3,
    qr_expires_at = $4,
    updated_at = NOW()
WHERE id = $1
  AND society_id = $2
  AND status = 'approved'
RETURNING id, society_id, flat_id, visitor_id, invite_id, source, purpose, status, vehicle_number, vehicle_type, companions_count, companion_details, expected_at, expected_checkout_at, checked_in_at, checked_out_at, auto_closed_at, approved_by, rejected_by, handled_by_guard_id, created_by, qr_token_hash, qr_expires_at, qr_used_at, notes, rejection_reason, metadata, created_at, updated_at, approved_at, delivery_partner, service_provider
`

type GenerateVisitorEntryQRParams struct {
	ID          int64              `db:"id" json:"id"`
	SocietyID   int64              `db:"society_id" json:"society_id"`
	QrTokenHash *string            `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt pgtype.Timestamptz `db:"qr_expires_at" json:"qr_expires_at"`
}

func (q *Queries) GenerateVisitorEntryQR(ctx context.Context, arg GenerateVisitorEntryQRParams) (VisitorEntry, error) {
	row := q.db.QueryRow(ctx, generateVisitorEntryQR,
		arg.ID,
		arg.SocietyID,
		arg.QrTokenHash,
		arg.QrExpiresAt,
	)
	var i VisitorEntry
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.VisitorID,
		&i.InviteID,
		&i.Source,
		&i.Purpose,
		&i.Status,
		&i.VehicleNumber,
		&i.VehicleType,
		&i.CompanionsCount,
		&i.CompanionDetails,
		&i.ExpectedAt,
		&i.ExpectedCheckoutAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.AutoClosedAt,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.HandledByGuardID,
		&i.CreatedBy,
		&i.QrTokenHash,
		&i.QrExpiresAt,
		&i.QrUsedAt,
		&i.Notes,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovedAt,
		&i.DeliveryPartner,
		&i.ServiceProvider,
	)
	return i, err
}

const getVisitor = `-- name: GetVisitor :one
SELECT id, full_name, phone_number, email, photo_url, metadata, created_at, updated_at
FROM visitors
WHERE id = $1
`

func (q *Queries) GetVisitor(ctx context.Context, id int64) (Visitor, error) {
	row := q.db.QueryRow(ctx, getVisitor, id)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.PhotoUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisitorEntry = `-- name: GetVisitorEntry :one
SELECT
    ve.id, ve.society_id, ve.flat_id, ve.visitor_id, ve.invite_id, ve.source, ve.purpose, ve.status, ve.vehicle_number, ve.vehicle_type, ve.companions_count, ve.companion_details, ve.expected_at, ve.expected_checkout_at, ve.checked_in_at, ve.checked_out_at, ve.auto_closed_at, ve.approved_by, ve.rejected_by, ve.handled_by_guard_id, ve.created_by, ve.qr_token_hash, ve.qr_expires_at, ve.qr_used_at, ve.notes, ve.rejection_reason, ve.metadata, ve.created_at, ve.updated_at, ve.approved_at, ve.delivery_partner, ve.service_provider,
    v.full_name AS visitor_full_name,
    v.phone_number AS visitor_phone_number,
    v.email AS visitor_email,
    v.photo_url AS visitor_photo_url,
    f.flat_number,
    f.block,
    f.floor
FROM visitor_entries ve
JOIN visitors v ON v.id = ve.visitor_id
JOIN flats f ON f.id = ve.flat_id
WHERE ve.id = $1
  AND ve.society_id = $2
`

type GetVisitorEntryParams struct {
	ID        int64 `db:"id" json:"id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
}

type GetVisitorEntryRow struct {
	ID                 int64               `db:"id" json:"id"`
	SocietyID          int64               `db:"society_id" json:"society_id"`
	FlatID             int64               `db:"flat_id" json:"flat_id"`
	VisitorID          int64               `db:"visitor_id" json:"visitor_id"`
	InviteID           *int64              `db:"invite_id" json:"invite_id"`
	Source             VisitorSource       `db:"source" json:"source"`
	Purpose            VisitorPurpose      `db:"purpose" json:"purpose"`
	Status             VisitorStatus       `db:"status" json:"status"`
	VehicleNumber      *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType        *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionsCount    int32               `db:"companions_count" json:"companions_count"`
	CompanionDetails   []byte              `db:"companion_details" json:"companion_details"`
	ExpectedAt         pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	CheckedInAt        pgtype.Timestamptz  `db:"checked_in_at" json:"checked_in_at"`
	CheckedOutAt       pgtype.Timestamptz  `db:"checked_out_at" json:"checked_out_at"`
	AutoClosedAt       pgtype.Timestamptz  `db:"auto_closed_at" json:"auto_closed_at"`
	ApprovedBy         *int64              `db:"approved_by" json:"approved_by"`
	RejectedBy         *int64              `db:"rejected_by" json:"rejected_by"`
	HandledByGuardID   *int64              `db:"handled_by_guard_id" json:"handled_by_guard_id"`
	CreatedBy          *int64              `db:"created_by" json:"created_by"`
	QrTokenHash        *string             `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt        pgtype.Timestamptz  `db:"qr_expires_at" json:"qr_expires_at"`
	QrUsedAt           pgtype.Timestamptz  `db:"qr_used_at" json:"qr_used_at"`
	Notes              *string             `db:"notes" json:"notes"`
	RejectionReason    *string             `db:"rejection_reason" json:"rejection_reason"`
	Metadata           []byte              `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	ApprovedAt         pgtype.Timestamptz  `db:"approved_at" json:"approved_at"`
	DeliveryPartner    *string             `db:"delivery_partner" json:"delivery_partner"`
	ServiceProvider    *string             `db:"service_provider" json:"service_provider"`
	VisitorFullName    string              `db:"visitor_full_name" json:"visitor_full_name"`
	VisitorPhoneNumber *string             `db:"visitor_phone_number" json:"visitor_phone_number"`
	VisitorEmail       *string             `db:"visitor_email" json:"visitor_email"`
	VisitorPhotoUrl    *string             `db:"visitor_photo_url" json:"visitor_photo_url"`
	FlatNumber         string              `db:"flat_number" json:"flat_number"`
	Block              *string             `db:"block" json:"block"`
	Floor              *string             `db:"floor" json:"floor"`
}

func (q *Queries) GetVisitorEntry(ctx context.Context, arg GetVisitorEntryParams) (GetVisitorEntryRow, error) {
	row := q.db.QueryRow(ctx, getVisitorEntry, arg.ID, arg.SocietyID)
	var i GetVisitorEntryRow
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.VisitorID,
		&i.InviteID,
		&i.Source,
		&i.Purpose,
		&i.Status,
		&i.VehicleNumber,
		&i.VehicleType,
		&i.CompanionsCount,
		&i.CompanionDetails,
		&i.ExpectedAt,
		&i.ExpectedCheckoutAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.AutoClosedAt,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.HandledByGuardID,
		&i.CreatedBy,
		&i.QrTokenHash,
		&i.QrExpiresAt,
		&i.QrUsedAt,
		&i.Notes,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovedAt,
		&i.DeliveryPartner,
		&i.ServiceProvider,
		&i.VisitorFullName,
		&i.VisitorPhoneNumber,
		&i.VisitorEmail,
		&i.VisitorPhotoUrl,
		&i.FlatNumber,
		&i.Block,
		&i.Floor,
	)
	return i, err
}

const getVisitorEntryByInviteID = `-- name: GetVisitorEntryByInviteID :one
SELECT
    ve.id, ve.society_id, ve.flat_id, ve.visitor_id, ve.invite_id, ve.source, ve.purpose, ve.status, ve.vehicle_number, ve.vehicle_type, ve.companions_count, ve.companion_details, ve.expected_at, ve.expected_checkout_at, ve.checked_in_at, ve.checked_out_at, ve.auto_closed_at, ve.approved_by, ve.rejected_by, ve.handled_by_guard_id, ve.created_by, ve.qr_token_hash, ve.qr_expires_at, ve.qr_used_at, ve.notes, ve.rejection_reason, ve.metadata, ve.created_at, ve.updated_at, ve.approved_at, ve.delivery_partner, ve.service_provider,
    v.full_name AS visitor_full_name,
    v.phone_number AS visitor_phone_number,
    v.email AS visitor_email,
    v.photo_url AS visitor_photo_url,
    f.flat_number,
    f.block,
    f.floor
FROM visitor_entries ve
JOIN visitors v ON v.id = ve.visitor_id
JOIN flats f ON f.id = ve.flat_id
WHERE ve.invite_id = $1
`

type GetVisitorEntryByInviteIDRow struct {
	ID                 int64               `db:"id" json:"id"`
	SocietyID          int64               `db:"society_id" json:"society_id"`
	FlatID             int64               `db:"flat_id" json:"flat_id"`
	VisitorID          int64               `db:"visitor_id" json:"visitor_id"`
	InviteID           *int64              `db:"invite_id" json:"invite_id"`
	Source             VisitorSource       `db:"source" json:"source"`
	Purpose            VisitorPurpose      `db:"purpose" json:"purpose"`
	Status             VisitorStatus       `db:"status" json:"status"`
	VehicleNumber      *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType        *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionsCount    int32               `db:"companions_count" json:"companions_count"`
	CompanionDetails   []byte              `db:"companion_details" json:"companion_details"`
	ExpectedAt         pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	CheckedInAt        pgtype.Timestamptz  `db:"checked_in_at" json:"checked_in_at"`
	CheckedOutAt       pgtype.Timestamptz  `db:"checked_out_at" json:"checked_out_at"`
	AutoClosedAt       pgtype.Timestamptz  `db:"auto_closed_at" json:"auto_closed_at"`
	ApprovedBy         *int64              `db:"approved_by" json:"approved_by"`
	RejectedBy         *int64              `db:"rejected_by" json:"rejected_by"`
	HandledByGuardID   *int64              `db:"handled_by_guard_id" json:"handled_by_guard_id"`
	CreatedBy          *int64              `db:"created_by" json:"created_by"`
	QrTokenHash        *string             `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt        pgtype.Timestamptz  `db:"qr_expires_at" json:"qr_expires_at"`
	QrUsedAt           pgtype.Timestamptz  `db:"qr_used_at" json:"qr_used_at"`
	Notes              *string             `db:"notes" json:"notes"`
	RejectionReason    *string             `db:"rejection_reason" json:"rejection_reason"`
	Metadata           []byte              `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	ApprovedAt         pgtype.Timestamptz  `db:"approved_at" json:"approved_at"`
	DeliveryPartner    *string             `db:"delivery_partner" json:"delivery_partner"`
	ServiceProvider    *string             `db:"service_provider" json:"service_provider"`
	VisitorFullName    string              `db:"visitor_full_name" json:"visitor_full_name"`
	VisitorPhoneNumber *string             `db:"visitor_phone_number" json:"visitor_phone_number"`
	VisitorEmail       *string             `db:"visitor_email" json:"visitor_email"`
	VisitorPhotoUrl    *string             `db:"visitor_photo_url" json:"visitor_photo_url"`
	FlatNumber         string              `db:"flat_number" json:"flat_number"`
	Block              *string             `db:"block" json:"block"`
	Floor              *string             `db:"floor" json:"floor"`
}

func (q *Queries) GetVisitorEntryByInviteID(ctx context.Context, inviteID *int64) (GetVisitorEntryByInviteIDRow, error) {
	row := q.db.QueryRow(ctx, getVisitorEntryByInviteID, inviteID)
	var i GetVisitorEntryByInviteIDRow
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.VisitorID,
		&i.InviteID,
		&i.Source,
		&i.Purpose,
		&i.Status,
		&i.VehicleNumber,
		&i.VehicleType,
		&i.CompanionsCount,
		&i.CompanionDetails,
		&i.ExpectedAt,
		&i.ExpectedCheckoutAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.AutoClosedAt,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.HandledByGuardID,
		&i.CreatedBy,
		&i.QrTokenHash,
		&i.QrExpiresAt,
		&i.QrUsedAt,
		&i.Notes,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovedAt,
		&i.DeliveryPartner,
		&i.ServiceProvider,
		&i.VisitorFullName,
		&i.VisitorPhoneNumber,
		&i.VisitorEmail,
		&i.VisitorPhotoUrl,
		&i.FlatNumber,
		&i.Block,
		&i.Floor,
	)
	return i, err
}

const getVisitorEntryByQRHash = `-- name: GetVisitorEntryByQRHash :one
SELECT
    ve.id, ve.society_id, ve.flat_id, ve.visitor_id, ve.invite_id, ve.source, ve.purpose, ve.status, ve.vehicle_number, ve.vehicle_type, ve.companions_count, ve.companion_details, ve.expected_at, ve.expected_checkout_at, ve.checked_in_at, ve.checked_out_at, ve.auto_closed_at, ve.approved_by, ve.rejected_by, ve.handled_by_guard_id, ve.created_by, ve.qr_token_hash, ve.qr_expires_at, ve.qr_used_at, ve.notes, ve.rejection_reason, ve.metadata, ve.created_at, ve.updated_at, ve.approved_at, ve.delivery_partner, ve.service_provider,
    v.full_name AS visitor_full_name,
    v.phone_number AS visitor_phone_number,
    v.email AS visitor_email,
    v.photo_url AS visitor_photo_url,
    f.flat_number,
    f.block,
    f.floor
FROM visitor_entries ve
JOIN visitors v ON v.id = ve.visitor_id
JOIN flats f ON f.id = ve.flat_id
WHERE ve.qr_token_hash = $1
`

type GetVisitorEntryByQRHashRow struct {
	ID                 int64               `db:"id" json:"id"`
	SocietyID          int64               `db:"society_id" json:"society_id"`
	FlatID             int64               `db:"flat_id" json:"flat_id"`
	VisitorID          int64               `db:"visitor_id" json:"visitor_id"`
	InviteID           *int64              `db:"invite_id" json:"invite_id"`
	Source             VisitorSource       `db:"source" json:"source"`
	Purpose            VisitorPurpose      `db:"purpose" json:"purpose"`
	Status             VisitorStatus       `db:"status" json:"status"`
	VehicleNumber      *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType        *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionsCount    int32               `db:"companions_count" json:"companions_count"`
	CompanionDetails   []byte              `db:"companion_details" json:"companion_details"`
	ExpectedAt         pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	CheckedInAt        pgtype.Timestamptz  `db:"checked_in_at" json:"checked_in_at"`
	CheckedOutAt       pgtype.Timestamptz  `db:"checked_out_at" json:"checked_out_at"`
	AutoClosedAt       pgtype.Timestamptz  `db:"auto_closed_at" json:"auto_closed_at"`
	ApprovedBy         *int64              `db:"approved_by" json:"approved_by"`
	RejectedBy         *int64              `db:"rejected_by" json:"rejected_by"`
	HandledByGuardID   *int64              `db:"handled_by_guard_id" json:"handled_by_guard_id"`
	CreatedBy          *int64              `db:"created_by" json:"created_by"`
	QrTokenHash        *string             `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt        pgtype.Timestamptz  `db:"qr_expires_at" json:"qr_expires_at"`
	QrUsedAt           pgtype.Timestamptz  `db:"qr_used_at" json:"qr_used_at"`
	Notes              *string             `db:"notes" json:"notes"`
	RejectionReason    *string             `db:"rejection_reason" json:"rejection_reason"`
	Metadata           []byte              `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	ApprovedAt         pgtype.Timestamptz  `db:"approved_at" json:"approved_at"`
	DeliveryPartner    *string             `db:"delivery_partner" json:"delivery_partner"`
	ServiceProvider    *string             `db:"service_provider" json:"service_provider"`
	VisitorFullName    string              `db:"visitor_full_name" json:"visitor_full_name"`
	VisitorPhoneNumber *string             `db:"visitor_phone_number" json:"visitor_phone_number"`
	VisitorEmail       *string             `db:"visitor_email" json:"visitor_email"`
	VisitorPhotoUrl    *string             `db:"visitor_photo_url" json:"visitor_photo_url"`
	FlatNumber         string              `db:"flat_number" json:"flat_number"`
	Block              *string             `db:"block" json:"block"`
	Floor              *string             `db:"floor" json:"floor"`
}

func (q *Queries) GetVisitorEntryByQRHash(ctx context.Context, qrTokenHash *string) (GetVisitorEntryByQRHashRow, error) {
	row := q.db.QueryRow(ctx, getVisitorEntryByQRHash, qrTokenHash)
	var i GetVisitorEntryByQRHashRow
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.VisitorID,
		&i.InviteID,
		&i.Source,
		&i.Purpose,
		&i.Status,
		&i.VehicleNumber,
		&i.VehicleType,
		&i.CompanionsCount,
		&i.CompanionDetails,
		&i.ExpectedAt,
		&i.ExpectedCheckoutAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.AutoClosedAt,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.HandledByGuardID,
		&i.CreatedBy,
		&i.QrTokenHash,
		&i.QrExpiresAt,
		&i.QrUsedAt,
		&i.Notes,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovedAt,
		&i.DeliveryPartner,
		&i.ServiceProvider,
		&i.VisitorFullName,
		&i.VisitorPhoneNumber,
		&i.VisitorEmail,
		&i.VisitorPhotoUrl,
		&i.FlatNumber,
		&i.Block,
		&i.Floor,
	)
	return i, err
}

const getVisitorEntryStats = `-- name: GetVisitorEntryStats :one
SELECT
    COUNT(*) FILTER (
        WHERE ve.created_at >= (CURRENT_DATE AT TIME ZONE 'Asia/Kolkata') AT TIME ZONE 'Asia/Kolkata'
          AND ve.created_at < ((CURRENT_DATE + INTERVAL '1 day') AT TIME ZONE 'Asia/Kolkata') AT TIME ZONE 'Asia/Kolkata'
    )::bigint AS today_visitors,
    COUNT(*) FILTER (WHERE ve.status = 'checked_in')::bigint AS visitors_inside,
    COUNT(*) FILTER (WHERE ve.status = 'waiting_approval')::bigint AS pending_approvals,
    COUNT(*) FILTER (
        WHERE ve.checked_out_at IS NOT NULL
          AND ve.status = 'checked_out'
          AND ve.checked_out_at >= (CURRENT_DATE AT TIME ZONE 'Asia/Kolkata') AT TIME ZONE 'Asia/Kolkata'
          AND ve.checked_out_at < ((CURRENT_DATE + INTERVAL '1 day') AT TIME ZONE 'Asia/Kolkata') AT TIME ZONE 'Asia/Kolkata'
    )::bigint AS checked_out_today,
    COUNT(*) FILTER (
        WHERE ve.status = 'rejected'
          AND ve.updated_at >= (CURRENT_DATE AT TIME ZONE 'Asia/Kolkata') AT TIME ZONE 'Asia/Kolkata'
          AND ve.updated_at < ((CURRENT_DATE + INTERVAL '1 day') AT TIME ZONE 'Asia/Kolkata') AT TIME ZONE 'Asia/Kolkata'
    )::bigint AS rejected_today,
    COUNT(*) FILTER (
        WHERE ve.auto_closed_at IS NOT NULL
          AND ve.auto_closed_at >= (CURRENT_DATE AT TIME ZONE 'Asia/Kolkata') AT TIME ZONE 'Asia/Kolkata'
          AND ve.auto_closed_at < ((CURRENT_DATE + INTERVAL '1 day') AT TIME ZONE 'Asia/Kolkata') AT TIME ZONE 'Asia/Kolkata'
    )::bigint AS auto_closed_today
FROM visitor_entries ve
WHERE ve.society_id = $1
`

type GetVisitorEntryStatsRow struct {
	TodayVisitors    int64 `db:"today_visitors" json:"today_visitors"`
	VisitorsInside   int64 `db:"visitors_inside" json:"visitors_inside"`
	PendingApprovals int64 `db:"pending_approvals" json:"pending_approvals"`
	CheckedOutToday  int64 `db:"checked_out_today" json:"checked_out_today"`
	RejectedToday    int64 `db:"rejected_today" json:"rejected_today"`
	AutoClosedToday  int64 `db:"auto_closed_today" json:"auto_closed_today"`
}

func (q *Queries) GetVisitorEntryStats(ctx context.Context, societyID int64) (GetVisitorEntryStatsRow, error) {
	row := q.db.QueryRow(ctx, getVisitorEntryStats, societyID)
	var i GetVisitorEntryStatsRow
	err := row.Scan(
		&i.TodayVisitors,
		&i.VisitorsInside,
		&i.PendingApprovals,
		&i.CheckedOutToday,
		&i.RejectedToday,
		&i.AutoClosedToday,
	)
	return i, err
}

const getVisitorEntryStatsInRange = `-- name: GetVisitorEntryStatsInRange :one
SELECT
    COUNT(*) FILTER (WHERE ve.status = 'checked_in')::bigint AS visitors_inside,
    COUNT(*) FILTER (WHERE ve.status = 'waiting_approval')::bigint AS pending_approvals,
    COUNT(*) FILTER (
        WHERE ve.checked_out_at IS NOT NULL
          AND ve.status = 'checked_out'
          AND ve.checked_out_at >= $1::timestamptz
          AND ve.checked_out_at < $2::timestamptz
    )::bigint AS checked_out_in_range
FROM visitor_entries ve
WHERE ve.society_id = $3
`

type GetVisitorEntryStatsInRangeParams struct {
	EventFrom pgtype.Timestamptz `db:"event_from" json:"event_from"`
	EventTo   pgtype.Timestamptz `db:"event_to" json:"event_to"`
	SocietyID int64              `db:"society_id" json:"society_id"`
}

type GetVisitorEntryStatsInRangeRow struct {
	VisitorsInside    int64 `db:"visitors_inside" json:"visitors_inside"`
	PendingApprovals  int64 `db:"pending_approvals" json:"pending_approvals"`
	CheckedOutInRange int64 `db:"checked_out_in_range" json:"checked_out_in_range"`
}

func (q *Queries) GetVisitorEntryStatsInRange(ctx context.Context, arg GetVisitorEntryStatsInRangeParams) (GetVisitorEntryStatsInRangeRow, error) {
	row := q.db.QueryRow(ctx, getVisitorEntryStatsInRange, arg.EventFrom, arg.EventTo, arg.SocietyID)
	var i GetVisitorEntryStatsInRangeRow
	err := row.Scan(&i.VisitorsInside, &i.PendingApprovals, &i.CheckedOutInRange)
	return i, err
}

const getVisitorInviteByID = `-- name: GetVisitorInviteByID :one
SELECT id, society_id, flat_id, created_by, purpose, token_hash, status, expires_at, used_at, metadata, created_at, updated_at
FROM visitor_invites
WHERE id = $1
  AND society_id = $2
`

type GetVisitorInviteByIDParams struct {
	ID        int64 `db:"id" json:"id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
}

func (q *Queries) GetVisitorInviteByID(ctx context.Context, arg GetVisitorInviteByIDParams) (VisitorInvite, error) {
	row := q.db.QueryRow(ctx, getVisitorInviteByID, arg.ID, arg.SocietyID)
	var i VisitorInvite
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.CreatedBy,
		&i.Purpose,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisitorInviteByTokenHash = `-- name: GetVisitorInviteByTokenHash :one
SELECT id, society_id, flat_id, created_by, purpose, token_hash, status, expires_at, used_at, metadata, created_at, updated_at
FROM visitor_invites
WHERE token_hash = $1
`

func (q *Queries) GetVisitorInviteByTokenHash(ctx context.Context, tokenHash string) (VisitorInvite, error) {
	row := q.db.QueryRow(ctx, getVisitorInviteByTokenHash, tokenHash)
	var i VisitorInvite
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.CreatedBy,
		&i.Purpose,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingVisitorApprovals = `-- name: ListPendingVisitorApprovals :many
SELECT
    ve.id, ve.society_id, ve.flat_id, ve.visitor_id, ve.invite_id, ve.source, ve.purpose, ve.status, ve.vehicle_number, ve.vehicle_type, ve.companions_count, ve.companion_details, ve.expected_at, ve.expected_checkout_at, ve.checked_in_at, ve.checked_out_at, ve.auto_closed_at, ve.approved_by, ve.rejected_by, ve.handled_by_guard_id, ve.created_by, ve.qr_token_hash, ve.qr_expires_at, ve.qr_used_at, ve.notes, ve.rejection_reason, ve.metadata, ve.created_at, ve.updated_at, ve.approved_at, ve.delivery_partner, ve.service_provider,
    v.full_name AS visitor_full_name,
    v.phone_number AS visitor_phone_number,
    v.email AS visitor_email,
    v.photo_url AS visitor_photo_url,
    f.flat_number,
    f.block,
    f.floor
FROM visitor_entries ve
JOIN visitors v ON v.id = ve.visitor_id
JOIN flats f ON f.id = ve.flat_id
WHERE ve.society_id = $1
  AND ve.flat_id = $2
  AND ve.status = 'waiting_approval'
ORDER BY ve.created_at DESC
`

type ListPendingVisitorApprovalsParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
}

type ListPendingVisitorApprovalsRow struct {
	ID                 int64               `db:"id" json:"id"`
	SocietyID          int64               `db:"society_id" json:"society_id"`
	FlatID             int64               `db:"flat_id" json:"flat_id"`
	VisitorID          int64               `db:"visitor_id" json:"visitor_id"`
	InviteID           *int64              `db:"invite_id" json:"invite_id"`
	Source             VisitorSource       `db:"source" json:"source"`
	Purpose            VisitorPurpose      `db:"purpose" json:"purpose"`
	Status             VisitorStatus       `db:"status" json:"status"`
	VehicleNumber      *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType        *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionsCount    int32               `db:"companions_count" json:"companions_count"`
	CompanionDetails   []byte              `db:"companion_details" json:"companion_details"`
	ExpectedAt         pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	CheckedInAt        pgtype.Timestamptz  `db:"checked_in_at" json:"checked_in_at"`
	CheckedOutAt       pgtype.Timestamptz  `db:"checked_out_at" json:"checked_out_at"`
	AutoClosedAt       pgtype.Timestamptz  `db:"auto_closed_at" json:"auto_closed_at"`
	ApprovedBy         *int64              `db:"approved_by" json:"approved_by"`
	RejectedBy         *int64              `db:"rejected_by" json:"rejected_by"`
	HandledByGuardID   *int64              `db:"handled_by_guard_id" json:"handled_by_guard_id"`
	CreatedBy          *int64              `db:"created_by" json:"created_by"`
	QrTokenHash        *string             `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt        pgtype.Timestamptz  `db:"qr_expires_at" json:"qr_expires_at"`
	QrUsedAt           pgtype.Timestamptz  `db:"qr_used_at" json:"qr_used_at"`
	Notes              *string             `db:"notes" json:"notes"`
	RejectionReason    *string             `db:"rejection_reason" json:"rejection_reason"`
	Metadata           []byte              `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	ApprovedAt         pgtype.Timestamptz  `db:"approved_at" json:"approved_at"`
	DeliveryPartner    *string             `db:"delivery_partner" json:"delivery_partner"`
	ServiceProvider    *string             `db:"service_provider" json:"service_provider"`
	VisitorFullName    string              `db:"visitor_full_name" json:"visitor_full_name"`
	VisitorPhoneNumber *string             `db:"visitor_phone_number" json:"visitor_phone_number"`
	VisitorEmail       *string             `db:"visitor_email" json:"visitor_email"`
	VisitorPhotoUrl    *string             `db:"visitor_photo_url" json:"visitor_photo_url"`
	FlatNumber         string              `db:"flat_number" json:"flat_number"`
	Block              *string             `db:"block" json:"block"`
	Floor              *string             `db:"floor" json:"floor"`
}

func (q *Queries) ListPendingVisitorApprovals(ctx context.Context, arg ListPendingVisitorApprovalsParams) ([]ListPendingVisitorApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listPendingVisitorApprovals, arg.SocietyID, arg.FlatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingVisitorApprovalsRow{}
	for rows.Next() {
		var i ListPendingVisitorApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.FlatID,
			&i.VisitorID,
			&i.InviteID,
			&i.Source,
			&i.Purpose,
			&i.Status,
			&i.VehicleNumber,
			&i.VehicleType,
			&i.CompanionsCount,
			&i.CompanionDetails,
			&i.ExpectedAt,
			&i.ExpectedCheckoutAt,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.AutoClosedAt,
			&i.ApprovedBy,
			&i.RejectedBy,
			&i.HandledByGuardID,
			&i.CreatedBy,
			&i.QrTokenHash,
			&i.QrExpiresAt,
			&i.QrUsedAt,
			&i.Notes,
			&i.RejectionReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApprovedAt,
			&i.DeliveryPartner,
			&i.ServiceProvider,
			&i.VisitorFullName,
			&i.VisitorPhoneNumber,
			&i.VisitorEmail,
			&i.VisitorPhotoUrl,
			&i.FlatNumber,
			&i.Block,
			&i.Floor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentVisitorEntriesByFlat = `-- name: ListRecentVisitorEntriesByFlat :many
SELECT
    ve.id, ve.society_id, ve.flat_id, ve.visitor_id, ve.invite_id, ve.source, ve.purpose, ve.status, ve.vehicle_number, ve.vehicle_type, ve.companions_count, ve.companion_details, ve.expected_at, ve.expected_checkout_at, ve.checked_in_at, ve.checked_out_at, ve.auto_closed_at, ve.approved_by, ve.rejected_by, ve.handled_by_guard_id, ve.created_by, ve.qr_token_hash, ve.qr_expires_at, ve.qr_used_at, ve.notes, ve.rejection_reason, ve.metadata, ve.created_at, ve.updated_at, ve.approved_at, ve.delivery_partner, ve.service_provider,
    v.full_name AS visitor_full_name,
    v.phone_number AS visitor_phone_number,
    v.email AS visitor_email,
    v.photo_url AS visitor_photo_url,
    f.flat_number,
    f.block,
    f.floor
FROM visitor_entries ve
JOIN visitors v ON v.id = ve.visitor_id
JOIN flats f ON f.id = ve.flat_id
WHERE ve.society_id = $1
  AND ve.flat_id = $2
ORDER BY ve.created_at DESC
LIMIT $3
`

type ListRecentVisitorEntriesByFlatParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
	Limit     int32 `db:"limit" json:"limit"`
}

type ListRecentVisitorEntriesByFlatRow struct {
	ID                 int64               `db:"id" json:"id"`
	SocietyID          int64               `db:"society_id" json:"society_id"`
	FlatID             int64               `db:"flat_id" json:"flat_id"`
	VisitorID          int64               `db:"visitor_id" json:"visitor_id"`
	InviteID           *int64              `db:"invite_id" json:"invite_id"`
	Source             VisitorSource       `db:"source" json:"source"`
	Purpose            VisitorPurpose      `db:"purpose" json:"purpose"`
	Status             VisitorStatus       `db:"status" json:"status"`
	VehicleNumber      *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType        *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionsCount    int32               `db:"companions_count" json:"companions_count"`
	CompanionDetails   []byte              `db:"companion_details" json:"companion_details"`
	ExpectedAt         pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	CheckedInAt        pgtype.Timestamptz  `db:"checked_in_at" json:"checked_in_at"`
	CheckedOutAt       pgtype.Timestamptz  `db:"checked_out_at" json:"checked_out_at"`
	AutoClosedAt       pgtype.Timestamptz  `db:"auto_closed_at" json:"auto_closed_at"`
	ApprovedBy         *int64              `db:"approved_by" json:"approved_by"`
	RejectedBy         *int64              `db:"rejected_by" json:"rejected_by"`
	HandledByGuardID   *int64              `db:"handled_by_guard_id" json:"handled_by_guard_id"`
	CreatedBy          *int64              `db:"created_by" json:"created_by"`
	QrTokenHash        *string             `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt        pgtype.Timestamptz  `db:"qr_expires_at" json:"qr_expires_at"`
	QrUsedAt           pgtype.Timestamptz  `db:"qr_used_at" json:"qr_used_at"`
	Notes              *string             `db:"notes" json:"notes"`
	RejectionReason    *string             `db:"rejection_reason" json:"rejection_reason"`
	Metadata           []byte              `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	ApprovedAt         pgtype.Timestamptz  `db:"approved_at" json:"approved_at"`
	DeliveryPartner    *string             `db:"delivery_partner" json:"delivery_partner"`
	ServiceProvider    *string             `db:"service_provider" json:"service_provider"`
	VisitorFullName    string              `db:"visitor_full_name" json:"visitor_full_name"`
	VisitorPhoneNumber *string             `db:"visitor_phone_number" json:"visitor_phone_number"`
	VisitorEmail       *string             `db:"visitor_email" json:"visitor_email"`
	VisitorPhotoUrl    *string             `db:"visitor_photo_url" json:"visitor_photo_url"`
	FlatNumber         string              `db:"flat_number" json:"flat_number"`
	Block              *string             `db:"block" json:"block"`
	Floor              *string             `db:"floor" json:"floor"`
}

func (q *Queries) ListRecentVisitorEntriesByFlat(ctx context.Context, arg ListRecentVisitorEntriesByFlatParams) ([]ListRecentVisitorEntriesByFlatRow, error) {
	rows, err := q.db.Query(ctx, listRecentVisitorEntriesByFlat, arg.SocietyID, arg.FlatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentVisitorEntriesByFlatRow{}
	for rows.Next() {
		var i ListRecentVisitorEntriesByFlatRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.FlatID,
			&i.VisitorID,
			&i.InviteID,
			&i.Source,
			&i.Purpose,
			&i.Status,
			&i.VehicleNumber,
			&i.VehicleType,
			&i.CompanionsCount,
			&i.CompanionDetails,
			&i.ExpectedAt,
			&i.ExpectedCheckoutAt,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.AutoClosedAt,
			&i.ApprovedBy,
			&i.RejectedBy,
			&i.HandledByGuardID,
			&i.CreatedBy,
			&i.QrTokenHash,
			&i.QrExpiresAt,
			&i.QrUsedAt,
			&i.Notes,
			&i.RejectionReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApprovedAt,
			&i.DeliveryPartner,
			&i.ServiceProvider,
			&i.VisitorFullName,
			&i.VisitorPhoneNumber,
			&i.VisitorEmail,
			&i.VisitorPhotoUrl,
			&i.FlatNumber,
			&i.Block,
			&i.Floor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocietyPendingVisitorApprovals = `-- name: ListSocietyPendingVisitorApprovals :many
SELECT
    ve.id, ve.society_id, ve.flat_id, ve.visitor_id, ve.invite_id, ve.source, ve.purpose, ve.status, ve.vehicle_number, ve.vehicle_type, ve.companions_count, ve.companion_details, ve.expected_at, ve.expected_checkout_at, ve.checked_in_at, ve.checked_out_at, ve.auto_closed_at, ve.approved_by, ve.rejected_by, ve.handled_by_guard_id, ve.created_by, ve.qr_token_hash, ve.qr_expires_at, ve.qr_used_at, ve.notes, ve.rejection_reason, ve.metadata, ve.created_at, ve.updated_at, ve.approved_at, ve.delivery_partner, ve.service_provider,
    v.full_name AS visitor_full_name,
    v.phone_number AS visitor_phone_number,
    v.email AS visitor_email,
    v.photo_url AS visitor_photo_url,
    f.flat_number,
    f.block,
    f.floor,
    u.full_name AS primary_resident_name,
    fr.id AS primary_resident_id
FROM visitor_entries ve
JOIN visitors v ON v.id = ve.visitor_id
JOIN flats f ON f.id = ve.flat_id
LEFT JOIN flat_residents fr
    ON fr.flat_id = ve.flat_id
   AND fr.society_id = ve.society_id
   AND fr.status = 'active'
   AND fr.is_primary = TRUE
LEFT JOIN users u ON u.id = fr.user_id
WHERE ve.society_id = $1
  AND ve.status = 'waiting_approval'
  AND ($2::bigint IS NULL OR ve.flat_id = $2::bigint)
  AND ($3::text IS NULL OR f.block = $3::text)
ORDER BY ve.created_at ASC
LIMIT $5 OFFSET $4
`

type ListSocietyPendingVisitorApprovalsParams struct {
	SocietyID int64   `db:"society_id" json:"society_id"`
	FlatID    *int64  `db:"flat_id" json:"flat_id"`
	Block     *string `db:"block" json:"block"`
	Offset    int32   `db:"offset" json:"offset"`
	Limit     int32   `db:"limit" json:"limit"`
}

type ListSocietyPendingVisitorApprovalsRow struct {
	ID                  int64               `db:"id" json:"id"`
	SocietyID           int64               `db:"society_id" json:"society_id"`
	FlatID              int64               `db:"flat_id" json:"flat_id"`
	VisitorID           int64               `db:"visitor_id" json:"visitor_id"`
	InviteID            *int64              `db:"invite_id" json:"invite_id"`
	Source              VisitorSource       `db:"source" json:"source"`
	Purpose             VisitorPurpose      `db:"purpose" json:"purpose"`
	Status              VisitorStatus       `db:"status" json:"status"`
	VehicleNumber       *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType         *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionsCount     int32               `db:"companions_count" json:"companions_count"`
	CompanionDetails    []byte              `db:"companion_details" json:"companion_details"`
	ExpectedAt          pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt  pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	CheckedInAt         pgtype.Timestamptz  `db:"checked_in_at" json:"checked_in_at"`
	CheckedOutAt        pgtype.Timestamptz  `db:"checked_out_at" json:"checked_out_at"`
	AutoClosedAt        pgtype.Timestamptz  `db:"auto_closed_at" json:"auto_closed_at"`
	ApprovedBy          *int64              `db:"approved_by" json:"approved_by"`
	RejectedBy          *int64              `db:"rejected_by" json:"rejected_by"`
	HandledByGuardID    *int64              `db:"handled_by_guard_id" json:"handled_by_guard_id"`
	CreatedBy           *int64              `db:"created_by" json:"created_by"`
	QrTokenHash         *string             `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt         pgtype.Timestamptz  `db:"qr_expires_at" json:"qr_expires_at"`
	QrUsedAt            pgtype.Timestamptz  `db:"qr_used_at" json:"qr_used_at"`
	Notes               *string             `db:"notes" json:"notes"`
	RejectionReason     *string             `db:"rejection_reason" json:"rejection_reason"`
	Metadata            []byte              `db:"metadata" json:"metadata"`
	CreatedAt           pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	ApprovedAt          pgtype.Timestamptz  `db:"approved_at" json:"approved_at"`
	DeliveryPartner     *string             `db:"delivery_partner" json:"delivery_partner"`
	ServiceProvider     *string             `db:"service_provider" json:"service_provider"`
	VisitorFullName     string              `db:"visitor_full_name" json:"visitor_full_name"`
	VisitorPhoneNumber  *string             `db:"visitor_phone_number" json:"visitor_phone_number"`
	VisitorEmail        *string             `db:"visitor_email" json:"visitor_email"`
	VisitorPhotoUrl     *string             `db:"visitor_photo_url" json:"visitor_photo_url"`
	FlatNumber          string              `db:"flat_number" json:"flat_number"`
	Block               *string             `db:"block" json:"block"`
	Floor               *string             `db:"floor" json:"floor"`
	PrimaryResidentName *string             `db:"primary_resident_name" json:"primary_resident_name"`
	PrimaryResidentID   *int64              `db:"primary_resident_id" json:"primary_resident_id"`
}

func (q *Queries) ListSocietyPendingVisitorApprovals(ctx context.Context, arg ListSocietyPendingVisitorApprovalsParams) ([]ListSocietyPendingVisitorApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listSocietyPendingVisitorApprovals,
		arg.SocietyID,
		arg.FlatID,
		arg.Block,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocietyPendingVisitorApprovalsRow{}
	for rows.Next() {
		var i ListSocietyPendingVisitorApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.FlatID,
			&i.VisitorID,
			&i.InviteID,
			&i.Source,
			&i.Purpose,
			&i.Status,
			&i.VehicleNumber,
			&i.VehicleType,
			&i.CompanionsCount,
			&i.CompanionDetails,
			&i.ExpectedAt,
			&i.ExpectedCheckoutAt,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.AutoClosedAt,
			&i.ApprovedBy,
			&i.RejectedBy,
			&i.HandledByGuardID,
			&i.CreatedBy,
			&i.QrTokenHash,
			&i.QrExpiresAt,
			&i.QrUsedAt,
			&i.Notes,
			&i.RejectionReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApprovedAt,
			&i.DeliveryPartner,
			&i.ServiceProvider,
			&i.VisitorFullName,
			&i.VisitorPhoneNumber,
			&i.VisitorEmail,
			&i.VisitorPhotoUrl,
			&i.FlatNumber,
			&i.Block,
			&i.Floor,
			&i.PrimaryResidentName,
			&i.PrimaryResidentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitorEntries = `-- name: ListVisitorEntries :many
SELECT
    ve.id, ve.society_id, ve.flat_id, ve.visitor_id, ve.invite_id, ve.source, ve.purpose, ve.status, ve.vehicle_number, ve.vehicle_type, ve.companions_count, ve.companion_details, ve.expected_at, ve.expected_checkout_at, ve.checked_in_at, ve.checked_out_at, ve.auto_closed_at, ve.approved_by, ve.rejected_by, ve.handled_by_guard_id, ve.created_by, ve.qr_token_hash, ve.qr_expires_at, ve.qr_used_at, ve.notes, ve.rejection_reason, ve.metadata, ve.created_at, ve.updated_at, ve.approved_at, ve.delivery_partner, ve.service_provider,
    v.full_name AS visitor_full_name,
    v.phone_number AS visitor_phone_number,
    v.email AS visitor_email,
    v.photo_url AS visitor_photo_url,
    f.flat_number,
    f.block,
    f.floor
FROM visitor_entries ve
JOIN visitors v ON v.id = ve.visitor_id
JOIN flats f ON f.id = ve.flat_id
WHERE ve.society_id = $1
  AND ($2::bigint IS NULL OR ve.flat_id = $2::bigint)
  AND ($3::visitor_status IS NULL OR ve.status = $3::visitor_status)
  AND ($4::visitor_source IS NULL OR ve.source = $4::visitor_source)
  AND ($5::visitor_purpose IS NULL OR ve.purpose = $5::visitor_purpose)
  AND ($6::text IS NULL OR f.block = $6::text)
  AND ($7::timestamptz IS NULL OR ve.created_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR ve.created_at < $8::timestamptz)
  AND (
      $9::text IS NULL
      OR $10::timestamptz IS NULL
      OR $11::timestamptz IS NULL
      OR (
          $9::text = 'created'
          AND ve.created_at >= $10::timestamptz
          AND ve.created_at < $11::timestamptz
      )
      OR (
          $9::text = 'checked_in'
          AND ve.checked_in_at IS NOT NULL
          AND ve.checked_in_at >= $10::timestamptz
          AND ve.checked_in_at < $11::timestamptz
      )
      OR (
          $9::text = 'checked_out'
          AND ve.checked_out_at IS NOT NULL
          AND ve.checked_out_at >= $10::timestamptz
          AND ve.checked_out_at < $11::timestamptz
      )
      OR (
          $9::text = 'expected'
          AND ve.expected_at IS NOT NULL
          AND ve.expected_at >= $10::timestamptz
          AND ve.expected_at < $11::timestamptz
      )
      OR (
          $9::text = 'activity'
          AND (
              (ve.created_at >= $10::timestamptz AND ve.created_at < $11::timestamptz)
              OR (
                  ve.checked_in_at IS NOT NULL
                  AND ve.checked_in_at >= $10::timestamptz
                  AND ve.checked_in_at < $11::timestamptz
              )
              OR (
                  ve.checked_out_at IS NOT NULL
                  AND ve.checked_out_at >= $10::timestamptz
                  AND ve.checked_out_at < $11::timestamptz
              )
          )
      )
  )
  AND (
      COALESCE($12::text, '') = ''
      OR v.full_name ILIKE '%' || $12::text || '%'
      OR COALESCE(v.phone_number, '') ILIKE '%' || $12::text || '%'
      OR COALESCE(f.flat_number, '') ILIKE '%' || $12::text || '%'
      OR COALESCE(f.block, '') ILIKE '%' || $12::text || '%'
  )
ORDER BY ve.created_at DESC
LIMIT $14 OFFSET $13
`

type ListVisitorEntriesParams struct {
	SocietyID   int64              `db:"society_id" json:"society_id"`
	FlatID      *int64             `db:"flat_id" json:"flat_id"`
	Status      *VisitorStatus     `db:"status" json:"status"`
	Source      *VisitorSource     `db:"source" json:"source"`
	Purpose     *VisitorPurpose    `db:"purpose" json:"purpose"`
	Block       *string            `db:"block" json:"block"`
	CreatedFrom pgtype.Timestamptz `db:"created_from" json:"created_from"`
	CreatedTo   pgtype.Timestamptz `db:"created_to" json:"created_to"`
	Event       *string            `db:"event" json:"event"`
	EventFrom   pgtype.Timestamptz `db:"event_from" json:"event_from"`
	EventTo     pgtype.Timestamptz `db:"event_to" json:"event_to"`
	Search      *string            `db:"search" json:"search"`
	Offset      int32              `db:"offset" json:"offset"`
	Limit       int32              `db:"limit" json:"limit"`
}

type ListVisitorEntriesRow struct {
	ID                 int64               `db:"id" json:"id"`
	SocietyID          int64               `db:"society_id" json:"society_id"`
	FlatID             int64               `db:"flat_id" json:"flat_id"`
	VisitorID          int64               `db:"visitor_id" json:"visitor_id"`
	InviteID           *int64              `db:"invite_id" json:"invite_id"`
	Source             VisitorSource       `db:"source" json:"source"`
	Purpose            VisitorPurpose      `db:"purpose" json:"purpose"`
	Status             VisitorStatus       `db:"status" json:"status"`
	VehicleNumber      *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType        *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionsCount    int32               `db:"companions_count" json:"companions_count"`
	CompanionDetails   []byte              `db:"companion_details" json:"companion_details"`
	ExpectedAt         pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	CheckedInAt        pgtype.Timestamptz  `db:"checked_in_at" json:"checked_in_at"`
	CheckedOutAt       pgtype.Timestamptz  `db:"checked_out_at" json:"checked_out_at"`
	AutoClosedAt       pgtype.Timestamptz  `db:"auto_closed_at" json:"auto_closed_at"`
	ApprovedBy         *int64              `db:"approved_by" json:"approved_by"`
	RejectedBy         *int64              `db:"rejected_by" json:"rejected_by"`
	HandledByGuardID   *int64              `db:"handled_by_guard_id" json:"handled_by_guard_id"`
	CreatedBy          *int64              `db:"created_by" json:"created_by"`
	QrTokenHash        *string             `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt        pgtype.Timestamptz  `db:"qr_expires_at" json:"qr_expires_at"`
	QrUsedAt           pgtype.Timestamptz  `db:"qr_used_at" json:"qr_used_at"`
	Notes              *string             `db:"notes" json:"notes"`
	RejectionReason    *string             `db:"rejection_reason" json:"rejection_reason"`
	Metadata           []byte              `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	ApprovedAt         pgtype.Timestamptz  `db:"approved_at" json:"approved_at"`
	DeliveryPartner    *string             `db:"delivery_partner" json:"delivery_partner"`
	ServiceProvider    *string             `db:"service_provider" json:"service_provider"`
	VisitorFullName    string              `db:"visitor_full_name" json:"visitor_full_name"`
	VisitorPhoneNumber *string             `db:"visitor_phone_number" json:"visitor_phone_number"`
	VisitorEmail       *string             `db:"visitor_email" json:"visitor_email"`
	VisitorPhotoUrl    *string             `db:"visitor_photo_url" json:"visitor_photo_url"`
	FlatNumber         string              `db:"flat_number" json:"flat_number"`
	Block              *string             `db:"block" json:"block"`
	Floor              *string             `db:"floor" json:"floor"`
}

func (q *Queries) ListVisitorEntries(ctx context.Context, arg ListVisitorEntriesParams) ([]ListVisitorEntriesRow, error) {
	rows, err := q.db.Query(ctx, listVisitorEntries,
		arg.SocietyID,
		arg.FlatID,
		arg.Status,
		arg.Source,
		arg.Purpose,
		arg.Block,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Event,
		arg.EventFrom,
		arg.EventTo,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisitorEntriesRow{}
	for rows.Next() {
		var i ListVisitorEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.FlatID,
			&i.VisitorID,
			&i.InviteID,
			&i.Source,
			&i.Purpose,
			&i.Status,
			&i.VehicleNumber,
			&i.VehicleType,
			&i.CompanionsCount,
			&i.CompanionDetails,
			&i.ExpectedAt,
			&i.ExpectedCheckoutAt,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.AutoClosedAt,
			&i.ApprovedBy,
			&i.RejectedBy,
			&i.HandledByGuardID,
			&i.CreatedBy,
			&i.QrTokenHash,
			&i.QrExpiresAt,
			&i.QrUsedAt,
			&i.Notes,
			&i.RejectionReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApprovedAt,
			&i.DeliveryPartner,
			&i.ServiceProvider,
			&i.VisitorFullName,
			&i.VisitorPhoneNumber,
			&i.VisitorEmail,
			&i.VisitorPhotoUrl,
			&i.FlatNumber,
			&i.Block,
			&i.Floor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitorEntryEvents = `-- name: ListVisitorEntryEvents :many
SELECT id, visitor_entry_id, society_id, actor_user_id, event_type, message, metadata, created_at
FROM visitor_entry_events
WHERE visitor_entry_id = $1
  AND society_id = $2
ORDER BY created_at DESC
`

type ListVisitorEntryEventsParams struct {
	VisitorEntryID int64 `db:"visitor_entry_id" json:"visitor_entry_id"`
	SocietyID      int64 `db:"society_id" json:"society_id"`
}

func (q *Queries) ListVisitorEntryEvents(ctx context.Context, arg ListVisitorEntryEventsParams) ([]VisitorEntryEvent, error) {
	rows, err := q.db.Query(ctx, listVisitorEntryEvents, arg.VisitorEntryID, arg.SocietyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VisitorEntryEvent{}
	for rows.Next() {
		var i VisitorEntryEvent
		if err := rows.Scan(
			&i.ID,
			&i.VisitorEntryID,
			&i.SocietyID,
			&i.ActorUserID,
			&i.EventType,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingAtGateVisitorEntries = `-- name: ListWaitingAtGateVisitorEntries :many
SELECT
    ve.id, ve.society_id, ve.flat_id, ve.visitor_id, ve.invite_id, ve.source, ve.purpose, ve.status, ve.vehicle_number, ve.vehicle_type, ve.companions_count, ve.companion_details, ve.expected_at, ve.expected_checkout_at, ve.checked_in_at, ve.checked_out_at, ve.auto_closed_at, ve.approved_by, ve.rejected_by, ve.handled_by_guard_id, ve.created_by, ve.qr_token_hash, ve.qr_expires_at, ve.qr_used_at, ve.notes, ve.rejection_reason, ve.metadata, ve.created_at, ve.updated_at, ve.approved_at, ve.delivery_partner, ve.service_provider,
    v.full_name AS visitor_full_name,
    v.phone_number AS visitor_phone_number,
    v.email AS visitor_email,
    v.photo_url AS visitor_photo_url,
    f.flat_number,
    f.block,
    f.floor
FROM visitor_entries ve
JOIN visitors v ON v.id = ve.visitor_id
JOIN flats f ON f.id = ve.flat_id
WHERE ve.society_id = $1
  AND ve.status = 'approved'
  AND (
      COALESCE($2::text, '') = ''
      OR v.full_name ILIKE '%' || $2::text || '%'
      OR COALESCE(v.phone_number, '') ILIKE '%' || $2::text || '%'
      OR COALESCE(f.flat_number, '') ILIKE '%' || $2::text || '%'
      OR COALESCE(f.block, '') ILIKE '%' || $2::text || '%'
      OR COALESCE(ve.vehicle_number, '') ILIKE '%' || $2::text || '%'
      OR COALESCE(ve.delivery_partner, '') ILIKE '%' || $2::text || '%'
      OR ve.purpose::text ILIKE '%' || $2::text || '%'
  )
ORDER BY ve.approved_at ASC NULLS LAST, ve.created_at ASC
LIMIT $4 OFFSET $3
`

type ListWaitingAtGateVisitorEntriesParams struct {
	SocietyID int64   `db:"society_id" json:"society_id"`
	Search    *string `db:"search" json:"search"`
	Offset    int32   `db:"offset" json:"offset"`
	Limit     int32   `db:"limit" json:"limit"`
}

type ListWaitingAtGateVisitorEntriesRow struct {
	ID                 int64               `db:"id" json:"id"`
	SocietyID          int64               `db:"society_id" json:"society_id"`
	FlatID             int64               `db:"flat_id" json:"flat_id"`
	VisitorID          int64               `db:"visitor_id" json:"visitor_id"`
	InviteID           *int64              `db:"invite_id" json:"invite_id"`
	Source             VisitorSource       `db:"source" json:"source"`
	Purpose            VisitorPurpose      `db:"purpose" json:"purpose"`
	Status             VisitorStatus       `db:"status" json:"status"`
	VehicleNumber      *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType        *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionsCount    int32               `db:"companions_count" json:"companions_count"`
	CompanionDetails   []byte              `db:"companion_details" json:"companion_details"`
	ExpectedAt         pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	CheckedInAt        pgtype.Timestamptz  `db:"checked_in_at" json:"checked_in_at"`
	CheckedOutAt       pgtype.Timestamptz  `db:"checked_out_at" json:"checked_out_at"`
	AutoClosedAt       pgtype.Timestamptz  `db:"auto_closed_at" json:"auto_closed_at"`
	ApprovedBy         *int64              `db:"approved_by" json:"approved_by"`
	RejectedBy         *int64              `db:"rejected_by" json:"rejected_by"`
	HandledByGuardID   *int64              `db:"handled_by_guard_id" json:"handled_by_guard_id"`
	CreatedBy          *int64              `db:"created_by" json:"created_by"`
	QrTokenHash        *string             `db:"qr_token_hash" json:"qr_token_hash"`
	QrExpiresAt        pgtype.Timestamptz  `db:"qr_expires_at" json:"qr_expires_at"`
	QrUsedAt           pgtype.Timestamptz  `db:"qr_used_at" json:"qr_used_at"`
	Notes              *string             `db:"notes" json:"notes"`
	RejectionReason    *string             `db:"rejection_reason" json:"rejection_reason"`
	Metadata           []byte              `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
	ApprovedAt         pgtype.Timestamptz  `db:"approved_at" json:"approved_at"`
	DeliveryPartner    *string             `db:"delivery_partner" json:"delivery_partner"`
	ServiceProvider    *string             `db:"service_provider" json:"service_provider"`
	VisitorFullName    string              `db:"visitor_full_name" json:"visitor_full_name"`
	VisitorPhoneNumber *string             `db:"visitor_phone_number" json:"visitor_phone_number"`
	VisitorEmail       *string             `db:"visitor_email" json:"visitor_email"`
	VisitorPhotoUrl    *string             `db:"visitor_photo_url" json:"visitor_photo_url"`
	FlatNumber         string              `db:"flat_number" json:"flat_number"`
	Block              *string             `db:"block" json:"block"`
	Floor              *string             `db:"floor" json:"floor"`
}

func (q *Queries) ListWaitingAtGateVisitorEntries(ctx context.Context, arg ListWaitingAtGateVisitorEntriesParams) ([]ListWaitingAtGateVisitorEntriesRow, error) {
	rows, err := q.db.Query(ctx, listWaitingAtGateVisitorEntries,
		arg.SocietyID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWaitingAtGateVisitorEntriesRow{}
	for rows.Next() {
		var i ListWaitingAtGateVisitorEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.FlatID,
			&i.VisitorID,
			&i.InviteID,
			&i.Source,
			&i.Purpose,
			&i.Status,
			&i.VehicleNumber,
			&i.VehicleType,
			&i.CompanionsCount,
			&i.CompanionDetails,
			&i.ExpectedAt,
			&i.ExpectedCheckoutAt,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.AutoClosedAt,
			&i.ApprovedBy,
			&i.RejectedBy,
			&i.HandledByGuardID,
			&i.CreatedBy,
			&i.QrTokenHash,
			&i.QrExpiresAt,
			&i.QrUsedAt,
			&i.Notes,
			&i.RejectionReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApprovedAt,
			&i.DeliveryPartner,
			&i.ServiceProvider,
			&i.VisitorFullName,
			&i.VisitorPhoneNumber,
			&i.VisitorEmail,
			&i.VisitorPhotoUrl,
			&i.FlatNumber,
			&i.Block,
			&i.Floor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVisitorInviteUsed = `-- name: MarkVisitorInviteUsed :one
UPDATE visitor_invites
SET status = 'used',
    used_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'active'
RETURNING id, society_id, flat_id, created_by, purpose, token_hash, status, expires_at, used_at, metadata, created_at, updated_at
`

func (q *Queries) MarkVisitorInviteUsed(ctx context.Context, id int64) (VisitorInvite, error) {
	row := q.db.QueryRow(ctx, markVisitorInviteUsed, id)
	var i VisitorInvite
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.CreatedBy,
		&i.Purpose,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mergeVisitorEntryMetadata = `-- name: MergeVisitorEntryMetadata :one
UPDATE visitor_entries
SET metadata = COALESCE(metadata, '{}'::jsonb) || $1::jsonb,
    updated_at = NOW()
WHERE id = $2
  AND society_id = $3
RETURNING id, society_id, flat_id, visitor_id, invite_id, source, purpose, status, vehicle_number, vehicle_type, companions_count, companion_details, expected_at, expected_checkout_at, checked_in_at, checked_out_at, auto_closed_at, approved_by, rejected_by, handled_by_guard_id, created_by, qr_token_hash, qr_expires_at, qr_used_at, notes, rejection_reason, metadata, created_at, updated_at, approved_at, delivery_partner, service_provider
`

type MergeVisitorEntryMetadataParams struct {
	MetadataPatch []byte `db:"metadata_patch" json:"metadata_patch"`
	ID            int64  `db:"id" json:"id"`
	SocietyID     int64  `db:"society_id" json:"society_id"`
}

func (q *Queries) MergeVisitorEntryMetadata(ctx context.Context, arg MergeVisitorEntryMetadataParams) (VisitorEntry, error) {
	row := q.db.QueryRow(ctx, mergeVisitorEntryMetadata, arg.MetadataPatch, arg.ID, arg.SocietyID)
	var i VisitorEntry
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.VisitorID,
		&i.InviteID,
		&i.Source,
		&i.Purpose,
		&i.Status,
		&i.VehicleNumber,
		&i.VehicleType,
		&i.CompanionsCount,
		&i.CompanionDetails,
		&i.ExpectedAt,
		&i.ExpectedCheckoutAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.AutoClosedAt,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.HandledByGuardID,
		&i.CreatedBy,
		&i.QrTokenHash,
		&i.QrExpiresAt,
		&i.QrUsedAt,
		&i.Notes,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovedAt,
		&i.DeliveryPartner,
		&i.ServiceProvider,
	)
	return i, err
}

const rejectVisitorEntry = `-- name: RejectVisitorEntry :one
UPDATE visitor_entries
SET status = 'rejected',
    rejected_by = $3,
    rejection_reason = $4,
    updated_at = NOW()
WHERE id = $1
  AND society_id = $2
  AND status = 'waiting_approval'
RETURNING id, society_id, flat_id, visitor_id, invite_id, source, purpose, status, vehicle_number, vehicle_type, companions_count, companion_details, expected_at, expected_checkout_at, checked_in_at, checked_out_at, auto_closed_at, approved_by, rejected_by, handled_by_guard_id, created_by, qr_token_hash, qr_expires_at, qr_used_at, notes, rejection_reason, metadata, created_at, updated_at, approved_at, delivery_partner, service_provider
`

type RejectVisitorEntryParams struct {
	ID              int64   `db:"id" json:"id"`
	SocietyID       int64   `db:"society_id" json:"society_id"`
	RejectedBy      *int64  `db:"rejected_by" json:"rejected_by"`
	RejectionReason *string `db:"rejection_reason" json:"rejection_reason"`
}

func (q *Queries) RejectVisitorEntry(ctx context.Context, arg RejectVisitorEntryParams) (VisitorEntry, error) {
	row := q.db.QueryRow(ctx, rejectVisitorEntry,
		arg.ID,
		arg.SocietyID,
		arg.RejectedBy,
		arg.RejectionReason,
	)
	var i VisitorEntry
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.FlatID,
		&i.VisitorID,
		&i.InviteID,
		&i.Source,
		&i.Purpose,
		&i.Status,
		&i.VehicleNumber,
		&i.VehicleType,
		&i.CompanionsCount,
		&i.CompanionDetails,
		&i.ExpectedAt,
		&i.ExpectedCheckoutAt,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.AutoClosedAt,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.HandledByGuardID,
		&i.CreatedBy,
		&i.QrTokenHash,
		&i.QrExpiresAt,
		&i.QrUsedAt,
		&i.Notes,
		&i.RejectionReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovedAt,
		&i.DeliveryPartner,
		&i.ServiceProvider,
	)
	return i, err
}
