export const ACTIVITY_PAGE_SIZE = 5;
export const ACTIVITY_VISIBLE_ROWS = ACTIVITY_PAGE_SIZE;
export const ACTIVITY_ROW_HEIGHT = 72;
export const ACTIVITY_LIST_HEIGHT = ACTIVITY_ROW_HEIGHT * ACTIVITY_VISIBLE_ROWS;
